"""
build_third_phase_tests.py
===========================
Third-phase chapter tests: AS 11, AS 22, AS 20, Framework. Same selection
logic, sources and honesty rules as build_second_phase_tests.py (imported and
re-pointed, not copied) - real MTP/RTP/PYQ content first, ICAI Test Your
Knowledge only as a top-up, nothing invented, short tests accepted as short.

Output (first_run/TESTS/third phase/):
  <AS>_Questions.md, <AS>_Questions_and_Answers.md, README.md   - for self
  student-edition/<AS>_Questions.pdf, <AS>_Answers.pdf          - student-facing
"""
import json
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import build_second_phase_tests as p2
import extract_study_material_tyk as tyk
import convert_tests_to_pdf as pdfconv

REPO = Path(r"D:\EffCorp_Projects\cap-online")
RAW = REPO / "books" / "ca-inter" / "concept-book" / "raw_icai_study_materials"
OUT = REPO / "first_run" / "TESTS" / "third phase"
STUDENT = OUT / "student-edition"
TYK_JSON = REPO / "first_run" / "output" / "generated-from-script" / "study_material_tyk_phase3.json"

CHAPTERS = {
    "as11": ("M2_C7_U3_ Accounting Standard 11 The Effects of Changes in Foreign Exchange Rates.md", "M2-C7-U3",
             "AS 11 — The Effects of Changes in Foreign Exchange Rates"),
    "as22": ("M2_C7_U4_ Accounting Standard 22 Accounting for Taxes on Income.md", "M2-C7-U4",
             "AS 22 — Accounting for Taxes on Income"),
    "as20": ("M1_C4_U5_ Accounting Standard 20 Earnings Per Share.md", "M1-C4-U5", "AS 20 — Earnings Per Share"),
    "framework": ("M1_C2_U1_ Framework for Preparation and Presentation of Financial Statements.md", "M1-C2-U0",
                  "Framework for Preparation and Presentation of Financial Statements"),
}

# --- re-point phase-2 module ---
tyk.SRC_DIR = RAW
tyk.OUT_PATH = TYK_JSON
tyk.CHAPTERS = CHAPTERS
p2.STUDY_TYK_PATH = TYK_JSON
p2.AS_LIST = list(CHAPTERS)
p2.CHAPTER_MAP = {k: v[1] for k, v in CHAPTERS.items()}
p2.AS_NAME = {k: v[2] for k, v in CHAPTERS.items()}


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    STUDENT.mkdir(parents=True, exist_ok=True)
    tyk.main()
    mcq_pool = p2.load_json(p2.MCQ_PATH)
    desc_pool = p2.load_json(p2.DESC_PATH)
    tests = []
    for k in CHAPTERS:
        t = p2.build_test(k, mcq_pool, desc_pool)
        tests.append(t)
        q_md = p2.render_questions_md(t)
        qa_md = p2.render_answers_md(t)
        (OUT / f"{k.upper()}_Questions.md").write_text(q_md, encoding="utf-8")
        (OUT / f"{k.upper()}_Questions_and_Answers.md").write_text(qa_md, encoding="utf-8")
        # answers-only student file: header + the "## Answers" block
        head = "\n".join(p2.render_header(t))
        ans_part = qa_md[qa_md.index("## Answers"):]
        a_md = f"{head}\n## Answer Key\n\n" + ans_part[len("## Answers"):]
        tmp_dir = OUT / "_tmp"
        tmp_dir.mkdir(exist_ok=True)
        (tmp_dir / f"{k.upper()}_Questions.md").write_text(q_md, encoding="utf-8")
        (tmp_dir / f"{k.upper()}_Answers.md").write_text(a_md, encoding="utf-8")
        print(f"{k.upper():10} {t['achieved_total']}/50  MCQ {t['mcq_marks']} ({t['mcq_count']}q)  "
              f"DESC {t['desc_marks']} ({t['desc_count']}q)  pool max {t['max_total_available']}  study={t['used_study_material']}")
    pdfconv.convert_all(OUT / "_tmp", STUDENT)
    for f in (OUT / "_tmp").glob("*.md"):
        f.unlink()
    (OUT / "_tmp").rmdir()

    L = ["# Third Phase — Chapter Tests (MCQ + Descriptive, up to 50 Marks)", "",
         "AS 11, AS 22, AS 20 and Framework — the chapters completed in class after AS 12. Same method and sources as "
         "Phase 2 (`build_second_phase_tests.py`): real MTP/RTP/PYQ questions first (official marks), ICAI "
         "\"Test Your Knowledge\" only as a top-up (marks estimated, tagged). Nothing invented; short tests are "
         "accepted as short. Generated by `first_run/scripts/build_third_phase_tests.py`.", "",
         "`*.md` here are for self. `student-edition/` holds the watermarked PDFs: Questions and Answers separately.", "",
         "| Chapter | Marks | MCQ | Descriptive | Study material | Status |", "|---|---|---|---|---|---|"]
    for t in tests:
        st = "OK — full 50" if t["achieved_total"] >= 50 else f"**SHORT — {t['achieved_total']}/50** (pool max {t['max_total_available']})"
        L.append(f"| {t['name']} | {t['achieved_total']}/50 | {t['mcq_marks']} ({t['mcq_count']}q) | "
                 f"{t['desc_marks']} ({t['desc_count']}q) | {'Yes' if t['used_study_material'] else 'No'} | {st} |")
    L += ["", f"*Generated: {date.today().isoformat()}*", ""]
    (OUT / "README.md").write_text("\n".join(L), encoding="utf-8")


if __name__ == "__main__":
    main()
