#!/usr/bin/env python3
"""
qb_merge.py: Question Bank Book: whole-book assembler
=========================================================

Same job as tools/strategy_book_merge.py, done for the Question Bank Book:
stitch independent, already-finished files (34 per-chapter files whose
"main content is done" per Pranav, plus front-matter.html and
back-matter.html) into ONE continuous HTML document so paged.js can
paginate the whole book as a single flow -- the only way to get continuous
page numbers and a running header that's correct on every physical page.

Read the strategy book's merge script docstring first if you haven't --
this file reuses every lesson from it (duplicate-style detection, id
collisions, page-break-per-section, vendor-path safety, an explicit
human-edited BOOK_ORDER cross-checked against what's actually on disk).
Only what's genuinely different about the Question Bank Book is explained
below.

WHAT'S DIFFERENT FROM THE STRATEGY BOOK MERGE
------------------------------------------------
1. TWO style layers, not one. The 34 chapter files share one embedded
   <style> (verified byte-identical -- qb_common.verify_shared_style).
   front-matter.html and back-matter.html carry a DIFFERENT, richer style
   (title page, copyright page, author bio -- classes the chapters never
   use). Rather than pick one file as "the" reference style (which is what
   the strategy book does, because every one of its files shares the exact
   same style), this script builds the merged <head> additively out of
   three known-safe pieces: the verified chapter style, qb_common's shared
   print/pagination layer, and qb_common's shared front/back-matter layer.
   front-matter.html and back-matter.html contribute only their BODY
   content here -- their own <style> tags are never pulled into the merged
   file, since qb_common.front_back_css() already IS that style, shared
   losslessly with the two generator scripts that use it.

2. The id="AS02-NNN" bug (see qb_common.py's module docstring) is fixed
   here at merge time via qb_common.rewrite_qblock_ids(), applied through
   qb_common.page_shell() for every chapter. front-matter.html and
   back-matter.html don't have this bug (they were never generated by the
   buggy generate_chapter_book.py), so they're inserted as-is.

3. Running header/footer only appear on chapter pages, not front/back
   matter -- ordinary book convention (a title page or copyright page
   doesn't carry a running header). qb_common.page_shell() adds the
   running-header/footer elements; front/back matter content is inserted
   directly without that wrapper.

4. Vendor paths are NOT "../vendor/..." like the strategy book -- this
   script writes its output directly into first_run/output/, the same
   folder vendor/ already lives in (see qb_common.VENDOR_DIR), so a plain
   "vendor/paged.polyfill.js" relative path is correct as-is.

USAGE
-----
    python qb_merge.py
        Merge using BOOK_ORDER below, write
        first_run/output/QUESTION-BANK-BOOK.html

    python qb_merge.py --force
        Proceed past an orphaned-file warning (a file sits in output/ that
        isn't listed in BOOK_ORDER) instead of stopping. Never overrides a
        missing-file error -- there's nothing sensible to substitute for a
        missing chapter.

After running: open the file in Chrome, wait for paged.js to finish
repainting (a 34-chapter book will take noticeably longer than any single
section -- that's expected, not a hang), then Ctrl+P -> Save as PDF with
Background graphics enabled.
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import qb_common as qc  # noqa: E402

# ── Chapter order ────────────────────────────────────────────────────────
# Teaching-sequence order, cross-referenced against
# books/concept-book/syllabus-engine/data/1-ca-inter-adv-accounts-topic-page-index.json's
# `teaching_sequence` field (2026-07-25). Two syllabus chapter pairs each
# collapse into ONE file here (Financial Statements: teaching_sequence 22 +
# 23A share one file; Amalgamation: 30A + AS 14 at 30B share one file,
# because pre-Ind-AS "AS 14" IS "Accounting for Amalgamations" -- confirmed
# directly from AS14_Question_Book.html's own <title>, "AS 14 (Amalgamation
# of Companies)"). This is why there are 34 files for 36 syllabus chapters,
# not a missing-file bug.
#
# Each entry: (slug, filename, chapter_label, study_material_ref). slug
# becomes both the id="{slug}" prefix (fixing the id="AS02-NNN" bug -- see
# qb_common.py) and the ToC/page-resolver anchor target -- keep it stable
# once the book has been through a real print run, since re-slugging breaks
# old links.
#
# study_material_ref (added 2026-07-26, Pranav's request: students should
# be able to jump from a Question Bank chapter straight to the matching
# study-material chapter) is each chapter's `unique_chapter_id` from
# books/concept-book/syllabus-engine/data/1-ca-inter-adv-accounts-topic-page-index.json
# -- deliberately that file, not metadata-index/topic-index.json, even
# though topic-index.json is the one already used for each QUESTION's own
# subtopic tag (the "AS 2 (1.4)" you see under every question -- that's
# unrelated and untouched). topic-index.json only covers 32 of 36 chapters
# and is explicitly documented (CLAUDE.md section 6) as secondary to file 1
# for chapter IDs; file 1 covers all 36, including the 2 (AS 1, AS 27)
# topic-index.json is still missing entirely. For the two chapters that
# fold two syllabus entries into one file (Financial Statements;
# Amalgamation/AS 14 -- see the comment above CHAPTERS), the ref shown is
# the one that's actually the chapter's real identity in that file's own
# title, not both codes.
CHAPTERS = (
    ("intro-to-as", "IntroToAS_Question_Book.html", "Intro to AS", "M1-C1-U0"),
    ("applicability-of-as", "ApplicabilityOfAS_Question_Book.html", "Applicability of AS", "M1-C3-U0"),
    ("framework", "Framework_Question_Book.html", "Framework for Preparation and Presentation of Financial Statements", "M1-C2-U0"),
    ("as02", "AS02_Question_Book.html", "AS 2: Valuation of Inventories", "M2-C5-U1"),
    ("as10", "AS10_Question_Book.html", "AS 10: Property, Plant and Equipment", "M2-C5-U2"),
    ("as26", "AS26_Question_Book.html", "AS 26: Intangible Assets", "M2-C5-U6"),
    ("as16", "AS16_Question_Book.html", "AS 16: Borrowing Costs", "M2-C5-U4"),
    ("as19", "AS19_Question_Book.html", "AS 19: Leases", "M2-C5-U5"),
    ("as28", "AS28_Question_Book.html", "AS 28: Impairment of Assets", "M2-C5-U7"),
    ("as13", "AS13_Question_Book.html", "AS 13: Accounting for Investments", "M2-C5-U3"),
    ("as29", "AS29_Question_Book.html", "AS 29: Provisions, Contingent Liabilities and Contingent Assets", "M2-C6-U2"),
    ("as15", "AS15_Question_Book.html", "AS 15: Employee Benefits", "M2-C6-U1"),
    ("as04", "AS04_Question_Book.html", "AS 4: Contingencies and Events Occurring After the Balance Sheet Date", "M2-C7-U1"),
    ("as05", "AS05_Question_Book.html", "AS 5: Net Profit or Loss, Prior Period Items and Changes in Accounting Policies", "M2-C7-U2"),
    ("as11", "AS11_Question_Book.html", "AS 11: The Effects of Changes in Foreign Exchange Rates", "M2-C7-U3"),
    ("as09", "AS09_Question_Book.html", "AS 9: Revenue Recognition", "M2-C8-U2"),
    ("as07", "AS07_Question_Book.html", "AS 7: Construction Contracts", "M2-C8-U1"),
    ("as12", "AS12_Question_Book.html", "AS 12: Accounting for Government Grants", "M2-C9-U1"),
    ("as22", "AS22_Question_Book.html", "AS 22: Accounting for Taxes on Income", "M2-C7-U4"),
    ("as20", "AS20_Question_Book.html", "AS 20: Earnings Per Share", "M1-C4-U5"),
    ("as01", "AS01_Question_Book.html", "AS 1: Disclosure of Accounting Policies", "M1-C4-U1"),
    ("financial-statements", "FinancialStatements_Question_Book.html", "Financial Statements of Companies (Schedule III)", "M3-C11-U1"),
    ("cash-flow-statement", "CashFlowStatement_Question_Book.html", "Cash Flow Statement (AS 3)", "M1-C4-U2"),
    ("as17", "AS17_Question_Book.html", "AS 17: Segment Reporting", "M1-C4-U3"),
    ("as18", "AS18_Question_Book.html", "AS 18: Related Party Disclosures", "M1-C4-U4"),
    ("as24", "AS24_Question_Book.html", "AS 24: Discontinuing Operations", "M1-C4-U6"),
    ("as21", "AS21_Question_Book.html", "AS 21: Consolidated Financial Statements", "M2-C10-U1"),
    ("as23", "AS23_Question_Book.html", "AS 23: Accounting for Investments in Associates in CFS", "M2-C10-U2"),
    ("as27", "AS27_Question_Book.html", "AS 27: Financial Reporting of Interests in Joint Ventures", "M2-C10-U3"),
    ("as14", "AS14_Question_Book.html", "AS 14: Amalgamation of Companies", "M3-C13-U0"),
    ("as25", "AS25_Question_Book.html", "AS 25: Interim Financial Reporting", "M1-C4-U7"),
    ("buyback", "Buyback_Question_Book.html", "Buy-back of Securities", "M3-C12-U0"),
    ("internal-reconstruction", "InternalReconstruction_Question_Book.html", "Internal Reconstruction", "M3-C14-U0"),
    ("branch-accounting", "BranchAccounting_Question_Book.html", "Accounting for Branches Including Foreign Branches", "M3-C15-U0"),
)

# Front-to-back order of the finished book, expressed as plain slugs (same
# pattern as strategy_book_merge.py's BOOK_ORDER) -- "front-matter" and
# "back-matter" are special-cased in build_merged_html() below, everything
# else is looked up in CHAPTERS.
BOOK_ORDER = ("front-matter",) + tuple(c[0] for c in CHAPTERS) + ("back-matter",)

FRONT_MATTER_FILE = "front-matter.html"
BACK_MATTER_FILE = "back-matter.html"

_SLUG_TO_CHAPTER = {
    slug: (filename, label, study_ref) for slug, filename, label, study_ref in CHAPTERS
}

MERGE_ONLY_CSS = """
/* ── Added only for the merged whole-book file (qb_merge.py) ──
   Belt-and-braces: .qb-section already carries break-before:page from
   qb_common.print_layer_css(), this just documents that the merge is what
   makes the rule meaningful (a lone file has nothing to break away from). */
"""


def validate_order(order: tuple, output_dir: Path, output_name: str, force: bool) -> None:
    """Cross-check BOOK_ORDER against what's actually in output/ -- same
    two-directional check as strategy_book_merge.py's validate_order()."""
    missing = []
    for slug in order:
        if slug == "front-matter":
            candidates = [output_dir / FRONT_MATTER_FILE]
        elif slug == "back-matter":
            candidates = [output_dir / BACK_MATTER_FILE]
        else:
            filename, _label, _ref = _SLUG_TO_CHAPTER[slug]
            candidates = [output_dir / filename, qc.CHAPTERS_DIR / filename]
        if not any(c.exists() for c in candidates):
            missing.append(f"{slug} -> {candidates[-1].name} (checked: "
                            + ", ".join(str(c.parent) for c in candidates) + ")")
    if missing:
        raise SystemExit(
            "ERROR: BOOK_ORDER lists section(s) with no file on disk:\n  "
            + "\n  ".join(missing)
        )

    # Only *_Question_Book.html files are candidate chapters -- the sitting-
    # level Layer 1 files (MTP_*.html, PYQ_*.html, RTP_*.html) also live
    # nearby but are raw per-sitting source, never merged into the book
    # directly (see CLAUDE.md section 6's pipeline description). Checked in
    # BOTH output/ and output/generated-from-script/ -- see qb_common.py's
    # CHAPTERS_DIR comment for why the chapter files' location isn't fixed.
    chapter_filenames = {c[1] for c in CHAPTERS}
    all_book_files = {p.name for p in output_dir.glob("*_Question_Book.html")}
    if qc.CHAPTERS_DIR.is_dir():
        all_book_files |= {p.name for p in qc.CHAPTERS_DIR.glob("*_Question_Book.html")}
    orphaned = sorted(all_book_files - chapter_filenames)
    if orphaned:
        msg = (
            "*_Question_Book.html-shaped file(s) exist in output/ but "
            "aren't listed in CHAPTERS (they will be silently left out of "
            "the merged book):\n  " + "\n  ".join(orphaned)
        )
        if force:
            print(f"WARNING: {msg}\n(--force: proceeding anyway)")
        else:
            raise SystemExit(
                f"ERROR: {msg}\n"
                "Add them to CHAPTERS in this script, or re-run with "
                "--force if leaving them out is intentional."
            )


def check_vendor_present(output_dir: Path) -> None:
    """Same sanity check as strategy_book_merge.py's check_vendor_present()
    -- the merged file references vendor/ with a plain relative path since
    it lives in the same folder vendor/ is already in (see module
    docstring point 4)."""
    polyfill = output_dir / "vendor" / "paged.polyfill.js"
    fonts_css = output_dir / "vendor" / "gfonts-local.css"
    missing = [p for p in (polyfill, fonts_css) if not p.exists()]
    if missing:
        raise SystemExit(
            "ERROR: missing vendor file(s), the merged book would silently "
            "fail to paginate/render fonts:\n  "
            + "\n  ".join(str(p) for p in missing)
        )


def build_merged_html(output_dir: Path, order: tuple, style: dict) -> str:
    shared_chapter_style = qc.verify_shared_style([c[1] for c in CHAPTERS])
    # Fonts are INLINED (not <link>ed) here -- confirmed by direct testing
    # (2026-07-26) that paged.js internally re-fetches every <link
    # rel="stylesheet"> via XHR to analyze its rules, and Chrome blocks that
    # XHR under file:// origin (CORS): "Access to XMLHttpRequest ... has
    # been blocked by CORS policy". The failure is silent to a casual look
    # -- an uncaught promise rejection, zero console error dialog, paged.js
    # simply never starts (.pagedjs_page count stayed at 0 for 115+ seconds
    # of real-time polling before this was traced). Inlining the same CSS
    # text directly into the <style> block sidesteps the extra fetch
    # entirely -- the woff2 files themselves still load fine via ordinary
    # @font-face resource loading, which file:// does allow.
    fonts_css = (output_dir / "vendor" / "gfonts-local.css").read_text(encoding="utf-8")
    # gfonts-local.css's url(fonts/font-NNN.woff2) paths are relative to
    # ITS OWN location (vendor/gfonts-local.css), i.e. really
    # vendor/fonts/font-NNN.woff2. Once inlined into a <style> block that
    # lives in the merged document's own <head>, relative url()s resolve
    # against the DOCUMENT's location instead -- so the "fonts/" prefix
    # must be rewritten to "vendor/fonts/" or every font 404s silently.
    fonts_css = fonts_css.replace("url(fonts/", "url(vendor/fonts/")
    full_style = (
        fonts_css
        + shared_chapter_style
        + qc.print_layer_css(style)
        + qc.front_back_css(style)
        + MERGE_ONLY_CSS
    )

    sections_html = []
    for slug in order:
        if slug == "front-matter":
            html_text = qc.load_chapter_html(FRONT_MATTER_FILE)
            sections_html.append(qc.extract_body_inner(html_text))
        elif slug == "back-matter":
            html_text = qc.load_chapter_html(BACK_MATTER_FILE)
            sections_html.append(qc.extract_body_inner(html_text))
        else:
            filename, label, study_ref = _SLUG_TO_CHAPTER[slug]
            html_text = qc.load_chapter_html(filename)
            sections_html.append(qc.page_shell(html_text, slug, label, study_ref))

    body = "\n\n".join(sections_html)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{qc.BOOK_TITLE}</title>
  <style>{full_style}</style>
</head>
<body>
{body}
<script src="vendor/paged.polyfill.js"></script>
</body>
</html>"""


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--output", default="QUESTION-BANK-BOOK.html",
        help="Output filename, written INTO first_run/output/ (must stay "
             "there so the vendor/... references keep working)."
    )
    ap.add_argument(
        "--force", action="store_true",
        help="Proceed past an orphaned-file warning instead of stopping."
    )
    args = ap.parse_args()

    output_dir = qc.OUTPUT_DIR
    style = qc.load_book_style()

    validate_order(BOOK_ORDER, output_dir, args.output, args.force)
    check_vendor_present(output_dir)

    merged = build_merged_html(output_dir, BOOK_ORDER, style)

    out_path = output_dir / args.output
    out_path.write_text(merged, encoding="utf-8")

    print(f"Merged {len(BOOK_ORDER)} sections -> {out_path}")
    print(f"  ({len(merged):,} characters)")
    print(
        "Next: open this file in Chrome, wait for paged.js to finish "
        "paginating (a 34-chapter book takes noticeably longer than any "
        "single section -- that's expected), then Ctrl+P -> Save as PDF "
        "with Background graphics enabled."
    )


if __name__ == "__main__":
    main()
