# Batch 1 (rows 1-50) topic tags. Row index = 1-based position in Questions_Accounts.csv data rows.
# Each entry: row_index -> dict(chapters=[(unitCode, standard, [(topic_no, topic_name, page)]), ...],
#                                scope='single'|'multiple', confidence='confident'|'inferred'|'flagged', notes=str)

TAGS = {
1: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])],
    scope="single", confidence="inferred",
    notes="Buy-back chapter has only 2 canonical topics (Intro/Section 70 provisions); bonus-share-from-CRR mechanics (Sec 69(2)) mapped to the Section-70-provisions topic as the closest match - coarse granularity, not a chapter-level doubt."),
2: dict(chapters=[("M2-C5-U4","AS 16", [("4.6","Specific borrowings","5.119"), ("4.7","General borrowings","5.119")])],
    scope="single", confidence="confident", notes=""),
3: dict(chapters=[("M2-C5-U4","AS 16", [("4.2","Definitions","5.114")])],
    scope="single", confidence="inferred", notes="Tests the 'qualifying asset' definition specifically (plant ready for use immediately = not qualifying); mapped to Definitions topic rather than Recognition Criteria."),
4: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])],
    scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1 (Sec 68(6) extinguishment timeline)."),
5: dict(chapters=[("M2-C9-U2","AS 14", [("2.6","Methods of Accounting for Amalgamations","9.26")])],
    scope="single", confidence="confident", notes=""),
6: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])],
    scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1 (premium funding source calc)."),
7: dict(chapters=[("M2-C10-U1","AS 21", [("1.1","Concept of Group, Holding Company and Subsidiary Company","10.2")])],
    scope="single", confidence="confident", notes=""),
8: dict(chapters=[("M3-C15-U0", None, [("5","Accounting for Dependent Branches","15.6")])],
    scope="single", confidence="confident", notes="Stock and Debtors Method is a sub-method under Dependent Branches."),
9: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])],
    scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1 (Debt Equity Ratio Test)."),
10: dict(chapters=[("M2-C5-U2","AS 10", [("2.10","Treatment of Subsequent Costs","5.38")])],
    scope="single", confidence="confident",
    notes="Case cluster 4778790b (with row 27, row 41-unrelated) spans AS2 (Year1 valuation, row 27) and AS10 (Year2 valuation, this row) under one shared narrative - flagging per the open cross-chapter case-scenario-cluster issue already logged in SKILL-question-bank-topic-tagging.md section 4. Each MCQ tagged individually here per current guidance."),
11: dict(chapters=[("M1-C4-U3","AS 17", [("3.4","Definition of the terms used in the Accounting Standard","4.45")])],
    scope="single", confidence="confident", notes=""),
12: dict(chapters=[("M2-C6-U2","AS 29", [("2.4","Recognition of provision","6.32"), ("2.11","Measurement: Best Estimate","6.38")])],
    scope="single", confidence="confident", notes=""),
13: dict(chapters=[("M2-C8-U2","AS 9", [("2.9","Effect of Uncertainties on Revenue Recognition","8.47")])],
    scope="single", confidence="confident", notes=""),
14: dict(chapters=[("M3-C11-U1", None, [("1.5","Final Accounts","11.1")])],
    scope="single", confidence="inferred", notes="Financial Statements of Companies (Sched III) chapter has only 6 broad topics; Schedule III line-item classification rules mapped to 'Final Accounts' as the closest of the 6."),
15: dict(chapters=[("M2-C9-U2","AS 14", [("2.7","Consideration","9.27")])],
    scope="single", confidence="confident", notes=""),
16: dict(chapters=[("M1-C2-U0", None, [("9","Elements of Financial Statements","2.13")])],
    scope="single", confidence="confident", notes=""),
17: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])],
    scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1 (Sec 68(1) permitted sources)."),
18: dict(chapters=[("M3-C11-U1", None, [("1.5","Final Accounts","11.1")])],
    scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 14 (current maturities classification)."),
19: dict(chapters=[("M3-C14-U0", None, [("3","Alteration of Share Capital","14.4")])],
    scope="single", confidence="confident", notes="Sub-division of shares is a form of alteration of share capital."),
20: dict(chapters=[("M1-C4-U1","AS 1", [("1.5","Disclosure of Changes in Accounting Policies","4.7")])],
    scope="single", confidence="confident",
    notes="CSV bucket says 'Presentation & Disclosures' (correct chapter group); question is squarely AS1 disclosure-of-policy-change, not AS2 inventory valuation, despite the inventory numbers used as the vehicle."),
21: dict(chapters=[("M1-C4-U3","AS 17", [("3.9","Identifying Reportable Segments (Quantitative Thresholds)","4.51")])],
    scope="single", confidence="confident", notes=""),
22: dict(chapters=[("M2-C8-U2","AS 9", [("2.6","Rendering of Services","8.41")])],
    scope="single", confidence="confident", notes=""),
23: dict(chapters=[("M2-C5-U2","AS 10", [("2.7","Initial Recognition","5.28")]), ("M2-C5-U4","AS 16", [("4.4","Borrowing Costs Eligible for Capitalisation","5.117")])],
    scope="multiple", confidence="inferred",
    notes="Primary: AS10 cost-capitalisation mechanics. Secondary: correctly excluding the deferred-credit interest requires the AS16 'not a qualifying asset' rule, which is independently tested knowledge, not just a passing mention."),
24: dict(chapters=[("M2-C9-U2","AS 14", [("2.4","Amalgamation in the Nature of Merger","9.25")])],
    scope="single", confidence="confident",
    notes="CSV chapter_id 'Other Accounting Standards' matches file 1's chapter_name for both AS12 (M2-C9-U1) and AS14 (M2-C9-U2) units - not a mismatch, just chapter-name-level coarseness needing unit resolution."),
25: dict(chapters=[("M1-C3-U0", None, [("2","Applicability of Accounting Standards","3.6")])],
    scope="single", confidence="inferred",
    notes="Applicability chapter has only 2 canonical topics in file 1 (no MSME-threshold sub-numbering); topic-index.json's finer ref '2.1' (Revised Criteria for classification of Non-company entities) supplements as the precise sub-topic - content is AS18/AS28 MSME exemption thresholds."),
26: dict(chapters=[("M2-C9-U2","AS 14", [("2.5","Amalgamation in the Nature of Purchase","9.26"), ("2.11","Treatment of Goodwill Arising on Amalgamation","9.3")])],
    scope="single", confidence="confident", notes=""),
27: dict(chapters=[("M2-C5-U1","AS 2", [("1.3","Measurement of Inventories","5.4")])],
    scope="single", confidence="confident",
    notes="Case cluster 4778790b (with row 10) spans AS2 (this row, Year1 valuation) and AS10 (row 10, Year2 valuation) - see note on row 10."),
28: dict(chapters=[("M1-C1-U0", None, [("1","Introduction","1.2")])],
    scope="single", confidence="inferred",
    notes="'Four aspects of AS' (recognition/measurement/presentation/disclosure, not taxation) is not its own numbered topic in file 1; mapped to the general Introduction topic."),
29: dict(chapters=[("M2-C9-U2","AS 14", [("2.7","Consideration","9.27")])],
    scope="single", confidence="confident", notes=""),
30: dict(chapters=[("M2-C10-U1","AS 21", [("1.11","Calculation of Goodwill/Capital Reserve (Cost of Control)","10.2")])],
    scope="single", confidence="confident", notes=""),
31: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])],
    scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1 (funding-source calc for buy-back, sale of investments)."),
32: dict(chapters=[("M1-C4-U1","AS 1", [("1.4","Selection of Accounting Policy","4.5")])],
    scope="single", confidence="inferred",
    notes="Question frames prudence as 'AS 1's principle'; AS1's Selection-of-Accounting-Policy topic covers prudence as one of 3 major considerations - though prudence is also a Framework (M1-C2-U0) qualitative characteristic; tagged to AS1 per the question's own framing."),
33: dict(chapters=[("M2-C8-U1","AS 7", [("1.6","Percentage Completion Method","8.12")])],
    scope="single", confidence="confident", notes="Foreseeable-loss provision calc under % completion method."),
34: dict(chapters=[("M1-C3-U0", None, [("2","Applicability of Accounting Standards","3.6")])],
    scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 25 (MSME-to-Large transition, prior-period restatement)."),
35: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])],
    scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1 (Resources Test)."),
36: dict(chapters=[("M1-C1-U0", None, [("1","Introduction","1.2")])],
    scope="single", confidence="confident", notes="Creative Accounting concept."),
37: dict(chapters=[("M2-C5-U6","AS 26", [("6.15","Development Phase","5.194"), ("6.16","Cost of an Internally Generated Intangible Asset","5.195")])],
    scope="single", confidence="confident",
    notes="Case cluster f1bb02d6 (with row 49) - both members AS26, consistent, no cross-chapter issue."),
38: dict(chapters=[("M2-C9-U2","AS 14", [("2.7","Consideration","9.27")])],
    scope="single", confidence="confident", notes="Liquidation expenses paid by purchasing co = part of purchase consideration."),
39: dict(chapters=[("M2-C9-U2","AS 14", [("2.9","Adjustments to reserves - Amalgamation in the Nature of Merger","9.28")])],
    scope="single", confidence="confident", notes=""),
40: dict(chapters=[("M2-C6-U1","AS 15", [("1.5","Post Employment Benefits: Defined Contribution vs Defined Benefits","6.12")])],
    scope="single", confidence="confident", notes=""),
41: dict(chapters=[("M2-C5-U2","AS 10", [("2.6","Measurement of PPE","5.27")])],
    scope="single", confidence="inferred",
    notes="Depreciation-commencement-timing is not a separately numbered topic among the 10 listed for this unit in file 1; mapped to Measurement of PPE as nearest match. Case cluster 15ccb29c (single-chapter, no cross-chapter issue in this batch)."),
42: dict(chapters=[("M2-C8-U1","AS 7", [("1.5","Contract Revenue and Costs","8.7")])],
    scope="single", confidence="confident", notes=""),
43: dict(chapters=[("M2-C5-U2","AS 10", [("2.7","Initial Recognition","5.28")])],
    scope="single", confidence="confident", notes="Case cluster 080adcad."),
44: dict(chapters=[("M1-C3-U0", None, [("1","Status of Accounting Standards","3.2")])],
    scope="single", confidence="confident", notes="Commercial/industrial/business activity applicability test."),
45: dict(chapters=[("M2-C5-U1","AS 2", [("1.10","Cost Formula","5.9")])],
    scope="single", confidence="confident", notes=""),
46: dict(chapters=[("M3-C11-U1", None, [("1.5","Final Accounts","11.1")])],
    scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 14 (Cash and Bank Balances presentation)."),
47: dict(chapters=[("M3-C11-U2", None, [("2.5","Calculation of Cash Flows from Investing Activities","11.82")])],
    scope="single", confidence="confident",
    notes="Cash Flow Statement content mapped to M3-C11-U2 (Companies-Act chapter), not the duplicate AS3 unit M1-C4-U2, per established pipeline convention (RTP_May2026.json precedent) - the two units cover identical AS3 content under different chapter groupings."),
48: dict(chapters=[("M2-C9-U1","AS 12", [("1.8","Presentation of Grants of the Nature of Promoters' Contribution","9.9")])],
    scope="single", confidence="confident", notes="Case cluster 5c708acd."),
49: dict(chapters=[("M2-C5-U6","AS 26", [("6.7","Recognition and Initial Measurement of an Intangible Asset","5.189"), ("6.8","Separate Acquisition","5.189")])],
    scope="single", confidence="confident",
    notes="Case cluster f1bb02d6 (with row 37) - both members AS26, consistent."),
50: dict(chapters=[("M1-C2-U0", None, [("6","Fundamental Accounting Assumptions","2.6")])],
    scope="single", confidence="confident", notes="Going Concern assumption."),
}
