# Batch 10 (rows 451-477)
TAGS = {
451: dict(chapters=[("M2-C6-U2","AS 29", [("2.19","Application of the Recognition and Measurement Rules","6.42")])], scope="single", confidence="confident", notes="Future operating losses not a liability."),
452: dict(chapters=[("M3-C13-U0", None, [("3","Types of Amalgamation","13.5")])],
    scope="single", confidence="confident",
    notes="Duplicate-chapter rule (row 106), reversed direction: Amalgamation-proper/Absorption/External-Reconstruction terminology matches M3-C13-U0's own 'Types of Amalgamation' topic more precisely than AS14's merger-vs-purchase-classification topic, so M3-C13-U0 wins here."),
453: dict(chapters=[("M1-C4-U4","AS 18", [("4.7","Disclosure requirements under AS-18","4.86")])],
    scope="single", confidence="confident",
    notes="Case cluster f5e7dfbc now spans AS3 (rows 91, 200, 280, 349) and AS18 (this row) - flagging per the open cross-chapter case-scenario-cluster issue."),
454: dict(chapters=[("M1-C1-U0", None, [("1","Introduction","1.2")])],
    scope="single", confidence="flagged",
    notes="This row appears to be placeholder/test data, not a real question - question text is literally 'Q1 for case study 1', options are 'Option A/B/C/D', and the explanation is literally the word 'Explanation'. Same issue as rows 224 and 291. Recommend Pranav review whether these three rows should be removed from the bank entirely."),
455: dict(chapters=[("M1-C2-U0", None, [("9","Elements of Financial Statements","2.13")])], scope="single", confidence="confident", notes="Doubtful-debt/depreciation provisions are asset diminution, not liabilities."),
456: dict(chapters=[("M3-C11-U2", None, [("2.2","Elements of Cash","11.75")])], scope="single", confidence="confident", notes="Cash equivalent 3-month maturity test; AS3 convention."),
457: dict(chapters=[("M3-C11-U2", None, [("2.5","Calculation of Cash Flows from Investing Activities","11.82")])],
    scope="single", confidence="confident", notes="Case cluster bc3fd25b (with rows 52, 176, 182) - this member is AS3, matching rows 176/182."),
458: dict(chapters=[("M2-C7-U3","AS 11", [("3.4","Reporting at each balance sheet date","7.32")])],
    scope="single", confidence="confident",
    notes="Case cluster 3b2dee7b now spans FOUR chapters: AS10 (row 57), AS28 (row 119), AS13 (row 170), and AS11 (this row) - flagging as another large cross-chapter cluster per the open case-scenario-cluster issue."),
459: dict(chapters=[("M3-C15-U0", None, [("6","Accounting for Independent Branches","15.41")])], scope="single", confidence="confident", notes="Head Office Account in independent-branch books."),
460: dict(chapters=[("M3-C11-U1", None, [("1.5","Final Accounts","11.1")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 14 (loan split principal/interest accrued but not due)."),
461: dict(chapters=[("M2-C5-U5","AS 19", [("5.3","Definitions","5.139")])],
    scope="single", confidence="inferred", notes="Same lessor-side-gap caveat as row 157 (output-based annual lease rent computation - lessor mechanics not separately topic-numbered)."),
462: dict(chapters=[("M2-C5-U2","AS 10", [("2.7","Initial Recognition","5.28")])], scope="single", confidence="confident", notes="Directly-attributable incidental income (demolition scrap) vs unrelated income (car park)."),
463: dict(chapters=[("M1-C4-U3","AS 17", [("3.9","Identifying Reportable Segments (Quantitative Thresholds)","4.51")])], scope="single", confidence="confident", notes="10% Profit/Loss Test, 5-segment calc."),
464: dict(chapters=[("M2-C5-U2","AS 10", [("2.7","Initial Recognition","5.28")])],
    scope="single", confidence="confident", notes="Case cluster 6fce0c47 (with rows 2, 132, 269) - this member is AS10, consistent."),
465: dict(chapters=[("M2-C5-U3","AS 13", [("3.9","Reclassification of Investments","5.86")])], scope="single", confidence="confident", notes="Same theme as row 438."),
466: dict(chapters=[("M3-C14-U0", None, [("5","Reduction of Share Capital","14.9")])], scope="single", confidence="confident", notes="Preference share reduction + dividend arrears waiver calc."),
467: dict(chapters=[("M2-C10-U1","AS 21", [("1.11","Calculation of Goodwill/Capital Reserve (Cost of Control)","10.2"), ("1.12","Minority Interests","10.24")])],
    scope="single", confidence="confident", notes=""),
468: dict(chapters=[("M1-C3-U0", None, [("1","Status of Accounting Standards","3.2")])], scope="single", confidence="confident", notes="Tax-exempt revenue still recognised in FS - AS/tax independence."),
469: dict(chapters=[("M2-C5-U4","AS 16", [("4.6","Specific borrowings","5.119"), ("4.7","General borrowings","5.119")])],
    scope="single", confidence="confident",
    notes="Case cluster d27f9a5b (with rows 138, 367, 448) confirmed as spanning AS13+AS2+AS10+AS16 - this member is pure AS16, consistent with row 448's AS16 tag."),
470: dict(chapters=[("M2-C9-U1","AS 12", [("1.5","Non-monetary Government Grants","9.4")])],
    scope="single", confidence="confident", notes="Case cluster 30b85fe4 (with rows 162, 351, 370) - all AS12, consistent."),
471: dict(chapters=[("M3-C14-U0", None, [("5","Reduction of Share Capital","14.9"), ("8","Entries in case of internal reconstruction","14.12")])],
    scope="single", confidence="confident", notes="Capital Reduction Account mechanics (theory)."),
472: dict(chapters=[("M2-C7-U1","AS 4", [("1","Introduction","7.1")])],
    scope="single", confidence="inferred",
    notes="Substance-over-form sale-recognition question explicitly framed under AS4 in the explanation, though it is not really a classic adjusting/non-adjusting post-balance-sheet-date event - no clearly matching sub-topic among the 6 listed, mapped to Introduction as the least-wrong fit. Chapter assignment follows the explanation's own AS4 citation; topic-level confidence is lower."),
473: dict(chapters=[("M2-C6-U2","AS 29", [("2.17","Changes in Provisions","6.41")])], scope="single", confidence="confident", notes="Provision review, over-provision reversal credit."),
474: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])],
    scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1. Case cluster 623873e2 (with rows 122, 293, 444) - consistent."),
475: dict(chapters=[("M1-C2-U0", None, [("3","Status and Scope of the Framework","2.3")])], scope="single", confidence="confident", notes="Framework applies to general-purpose FS."),
476: dict(chapters=[("M3-C14-U0", None, [("1","Meaning of reconstruction","14.2")])], scope="single", confidence="confident", notes="Same theme as row 184 (reconstruction without liquidation)."),
477: dict(chapters=[("M1-C1-U0", None, [("12","History of IFRS Converged Indian Accounting Standards (Ind AS)","1.22")])], scope="single", confidence="confident", notes="MCA notification Feb 2015, voluntary Ind AS from 1 Apr 2015."),
}
