# Batch 5 (rows 201-250)
TAGS = {
201: dict(chapters=[("M1-C2-U0", None, [("11","Capital Maintenance","2.25")])], scope="single", confidence="confident", notes="Physical Capital Maintenance at Current Costs."),
202: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1. Case cluster 3b7a7ad5 (with rows 9, 211) - all buy-back, consistent."),
203: dict(chapters=[("M2-C9-U2","AS 14", [("2.3","Types of Amalgamations","9.24")])], scope="single", confidence="confident", notes="90% merger-qualification test."),
204: dict(chapters=[("M2-C6-U2","AS 29", [("2.17","Changes in Provisions","6.41")])], scope="single", confidence="confident", notes="Warranty provision movement, P&L charge."),
205: dict(chapters=[("M2-C9-U1","AS 12", [("1.9","Refund of Government Grants","9.11")])], scope="single", confidence="confident", notes=""),
206: dict(chapters=[("M1-C1-U0", None, [("3","How Many Accounting Standards?","1.9")])], scope="single", confidence="confident", notes="Earliest applicability date."),
207: dict(chapters=[("M1-C3-U0", None, [("2","Applicability of Accounting Standards","3.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 25 (AS21/23/25 CFS non-mandatory for non-company entities)."),
208: dict(chapters=[("M3-C11-U2", None, [("2.3","Classification of Cash Flow Activities","11.76")])], scope="single", confidence="confident", notes="Employee/subsidiary loans + dividends paid classification; AS3 convention."),
209: dict(chapters=[("M2-C7-U2","AS 5", [("2.4","Changes in Accounting Estimates","7.18")])], scope="single", confidence="confident", notes="Depreciation-method change = estimate change, not extraordinary item."),
210: dict(chapters=[("M2-C6-U2","AS 29", [("2.4","Recognition of provision","6.32")])],
    scope="single", confidence="confident",
    notes="Case cluster dff21db8 spans AS9 (row 22, installation-fee revenue recognition) and AS29 (this row, warranty provision) - flagging per the open cross-chapter case-scenario-cluster issue."),
211: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1. Case cluster 3b7a7ad5 (with rows 9, 202) - consistent."),
212: dict(chapters=[("M2-C5-U6","AS 26", [("6.18","Subsequent Expenditure","5.198")])],
    scope="single", confidence="confident", notes="Case cluster f1bb02d6 (with rows 37, 49, 125) - all AS26, consistent."),
213: dict(chapters=[("M2-C9-U2","AS 14", [("2.7","Consideration","9.27")])], scope="single", confidence="confident", notes="Intrinsic Value / Share Exchange method, entries at par value. Duplicate-chapter rule (row 106) - AS14 topic matches directly."),
214: dict(chapters=[("M1-C2-U0", None, [("9","Elements of Financial Statements","2.13")])], scope="single", confidence="confident", notes="Employee talent not an asset - insufficient control."),
215: dict(chapters=[("M1-C3-U0", None, [("1","Status of Accounting Standards","3.2")])], scope="single", confidence="confident", notes="AS cannot override laws/local regulations."),
216: dict(chapters=[("M1-C1-U0", None, [("5","Need for Convergence towards Global Standards","1.13")])], scope="single", confidence="confident", notes=""),
217: dict(chapters=[("M1-C2-U0", None, [("11","Capital Maintenance","2.25")])], scope="single", confidence="confident", notes="Financial Capital Maintenance at Historical Cost."),
218: dict(chapters=[("M2-C10-U2","AS 23", [("2.3","Definitions of the terms used in the Accounting Standard","10.111")])],
    scope="single", confidence="confident",
    notes="Case cluster fe39296d spans AS13 (row 172, investment carrying amount) and AS23 (this row, associate-relationship identification) - flagging per the open cross-chapter case-scenario-cluster issue."),
219: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1. Case cluster 00403636 (with rows 31, 148) - consistent."),
220: dict(chapters=[("M1-C2-U0", None, [("6","Fundamental Accounting Assumptions","2.6")])], scope="single", confidence="confident", notes="Consistency assumption, valid reasons to change policy."),
221: dict(chapters=[("M2-C5-U2","AS 10", [("2.7","Initial Recognition","5.28")])], scope="single", confidence="confident", notes="Refundable GST input credit excluded from cost."),
222: dict(chapters=[("M2-C6-U1","AS 15", [("1.10","Actuarial Gains and Losses","6.16")])], scope="single", confidence="confident", notes="Actual return on plan assets calc."),
223: dict(chapters=[("M2-C10-U1","AS 21", [("1.17","Uniform Accounting Policies","10.78")])], scope="single", confidence="confident", notes=""),
224: dict(chapters=[("M1-C1-U0", None, [("1","Introduction","1.2")])],
    scope="single", confidence="flagged",
    notes="This row appears to be placeholder/test data, not a real question - question text is literally 'Q1 for case study 2', options are 'Option A/B/C/D', and the explanation is literally the word 'Explanation'. Recommend Pranav review whether this row should be removed from the bank entirely rather than tagged as real content."),
225: dict(chapters=[("M2-C7-U3","AS 11", [("3.4","Reporting at each balance sheet date","7.32")])], scope="single", confidence="confident", notes="Case cluster 0ebfb1c7; loan restated at closing rate."),
226: dict(chapters=[("M3-C11-U1", None, [("1.5","Final Accounts","11.1")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 14 (Securities Premium under Reserves and Surplus)."),
227: dict(chapters=[("M2-C9-U1","AS 12", [("1.6","Presentation of Grants Related to Specific Fixed Assets","9.4")])],
    scope="single", confidence="confident",
    notes="Case cluster 080adcad spans AS10 (row 43, revenue expenditure) and AS12 (this row, grant-funded asset ownership) - flagging per the open cross-chapter case-scenario-cluster issue."),
228: dict(chapters=[("M3-C11-U1", None, [("1.5","Final Accounts","11.1")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 14 (Share Option Outstanding under Reserves and Surplus)."),
229: dict(chapters=[("M3-C11-U1", None, [("1.5","Final Accounts","11.1")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 14 (Trade Receivables ageing sub-classification)."),
230: dict(chapters=[("M1-C3-U0", None, [("1","Status of Accounting Standards","3.2")])],
    scope="single", confidence="inferred", notes="Core lesson is AS/tax-law independence (Applicability chapter theme); uses an AS19 finance-lease depreciation example as the vehicle."),
231: dict(chapters=[("M3-C11-U1", None, [("1.6","Distributable Profit","11.18")])], scope="single", confidence="confident", notes="Sec 124 unpaid dividend transfer timeline."),
232: dict(chapters=[("M2-C7-U4","AS 22", [("4.4","Recognition","7.56")])],
    scope="single", confidence="confident",
    notes="Case cluster 5c708acd now spans THREE chapters: AS12 (row 48), AS26 (row 112), and AS22 (this row, deferred tax on machinery timing difference) - a 3-way cross-chapter cluster, flagging per the open case-scenario-cluster issue."),
233: dict(chapters=[("M1-C3-U0", None, [("1","Status of Accounting Standards","3.2")])], scope="single", confidence="confident", notes="Materiality definition - correctly under Applicability chapter per topic-index.json (see correction note on row 185)."),
234: dict(chapters=[("M1-C3-U0", None, [("2","Applicability of Accounting Standards","3.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 25 (MSME partial-exemption disclosure rule)."),
235: dict(chapters=[("M3-C11-U1", None, [("1.5","Final Accounts","11.1")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 14 (Unpaid Dividend under Other Current Liabilities)."),
236: dict(chapters=[("M1-C3-U0", None, [("1","Status of Accounting Standards","3.2")])], scope="single", confidence="confident", notes="Sector-specific law exemption (Electricity Act) doesn't affect true-and-fair view."),
237: dict(chapters=[("M1-C2-U0", None, [("9","Elements of Financial Statements","2.13")])], scope="single", confidence="confident", notes="Dealer's unsold inventory = asset."),
238: dict(chapters=[("M1-C2-U0", None, [("7","Qualitative Characteristics of Financial Statements","2.11")])], scope="single", confidence="confident", notes="Four qualitative characteristics."),
239: dict(chapters=[("M1-C2-U0", None, [("10","Measurement of Elements of Financial Statements","2.21")])], scope="single", confidence="confident", notes="Current Cost basis, liabilities at undiscounted amount."),
240: dict(chapters=[("M3-C11-U2", None, [("2.5","Calculation of Cash Flows from Investing Activities","11.82")])], scope="single", confidence="confident", notes="Case cluster 7c0cf99a (with rows 79, 194) - all AS3, consistent."),
241: dict(chapters=[("M3-C15-U0", None, [("1","Introduction","15.2")])], scope="single", confidence="confident", notes="Inland/foreign, dependent/independent branch classification."),
242: dict(chapters=[("M3-C14-U0", None, [("5","Reduction of Share Capital","14.9")])], scope="single", confidence="confident", notes="Both nominal and paid-up value reduced."),
243: dict(chapters=[("M2-C9-U2","AS 14", [("2.5","Amalgamation in the Nature of Purchase","9.26"), ("2.11","Treatment of Goodwill Arising on Amalgamation","9.3")])],
    scope="single", confidence="confident", notes="Duplicate-chapter rule (row 106) - AS14 topic matches directly."),
244: dict(chapters=[("M2-C7-U2","AS 5", [("2.5","Changes in Accounting Policies","7.2")])],
    scope="single", confidence="confident",
    notes="Case cluster c2aa648f now spans THREE chapters: AS21+AS23 (row 61), AS5 (this row, employee-benefit-scheme policy-change test), and AS9 (row 249, revenue recognition) - a 3-way cross-chapter cluster on one large multi-part company case study, flagging per the open case-scenario-cluster issue."),
245: dict(chapters=[("M1-C3-U0", None, [("2","Applicability of Accounting Standards","3.6")])], scope="single", confidence="confident", notes="2024 revised 2-category (MSME/Large) scheme."),
246: dict(chapters=[("M2-C5-U2","AS 10", [("2.6","Measurement of PPE","5.27")])], scope="single", confidence="inferred", notes="Same Revaluation Model gap as rows 117/163."),
247: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1. Case cluster 9baffa7e (with row 180) - consistent (Sec 68(2) 25% Resources Test theory)."),
248: dict(chapters=[("M1-C2-U0", None, [("4","Components of Financial Statements","2.4")])], scope="single", confidence="confident", notes="Balance Sheet shows liquidity/solvency."),
249: dict(chapters=[("M2-C8-U2","AS 9", [("2.3","Agency Relationship","8.37")])],
    scope="single", confidence="confident", notes="Case cluster c2aa648f (see row 244's note) - gross vs net revenue recognition, principal vs agent."),
250: dict(chapters=[("M1-C4-U1","AS 1", [("1.2","Fundamental Accounting Assumptions","4.3")])], scope="single", confidence="confident", notes="Accrual basis mandatory per Sec 128(1)."),
}
