# Batch 3 (rows 101-150)
TAGS = {
101: dict(chapters=[("M3-C15-U0", None, [("5","Accounting for Dependent Branches","15.6")])], scope="single", confidence="confident", notes=""),
102: dict(chapters=[("M3-C11-U1", None, [("1.6","Distributable Profit","11.18")])], scope="single", confidence="confident", notes=""),
103: dict(chapters=[("M3-C11-U1", None, [("1.6","Distributable Profit","11.18")])], scope="single", confidence="confident", notes=""),
104: dict(chapters=[("M1-C2-U0", None, [("5","Objectives and Users of Financial Statements","2.5")])], scope="single", confidence="confident", notes=""),
105: dict(chapters=[("M2-C7-U1","AS 4", [("1.4","Adjusting Events","7.4")])], scope="single", confidence="confident", notes=""),
106: dict(chapters=[("M2-C9-U2","AS 14", [("2.9","Adjustments to reserves - Amalgamation in the Nature of Merger","9.28")])],
    scope="single", confidence="confident",
    notes="DUPLICATE-CHAPTER RULE APPLIED (flagging for awareness, same pattern as the AS3/Cash-Flow M1-C4-U2 vs M3-C11-U2 duplicate): Amalgamation content exists in two canonical chapters - M2-C9-U2 (AS14, conceptual/definitional, 14 topics) and M3-C13-U0 (Amalgamation of Companies, Companies-Act procedural, 7 topics, overlapping subject matter). Adopted rule for this tagging pass: default to M2-C9-U2 whenever a matching AS14 topic exists (as here - reserve adjustment under pooling is topic 2.9); fall back to M3-C13-U0 only for the pure bookkeeping-mechanics topics AS14's list doesn't cover (vendor-book-closing entries, purchaser's entries - see row 86). This is a new open issue worth Pranav's attention, analogous to the existing Cash-Flow duplicate."),
107: dict(chapters=[("M2-C8-U2","AS 9", [("2.5","Timing of Recognition of Revenue from Sale of Goods","8.39")])],
    scope="single", confidence="confident", notes="Case cluster dd4cd032 (bill-and-hold sale)."),
108: dict(chapters=[("M3-C11-U2", None, [("2.6","Calculation of Cash Flows from Financing Activities","11.82")])],
    scope="single", confidence="confident", notes="Dividend paid classification; AS3->M3-C11-U2 convention."),
109: dict(chapters=[("M2-C7-U4","AS 22", [("4.4","Recognition","7.56")])], scope="single", confidence="confident", notes="GST Sec 43B deferred tax timing difference."),
110: dict(chapters=[("M2-C8-U2","AS 9", [("2.9","Effect of Uncertainties on Revenue Recognition","8.47")])], scope="single", confidence="confident", notes=""),
111: dict(chapters=[("M1-C1-U0", None, [("14","Roadmap for Implementation of Indian Accounting Standards (Ind AS): A Snapshot","1.26")])],
    scope="single", confidence="confident", notes="NBFC voluntary-adoption restriction."),
112: dict(chapters=[("M2-C5-U6","AS 26", [("6.8","Separate Acquisition","5.189")])],
    scope="single", confidence="confident",
    notes="Case cluster 5c708acd spans AS12 (row 48, government-grant subsidy question) and AS26 (this row, trademark capitalisation) under one shared narrative - flagging per the open cross-chapter case-scenario-cluster issue (see row 10's note and SKILL-question-bank-topic-tagging.md section 4)."),
113: dict(chapters=[("M3-C15-U0", None, [("5","Accounting for Dependent Branches","15.6")])], scope="single", confidence="confident", notes="Closing stock at invoice price."),
114: dict(chapters=[("M3-C15-U0", None, [("7","Adjustment and Reconciliation of Branch& Head Office Accounts","15.44")])],
    scope="single", confidence="inferred", notes="Inter-branch transactions routed through HO."),
115: dict(chapters=[("M2-C8-U2","AS 9", [("2.4","Sale of Goods","8.39")])], scope="single", confidence="confident", notes="Risk/reward transfer date vs registration date."),
116: dict(chapters=[("M1-C3-U0", None, [("2","Applicability of Accounting Standards","3.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 25 (MSME classification table)."),
117: dict(chapters=[("M2-C5-U2","AS 10", [("2.6","Measurement of PPE","5.27")])],
    scope="single", confidence="inferred", notes="Revaluation Model (downward-then-upward revaluation P&L/Reserve split) not separately topic-numbered in file 1's 10-topic list for this unit; mapped to Measurement of PPE."),
118: dict(chapters=[("M1-C4-U1","AS 1", [("1.5","Disclosure of Changes in Accounting Policies","4.7")])], scope="single", confidence="confident", notes=""),
119: dict(chapters=[("M2-C5-U7","AS 28", [("7.4","Measurement of Recoverable Amount","5.219"), ("7.7","Recognition and Measurement of an Impairment Loss","5.224")])],
    scope="single", confidence="confident",
    notes="Case cluster 3b2dee7b spans AS10 (row 57, carrying value/dismantling-cost question) and AS28 (this row, impairment loss) under one shared narrative - flagging per the open cross-chapter case-scenario-cluster issue."),
120: dict(chapters=[("M2-C10-U1","AS 21", [("1.12","Minority Interests","10.24")])], scope="single", confidence="confident", notes=""),
121: dict(chapters=[("M1-C1-U0", None, [("1","Introduction","1.2")])], scope="single", confidence="confident", notes="GAAP definition."),
122: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])],
    scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1. Case cluster 623873e2."),
123: dict(chapters=[("M3-C14-U0", None, [("8","Entries in case of internal reconstruction","14.12")])], scope="single", confidence="confident", notes="Debenture holders accept plant/machinery in settlement."),
124: dict(chapters=[("M2-C10-U1","AS 21", [("1.11","Calculation of Goodwill/Capital Reserve (Cost of Control)","10.2")])],
    scope="single", confidence="confident", notes="Bonus shares issued post-acquisition affecting cost-of-control calc."),
125: dict(chapters=[("M2-C5-U6","AS 26", [("6.7","Recognition and Initial Measurement of an Intangible Asset","5.189")])],
    scope="single", confidence="confident", notes="Case cluster f1bb02d6 (with rows 37, 49) - all three AS26, consistent."),
126: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1."),
127: dict(chapters=[("M2-C8-U2","AS 9", [("2.4","Sale of Goods","8.39"), ("2.5","Timing of Recognition of Revenue from Sale of Goods","8.39")])],
    scope="single", confidence="confident", notes=""),
128: dict(chapters=[("M1-C2-U0", None, [("9","Elements of Financial Statements","2.13")])], scope="single", confidence="confident", notes=""),
129: dict(chapters=[("M3-C14-U0", None, [("8","Entries in case of internal reconstruction","14.12")])], scope="single", confidence="confident", notes="Creditor forgoes claim, part-settled in shares."),
130: dict(chapters=[("M1-C3-U0", None, [("2","Applicability of Accounting Standards","3.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 25 (AS3/17/20/24 exemptions)."),
131: dict(chapters=[("M1-C4-U1","AS 1", [("1.2","Fundamental Accounting Assumptions","4.3")])], scope="single", confidence="confident", notes=""),
132: dict(chapters=[("M2-C5-U2","AS 10", [("2.6","Measurement of PPE","5.27"), ("2.7","Initial Recognition","5.28")])],
    scope="single", confidence="confident",
    notes="Case cluster 6fce0c47 spans AS16 (row 2, net borrowing cost) and AS10 (this row, factory building cost + component depreciation) - a naturally connected AS10+AS16 construction-of-qualifying-asset fact pattern split across two case-cluster MCQs. Flagging per the open cross-chapter case-scenario-cluster issue, same as rows 10/112/119."),
133: dict(chapters=[("M2-C9-U1","AS 12", [("1.6","Presentation of Grants Related to Specific Fixed Assets","9.4")])],
    scope="single", confidence="confident", notes="Method II deferred income for an asset-related grant."),
134: dict(chapters=[("M2-C10-U1","AS 21", [("1.14","Consolidation Adjustments","10.27")])], scope="single", confidence="confident", notes="Upstream unrealized-profit elimination."),
135: dict(chapters=[("M2-C9-U2","AS 14", [("2.7","Consideration","9.27")])],
    scope="single", confidence="confident", notes="Duplicate-chapter rule (see row 106) - matches an AS14 topic directly, so M2-C9-U2 wins over M3-C13-U0."),
136: dict(chapters=[("M1-C2-U0", None, [("7","Qualitative Characteristics of Financial Statements","2.11")])], scope="single", confidence="confident", notes="Timeliness constraint."),
137: dict(chapters=[("M2-C7-U3","AS 11", [("3.4","Reporting at each balance sheet date","7.32"), ("3.5","Recognition of Exchange Differences","7.32")])],
    scope="single", confidence="confident", notes=""),
138: dict(chapters=[("M2-C5-U3","AS 13", [("3.5","Cost of Investments","5.8"), ("3.6","Carrying Amount of Investments","5.82")])],
    scope="single", confidence="confident", notes="Case cluster d27f9a5b; dividend from pre-acquisition profits deducted from cost."),
139: dict(chapters=[("M2-C8-U1","AS 7", [("1.9","Stage of Completion","8.18")])], scope="single", confidence="confident", notes=""),
140: dict(chapters=[("M2-C8-U2","AS 9", [("2.4","Sale of Goods","8.39")])], scope="single", confidence="confident", notes="Sale-and-repurchase = financing arrangement, not sale."),
141: dict(chapters=[("M1-C1-U0", None, [("4","Status of Accounting Standards","1.13")])], scope="single", confidence="confident", notes="ICAI not a legislative body."),
142: dict(chapters=[("M2-C8-U1","AS 7", [("1.6","Percentage Completion Method","8.12")])], scope="single", confidence="confident", notes=""),
143: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1 (fully-paid-shares-only condition)."),
144: dict(chapters=[("M2-C10-U1","AS 21", [("1.14","Consolidation Adjustments","10.27")])], scope="single", confidence="confident", notes="Downstream unrealized-profit elimination."),
145: dict(chapters=[("M2-C9-U1","AS 12", [("1.6","Presentation of Grants Related to Specific Fixed Assets","9.4")])], scope="single", confidence="confident", notes="Method I depreciation calc."),
146: dict(chapters=[("M1-C2-U0", None, [("9","Elements of Financial Statements","2.13")])], scope="single", confidence="confident", notes="Asset definition, 'controlled' not 'owned'."),
147: dict(chapters=[("M2-C10-U1","AS 21", [("1.11","Calculation of Goodwill/Capital Reserve (Cost of Control)","10.2")]),
                    ("M2-C5-U3","AS 13", [("3.5","Cost of Investments","5.8")])],
    scope="multiple", confidence="inferred",
    notes="Primary: AS21 goodwill/cost-of-control computation. Secondary: the AS13 rule (pre-acquisition dividend deducted from cost) is independently tested knowledge needed to solve it, genuinely connected within one fact pattern."),
148: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])],
    scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1. Case cluster 00403636 (with row 31) - both buy-back, consistent."),
149: dict(chapters=[("M2-C10-U1","AS 21", [("1.13","Profit or Loss of Subsidiary Company","10.26")])], scope="single", confidence="confident", notes="Mid-year acquisition pre/post-acquisition profit time-apportionment."),
150: dict(chapters=[("M1-C2-U0", None, [("10","Measurement of Elements of Financial Statements","2.21")])], scope="single", confidence="confident", notes="Four measurement bases."),
}
