# Batch 9 (rows 401-450)
TAGS = {
401: dict(chapters=[("M3-C15-U0", None, [("7","Adjustment and Reconciliation of Branch& Head Office Accounts","15.44")])], scope="single", confidence="confident", notes="Goods in transit."),
402: dict(chapters=[("M1-C1-U0", None, [("11","What are Indian Accounting Standards (Ind AS)?","1.21")])], scope="single", confidence="confident", notes="IFRS-to-Ind-AS numbering (+100)."),
403: dict(chapters=[("M1-C1-U0", None, [("6","International Accounting Standard Board","1.15")])], scope="single", confidence="confident", notes="IASC established 1973."),
404: dict(chapters=[("M2-C6-U2","AS 29", [("2.3","Definitions","6.31")])], scope="single", confidence="confident", notes="Provision definition."),
405: dict(chapters=[("M2-C10-U1","AS 21", [("1.11","Calculation of Goodwill/Capital Reserve (Cost of Control)","10.2")])], scope="single", confidence="confident", notes="Pre-acquisition profit treatment."),
406: dict(chapters=[("M2-C7-U3","AS 11", [("3.5","Recognition of Exchange Differences","7.32")])],
    scope="single", confidence="confident", notes="Case cluster 0ebfb1c7 (with rows 225, 310, 316, 378) - all AS11, consistent."),
407: dict(chapters=[("M2-C7-U1","AS 4", [("1.4","Adjusting Events","7.4")])],
    scope="single", confidence="confident",
    notes="Case cluster dd4cd032 now spans THREE chapters: AS9 (row 107), AS29 (row 197), and AS4 (this row) - flagging per the open cross-chapter case-scenario-cluster issue."),
408: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1 (premium + CRR journal entries)."),
409: dict(chapters=[("M1-C2-U0", None, [("9","Elements of Financial Statements","2.13")])], scope="single", confidence="confident", notes="Expenses associated with asset reduction/liability increase."),
410: dict(chapters=[("M3-C11-U1", None, [("1.2","Maintenance of Books of Account","11.6")])],
    scope="single", confidence="confident", notes="CSV chapter_id 'Framework' mislabels this Sec 128(1) Companies Act content - same provision as row 89, tagged per actual content."),
411: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])],
    scope="single", confidence="flagged",
    notes="Content is ESOP-exercise journal entries, not buy-back mechanics per se - doesn't clearly match either of file 1's 2 topics for this chapter. May indicate the real syllabus chapter covers broader 'other capital reorganisation' content (ESOP schemes) that file 1's 2-topic summary doesn't capture; kept in the CSV's own Buy-back bucket for lack of a better match, flagging the gap."),
412: dict(chapters=[("M2-C6-U2","AS 29", [("2.4","Recognition of provision","6.32"), ("2.9","Contingent Liabilities","6.35")])], scope="single", confidence="confident", notes="Split legal-costs/settlement treatment."),
413: dict(chapters=[("M2-C5-U3","AS 13", [("3.5","Cost of Investments","5.8")])], scope="single", confidence="confident", notes="Pre-acquisition interest on debenture investment."),
414: dict(chapters=[("M2-C5-U2","AS 10", [("2.6","Measurement of PPE","5.27")])], scope="single", confidence="inferred", notes="Same depreciation-mechanics gap as rows 41/94/163/319/329."),
415: dict(chapters=[("M2-C5-U2","AS 10", [("2.10","Treatment of Subsequent Costs","5.38")])], scope="single", confidence="confident", notes="Derecognition of replaced part."),
416: dict(chapters=[("M2-C6-U2","AS 29", [("2.10","Contingent Assets","6.37")])], scope="single", confidence="confident", notes=""),
417: dict(chapters=[("M2-C5-U2","AS 10", [("2.7","Initial Recognition","5.28")])],
    scope="single", confidence="confident",
    notes="Case cluster 15ccb29c spans AS10 (rows 41, 312, this row) and AS16 (row 446, borrowing cost) - a naturally connected AS10+AS16 construction fact pattern split across case-cluster MCQs, same pattern as clusters 6fce0c47/080adcad. Flagging per the open cross-chapter case-scenario-cluster issue."),
418: dict(chapters=[("M2-C9-U1","AS 12", [("1.8","Presentation of Grants of the Nature of Promoters' Contribution","9.9")])],
    scope="single", confidence="confident", notes="Case cluster 080adcad (with rows 43, 227, 369) - this member is AS12, matching row 227's chapter."),
419: dict(chapters=[("M2-C7-U3","AS 11", [("3.8","Translation of Non-Integral Foreign Operations","7.36")])], scope="single", confidence="confident", notes=""),
420: dict(chapters=[("M2-C8-U1","AS 7", [("1.6","Percentage Completion Method","8.12")])], scope="single", confidence="confident", notes="Foreseeable loss + provision calc."),
421: dict(chapters=[("M2-C10-U2","AS 23", [("2.4","Associates Accounted for using the Equity method","10.114"), ("2.6","Application of the Equity Method","10.116")])],
    scope="single", confidence="confident", notes="Case cluster fe39296d (with rows 172, 218, 433) - this member is AS23, matching row 218/433."),
422: dict(chapters=[("M2-C8-U2","AS 9", [("2.4","Sale of Goods","8.39"), ("2.6","Rendering of Services","8.41")])],
    scope="single", confidence="confident", notes="Case cluster dff21db8 (with rows 22, 210, 390) - this member is AS9, matching row 22/390."),
423: dict(chapters=[("M2-C10-U1","AS 21", [("1.14","Consolidation Adjustments","10.27")])], scope="single", confidence="confident", notes="Full intra-group elimination."),
424: dict(chapters=[("M3-C11-U2", None, [("2.3","Classification of Cash Flow Activities","11.76")])], scope="single", confidence="confident", notes="Financial enterprise - both Operating; AS3 convention."),
425: dict(chapters=[("M2-C5-U2","AS 10", [("2.3","Definition of Property, Plant and Equipment (PPE)","5.23")])], scope="single", confidence="confident", notes=""),
426: dict(chapters=[("M2-C5-U1","AS 2", [("1.3","Measurement of Inventories","5.4")])], scope="single", confidence="confident", notes="Partly finished unit NRV with brokerage deduction."),
427: dict(chapters=[("M3-C15-U0", None, [("5","Accounting for Dependent Branches","15.6")])], scope="single", confidence="confident", notes="Goods lost/stolen, selling-price invoicing."),
428: dict(chapters=[("M2-C9-U1","AS 12", [("1.4","Recognition of Government Grants","9.3")])], scope="single", confidence="confident", notes=""),
429: dict(chapters=[("M3-C11-U1", None, [("1.5","Final Accounts","11.1")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 14 (Fixed Assets Held for Sale -> Current Asset, same theme as row 296)."),
430: dict(chapters=[("M2-C5-U2","AS 10", [("2.6","Measurement of PPE","5.27")]),
                    ("M2-C7-U2","AS 5", [("2.4","Changes in Accounting Estimates","7.18")])],
    scope="multiple", confidence="inferred",
    notes="Primary: AS10 depreciation mechanics (revised useful-life calc). Secondary: AS5's prospective-application-for-estimate-changes principle, explicitly invoked in the explanation."),
431: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])],
    scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1. Case cluster 2b23f733 (with rows 192, 345) - consistent."),
432: dict(chapters=[("M1-C1-U0", None, [("2","Standards Setting Process","1.6")])],
    scope="single", confidence="confident",
    notes="CSV chapter_id 'Applicability of Accounting Standards' mislabels this content - 'who develops/issues AS' (ASB/ICAI Council) matches Introduction chapter's Standards Setting Process topic directly, tagged per actual content."),
433: dict(chapters=[("M2-C10-U2","AS 23", [("2.5","Circumstances under which Equity Method is followed","10.115")])],
    scope="single", confidence="confident", notes="Case cluster fe39296d (with rows 172, 218, 421) - this member is AS23, matching row 218/421."),
434: dict(chapters=[("M2-C9-U2","AS 14", [("2.2","Definition of the Terms used in the Standard","9.24")])], scope="single", confidence="confident", notes="Acquisition vs amalgamation distinction."),
435: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1 (25% Shares Outstanding Test theory)."),
436: dict(chapters=[("M1-C3-U0", None, [("2","Applicability of Accounting Standards","3.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 25 (MSME AS28 value-in-use relaxation)."),
437: dict(chapters=[("M2-C5-U3","AS 13", [("3.8","Disposal of Investments","5.86")])], scope="single", confidence="confident", notes="Net gain/loss on long-term investment disposal to P&L."),
438: dict(chapters=[("M2-C5-U3","AS 13", [("3.9","Reclassification of Investments","5.86")])], scope="single", confidence="confident", notes=""),
439: dict(chapters=[("M3-C11-U2", None, [("2.2","Elements of Cash","11.75")])], scope="single", confidence="confident", notes="Cash and Cash Equivalents calc; AS3 convention."),
440: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])],
    scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1. Case cluster 00403636 (with rows 31, 148, 219) - consistent."),
441: dict(chapters=[("M2-C10-U1","AS 21", [("1.12","Minority Interests","10.24")])], scope="single", confidence="confident", notes="Minority losses exceeding minority equity."),
442: dict(chapters=[("M1-C3-U0", None, [("1","Status of Accounting Standards","3.2")])], scope="single", confidence="confident", notes="ICDS numbering pairs."),
443: dict(chapters=[("M2-C5-U5","AS 19", [("5.2","Applicability of AS 19 [Scope]","5.138")])], scope="single", confidence="confident", notes=""),
444: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])],
    scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1. Case cluster 623873e2 (with rows 122, 293) - consistent."),
445: dict(chapters=[("M1-C3-U0", None, [("2","Applicability of Accounting Standards","3.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 25 (MSME AS22 deferred-tax transitional treatment)."),
446: dict(chapters=[("M2-C5-U4","AS 16", [("4.10","Suspension of Capitalisation","5.123")])],
    scope="single", confidence="confident", notes="Case cluster 15ccb29c (with rows 41, 312, 417) - see row 417's note; this member is AS16."),
447: dict(chapters=[("M3-C13-U0", None, [("7","Entries in the books of Purchasing Company","13.29")])],
    scope="single", confidence="inferred",
    notes="Duplicate-chapter situation (see row 106/304): mutual-owing elimination post-amalgamation has no matching AS14 topic, falls to M3-C13-U0's purchasing-company-entries topic per the fallback rule."),
448: dict(chapters=[("M2-C5-U2","AS 10", [("2.7","Initial Recognition","5.28")]),
                    ("M2-C5-U4","AS 16", [("4.9","Commencement of Capitalisation","5.122")])],
    scope="multiple", confidence="confident",
    notes="Self-constructed asset cost genuinely combines AS10 (component costs) and AS16 (capitalised interest) within one connected question. Case cluster d27f9a5b now spans THREE chapters: AS13 (row 138), AS2 (row 367), and AS10+AS16 (this row) - flagging per the open cross-chapter case-scenario-cluster issue."),
449: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1 (Sec 69(1) CRR mandatory transfer)."),
450: dict(chapters=[("M1-C1-U0", None, [("3","How Many Accounting Standards?","1.9")])], scope="single", confidence="confident", notes="AS22 chapter-grouping question, same theme as row 271."),
}
