# Batch 8 (rows 351-400)
TAGS = {
351: dict(chapters=[("M2-C9-U1","AS 12", [("1.6","Presentation of Grants Related to Specific Fixed Assets","9.4")])],
    scope="single", confidence="confident", notes="Case cluster 30b85fe4 (with row 162) - consistent."),
352: dict(chapters=[("M2-C7-U4","AS 22", [("4.5","Measurement","7.57")])], scope="single", confidence="confident", notes="Net DTA/DTL calc."),
353: dict(chapters=[("M3-C14-U0", None, [("2","Methods of internal reconstruction","14.4")])], scope="single", confidence="confident", notes="Sections 61/66."),
354: dict(chapters=[("M1-C4-U3","AS 17", [("3.9","Identifying Reportable Segments (Quantitative Thresholds)","4.51")])], scope="single", confidence="confident", notes="Continuity rule for previously-reportable segments."),
355: dict(chapters=[("M2-C5-U3","AS 13", [("3.5","Cost of Investments","5.8")]),
                    ("M2-C10-U1","AS 21", [("1.11","Calculation of Goodwill/Capital Reserve (Cost of Control)","10.2")])],
    scope="multiple", confidence="inferred",
    notes="Primary: AS13's pre-acquisition-dividend-reduces-cost rule (explanation explicitly cites AS13). Secondary: AS21 consolidation context (CSV bucket), since this affects cost-of-control/goodwill computation - same pattern as row 147."),
356: dict(chapters=[("M3-C15-U0", None, [("5","Accounting for Dependent Branches","15.6")])], scope="single", confidence="confident", notes="Wholesale-price outlet Stock Reserve calc."),
357: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])],
    scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1. Case cluster f5667ebd (with rows 35, 315) - consistent."),
358: dict(chapters=[("M1-C2-U0", None, [("6","Fundamental Accounting Assumptions","2.6")])], scope="single", confidence="confident", notes="Disclosure only if not followed."),
359: dict(chapters=[("M1-C3-U0", None, [("2","Applicability of Accounting Standards","3.6")])], scope="single", confidence="confident", notes="Large->MSME transition, 2-consecutive-year rule - core topic-2 content."),
360: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])],
    scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1. Case cluster f5667ebd (with rows 35, 315, 357) - consistent."),
361: dict(chapters=[("M2-C5-U2","AS 10", [("2.6","Measurement of PPE","5.27")])],
    scope="single", confidence="flagged",
    notes="Content is a basic Suspense-Account/profit-on-disposal rectification exercise - loosely AS10-adjacent (disposal proceeds vs carrying amount) but this specific bookkeeping-rectification style isn't clearly covered by any Inter-level AS10 topic; may be more foundational-level content that doesn't map cleanly onto this taxonomy. Flagging for review rather than asserting high confidence."),
362: dict(chapters=[("M2-C5-U3","AS 13", [("3.6","Carrying Amount of Investments","5.82")])],
    scope="single", confidence="confident", notes="Case cluster 35195135 (with rows 54, 87, 375) - all AS13, consistent."),
363: dict(chapters=[("M2-C9-U2","AS 14", [("2.7","Consideration","9.27")])], scope="single", confidence="confident", notes="Duplicate-chapter rule (row 106) - AS14 topic matches directly."),
364: dict(chapters=[("M2-C9-U2","AS 14", [("2.7","Consideration","9.27")])], scope="single", confidence="confident", notes="Duplicate-chapter rule (row 106) - AS14 topic matches directly."),
365: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])],
    scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1. Case cluster 9baffa7e (with rows 180, 247, 368) - consistent."),
366: dict(chapters=[("M1-C1-U0", None, [("14","Roadmap for Implementation of Indian Accounting Standards (Ind AS): A Snapshot","1.26")])], scope="single", confidence="confident", notes="NBFC roadmap Phase I."),
367: dict(chapters=[("M2-C5-U1","AS 2", [("1.3","Measurement of Inventories","5.4")])],
    scope="single", confidence="confident",
    notes="Case cluster d27f9a5b spans AS13 (row 138, investment carrying amount) and AS2 (this row, RM/FG closing stock) - flagging per the open cross-chapter case-scenario-cluster issue."),
368: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])],
    scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1. Case cluster 9baffa7e (with rows 180, 247, 365) - consistent."),
369: dict(chapters=[("M2-C5-U2","AS 10", [("2.7","Initial Recognition","5.28")])],
    scope="single", confidence="confident",
    notes="Case cluster 080adcad now spans AS10 (row 43, this row), AS12 (row 227), and mentions AS16 capitalised-interest tangentially (not independently tested here) - flagging per the open cross-chapter case-scenario-cluster issue."),
370: dict(chapters=[("M2-C9-U1","AS 12", [("1.8","Presentation of Grants of the Nature of Promoters' Contribution","9.9")])],
    scope="single", confidence="confident", notes="Case cluster 30b85fe4 (with rows 162, 351) - all AS12, consistent."),
371: dict(chapters=[("M1-C1-U0", None, [("1","Introduction","1.2")])], scope="single", confidence="confident", notes="Benefit of AS = additional disclosures for alternative treatments."),
372: dict(chapters=[("M1-C1-U0", None, [("14","Roadmap for Implementation of Indian Accounting Standards (Ind AS): A Snapshot","1.26")])], scope="single", confidence="confident", notes="Ind AS roadmap Phase I companies."),
373: dict(chapters=[("M2-C6-U2","AS 29", [("2.4","Recognition of provision","6.32")])], scope="single", confidence="confident", notes="Three conditions for provision recognition."),
374: dict(chapters=[("M1-C1-U0", None, [("6","International Accounting Standard Board","1.15")])], scope="single", confidence="confident", notes="IAS/IFRS naming cutoff 2001."),
375: dict(chapters=[("M2-C5-U3","AS 13", [("3.5","Cost of Investments","5.8")])],
    scope="single", confidence="confident", notes="Case cluster 35195135 (with rows 54, 87, 362) - all AS13, consistent."),
376: dict(chapters=[("M1-C4-U1","AS 1", [("1.2","Fundamental Accounting Assumptions","4.3"), ("1.4","Selection of Accounting Policy","4.5")])],
    scope="single", confidence="confident", notes="Accrual + prudence, overdue interest not provided."),
377: dict(chapters=[("M1-C1-U0", None, [("13","List of Ind AS","1.23")])], scope="single", confidence="confident", notes="Ind AS 28 mapping."),
378: dict(chapters=[("M2-C7-U3","AS 11", [("3.4","Reporting at each balance sheet date","7.32")])],
    scope="single", confidence="confident", notes="Case cluster 0ebfb1c7 (with rows 225, 310, 316) - all AS11, consistent."),
379: dict(chapters=[("M3-C15-U0", None, [("5","Accounting for Dependent Branches","15.6")])], scope="single", confidence="confident", notes="Debtors Method credit balance = profit."),
380: dict(chapters=[("M1-C3-U0", None, [("1","Status of Accounting Standards","3.2")])], scope="single", confidence="confident", notes="Religious trust with commercial bookshop - AS applies to all activities."),
381: dict(chapters=[("M2-C6-U2","AS 29", [("2.11","Measurement: Best Estimate","6.38")])],
    scope="single", confidence="confident",
    notes="Uses the identical three warranty invoices (11 Feb 20X0, 25 Dec 20X0, 04 Oct 20X1) as row 204, computing the earlier-point-in-time provision that row 204 then treats as its opening balance - clearly two parts of the same original worked example, not linked by a shared case_study_id though. Noting the connection for cross-reference."),
382: dict(chapters=[("M2-C5-U3","AS 13", [("3.6","Carrying Amount of Investments","5.82")])],
    scope="single", confidence="confident",
    notes="Near-identical to row 151 with the same figures scaled x100 (1,000/800/1,200 vs 1,00,000/80,000/1,20,000) and identical question structure - a strong candidate for the OP/PP recurring-question mechanism (SKILL-question-bank-duplicate-detection.md, not yet run against this bank). Flagging for that future pass rather than resolving OP/PP roles here."),
383: dict(chapters=[("M1-C2-U0", None, [("9","Elements of Financial Statements","2.13")])], scope="single", confidence="confident", notes="Binding agreement liability + expected-loss expense."),
384: dict(chapters=[("M1-C1-U0", None, [("1","Introduction","1.2")])], scope="single", confidence="confident", notes="Harmonisation + reliability objectives."),
385: dict(chapters=[("M1-C4-U3","AS 17", [("3.4","Definition of the terms used in the Accounting Standard","4.45")])], scope="single", confidence="confident", notes="Segment Revenue definition."),
386: dict(chapters=[("M2-C8-U1","AS 7", [("1.6","Percentage Completion Method","8.12")])], scope="single", confidence="confident", notes="Expected loss recognised immediately."),
387: dict(chapters=[("M1-C2-U0", None, [("5","Objectives and Users of Financial Statements","2.5")])], scope="single", confidence="confident", notes=""),
388: dict(chapters=[("M2-C7-U3","AS 11", [("3.11","Forward Exchange Contract","7.41")])],
    scope="single", confidence="confident",
    notes="Case cluster c2aa648f now spans FOUR chapters: AS21+AS23 (row 61), AS5 (row 244), AS9 (row 249), and AS11 (this row) - the largest cross-chapter cluster besides 5c708acd, flagging per the open case-scenario-cluster issue."),
389: dict(chapters=[("M2-C9-U2","AS 14", [("2.9","Adjustments to reserves - Amalgamation in the Nature of Merger","9.28"), ("2.10","Adjustments to reserves - Amalgamation in the Nature of Purchase","9.29")])],
    scope="single", confidence="confident", notes=""),
390: dict(chapters=[("M2-C8-U2","AS 9", [("2.2","Definition of Revenue","8.36")])],
    scope="single", confidence="confident", notes="Case cluster dff21db8 (with rows 22, 210) - this member is AS9, matching row 22's chapter."),
391: dict(chapters=[("M2-C10-U1","AS 21", [("1.11","Calculation of Goodwill/Capital Reserve (Cost of Control)","10.2")])], scope="single", confidence="confident", notes="Subsidiary asset revaluation at acquisition = capital profit."),
392: dict(chapters=[("M1-C4-U4","AS 18", [("4.3","Related Party Relationships, as contemplated under AS-18","4.73")])], scope="single", confidence="confident", notes="Indirect voting-rights chain."),
393: dict(chapters=[("M2-C8-U2","AS 9", [("2.5","Timing of Recognition of Revenue from Sale of Goods","8.39")])], scope="single", confidence="confident", notes="Bill-and-hold, delivery delayed at buyer's request."),
394: dict(chapters=[("M2-C9-U2","AS 14", [("2.9","Adjustments to reserves - Amalgamation in the Nature of Merger","9.28")])], scope="single", confidence="confident", notes="Duplicate-chapter rule (row 106) - AS14 topic matches directly."),
395: dict(chapters=[("M3-C15-U0", None, [("7","Adjustment and Reconciliation of Branch& Head Office Accounts","15.44")])], scope="single", confidence="confident", notes="HO collected from branch customer without informing branch."),
396: dict(chapters=[("M2-C7-U4","AS 22", [("4.4","Recognition","7.56")])], scope="single", confidence="confident", notes="Tax-holiday DTL non-recognition rule."),
397: dict(chapters=[("M2-C8-U1","AS 7", [("1.6","Percentage Completion Method","8.12"), ("1.9","Stage of Completion","8.18")])], scope="single", confidence="confident", notes="Cost-method stage-of-completion revenue calc."),
398: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1 (Board vs Special Resolution 10% threshold)."),
399: dict(chapters=[("M1-C2-U0", None, [("7","Qualitative Characteristics of Financial Statements","2.11")])], scope="single", confidence="confident", notes="Balance between Benefit and Cost = pervasive constraint."),
400: dict(chapters=[("M3-C14-U0", None, [("3","Alteration of Share Capital","14.4"), ("7","Surrender of Shares","14.12")])], scope="single", confidence="confident", notes="Sub-division + surrender combined entry."),
}
