# Batch 2 (rows 51-100)
TAGS = {
51: dict(chapters=[("M2-C7-U3","AS 11", [("3.4","Reporting at each balance sheet date","7.32")])],
    scope="single", confidence="confident", notes=""),
52: dict(chapters=[("M2-C5-U2","AS 10", [("2.7","Initial Recognition","5.28")])],
    scope="single", confidence="confident", notes="Case cluster bc3fd25b (deferred payment cash-price-equivalent)."),
53: dict(chapters=[("M3-C14-U0", None, [("8","Entries in case of internal reconstruction","14.12")])],
    scope="single", confidence="inferred", notes="Debenture-value-reduction Capital Reduction credit mapped to the general journal-entries topic; no separate debenture-specific topic in file 1's 8-topic list."),
54: dict(chapters=[("M2-C5-U3","AS 13", [("3.8","Disposal of Investments","5.86")])],
    scope="single", confidence="confident", notes="Case cluster 35195135 (with row 87) - both AS13, consistent."),
55: dict(chapters=[("M2-C8-U2","AS 9", [("2.5","Timing of Recognition of Revenue from Sale of Goods","8.39"), ("2.9","Effect of Uncertainties on Revenue Recognition","8.47")])],
    scope="single", confidence="confident", notes=""),
56: dict(chapters=[("M2-C8-U1","AS 7", [("1.5","Contract Revenue and Costs","8.7")])],
    scope="single", confidence="flagged",
    notes="Source inconsistency: question stem says 'Under AS 9' but the explanation correctly identifies this as an AS 7 construction-contract incentive-payment question. Tagged to AS 7 (per the explanation, which is authoritative), but flagging the stem's AS9 mislabel for awareness - not something to silently fix in original data."),
57: dict(chapters=[("M2-C5-U2","AS 10", [("2.7","Initial Recognition","5.28")])],
    scope="single", confidence="confident", notes="Case cluster 3b2dee7b (dismantling cost PV)."),
58: dict(chapters=[("M2-C10-U1","AS 21", [("1.10","Consolidation Procedures","10.18")])],
    scope="single", confidence="inferred", notes="Reporting-date-gap (max 6 months) rule not separately topic-numbered; mapped to Consolidation Procedures."),
59: dict(chapters=[("M3-C11-U1", None, [("1.6","Distributable Profit","11.18")])],
    scope="single", confidence="confident", notes=""),
60: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])],
    scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1 (Debt-Equity Test minimum equity)."),
61: dict(chapters=[("M2-C10-U1","AS 21", [("1.1","Concept of Group, Holding Company and Subsidiary Company","10.2")]),
                   ("M2-C10-U2","AS 23", [("2.4","Associates Accounted for using the Equity method","10.114")])],
    scope="multiple", confidence="inferred",
    notes="Case cluster c2aa648f. Tests both AS21 (SEAS consolidating subsidiary ADI) and AS23 (equity method for ADI's/SEAS's associate stakes) as genuinely connected content in one fact pattern."),
62: dict(chapters=[("M2-C9-U1","AS 12", [("1.6","Presentation of Grants Related to Specific Fixed Assets","9.4")])],
    scope="single", confidence="confident", notes=""),
63: dict(chapters=[("M1-C4-U1","AS 1", [("1.4","Selection of Accounting Policy","4.5")])],
    scope="single", confidence="confident", notes="Prudence threshold for provisions, same topic as row 32."),
64: dict(chapters=[("M2-C6-U1","AS 15", [("1.4","Short-term Employee Benefits","6.6")])],
    scope="single", confidence="confident", notes="Accumulating compensated absences."),
65: dict(chapters=[("M2-C9-U2","AS 14", [("2.8","Treatment of Reserves of the Transferor Company on Amalgamation","9.28")])],
    scope="single", confidence="confident", notes=""),
66: dict(chapters=[("M1-C1-U0", None, [("2","Standards Setting Process","1.6")])],
    scope="single", confidence="confident", notes="ASB composition."),
67: dict(chapters=[("M1-C3-U0", None, [("1","Status of Accounting Standards","3.2")])],
    scope="single", confidence="confident", notes="ICDS notification under Sec 145(2)."),
68: dict(chapters=[("M1-C2-U0", None, [("9","Elements of Financial Statements","2.13")])],
    scope="single", confidence="confident", notes=""),
69: dict(chapters=[("M1-C4-U5","AS 20", [("5.12","Disclosure","4.113")])],
    scope="single", confidence="confident",
    notes="CSV chapter_id is 'Other Accounting Standards' but AS20 canonically belongs to the Presentation & Disclosures chapter group (M1-C4-U5), not M2-C9 - a genuine bucket-label mismatch (not just coarseness), tagged per the canonical taxonomy regardless of the CSV's own grouping."),
70: dict(chapters=[("M2-C6-U2","AS 29", [("2.6","Past Event","6.33")])],
    scope="single", confidence="confident", notes="Obligating event / virtually-certain-legislation rule."),
71: dict(chapters=[("M1-C4-U3","AS 17", [("3.9","Identifying Reportable Segments (Quantitative Thresholds)","4.51")])],
    scope="single", confidence="confident", notes=""),
72: dict(chapters=[("M2-C7-U4","AS 22", [("4.3","Definitions","7.55")])],
    scope="single", confidence="confident", notes=""),
73: dict(chapters=[("M1-C2-U0", None, [("3","Status and Scope of the Framework","2.3")])],
    scope="single", confidence="confident", notes=""),
74: dict(chapters=[("M2-C5-U4","AS 16", [("4.6","Specific borrowings","5.119")])],
    scope="single", confidence="confident", notes="Temporary-investment-income offset, same theme as row 2."),
75: dict(chapters=[("M2-C9-U2","AS 14", [("2.11","Treatment of Goodwill Arising on Amalgamation","9.3")])],
    scope="single", confidence="confident", notes=""),
76: dict(chapters=[("M1-C2-U0", None, [("9","Elements of Financial Statements","2.13")])],
    scope="single", confidence="confident", notes="Equity definition."),
77: dict(chapters=[("M1-C2-U0", None, [("1","Introduction","2.2")])],
    scope="single", confidence="confident", notes="8 principal areas of the Framework."),
78: dict(chapters=[("M2-C7-U3","AS 11", [("3.5","Recognition of Exchange Differences","7.32")])],
    scope="single", confidence="confident", notes="Para 46A option not exercised."),
79: dict(chapters=[("M3-C11-U2", None, [("2.4","Calculation of Cash Flows from Operating Activities","11.8"), ("2.5","Calculation of Cash Flows from Investing Activities","11.82"), ("2.6","Calculation of Cash Flows from Financing Activities","11.82")])],
    scope="single", confidence="confident",
    notes="Case cluster 7c0cf99a - full cash-flow reconciliation spanning all three activity types within the one AS3/Cash-Flow-Statement chapter; mapped to M3-C11-U2 per established convention."),
80: dict(chapters=[("M3-C15-U0", None, [("5","Accounting for Dependent Branches","15.6")])],
    scope="single", confidence="confident", notes="Stock Reserve on opening stock, invoice-price method."),
81: dict(chapters=[("M1-C3-U0", None, [("2","Applicability of Accounting Standards","3.6")])],
    scope="single", confidence="confident", notes="ICAI 433rd-meeting revision history."),
82: dict(chapters=[("M2-C7-U2","AS 5", [("2.3","Prior Period Items","7.17")])],
    scope="single", confidence="confident", notes=""),
83: dict(chapters=[("M2-C7-U1","AS 4", [("1.5","Non-Adjusting Events","7.4")])],
    scope="single", confidence="confident", notes=""),
84: dict(chapters=[("M1-C1-U0", None, [("9","What are Carve Outs/Ins in Ind AS?","1.18")])],
    scope="single", confidence="confident", notes=""),
85: dict(chapters=[("M3-C15-U0", None, [("5","Accounting for Dependent Branches","15.6")])],
    scope="single", confidence="confident", notes="Wholesale Price Branch Method, retail-sales-from-gross-profit calc."),
86: dict(chapters=[("M3-C13-U0", None, [("6","Journal Entries to close the books of Vendor Company","13.21")])],
    scope="single", confidence="confident", notes="Realization Account exclusions."),
87: dict(chapters=[("M2-C5-U3","AS 13", [("3.5","Cost of Investments","5.8")])],
    scope="single", confidence="confident", notes="Case cluster 35195135 (with row 54) - both AS13, consistent."),
88: dict(chapters=[("M2-C8-U1","AS 7", [("1.5","Contract Revenue and Costs","8.7")])],
    scope="single", confidence="inferred", notes="Gross-amount-due-from/to-customers formula not separately topic-numbered; mapped to Contract Revenue and Costs."),
89: dict(chapters=[("M3-C11-U1", None, [("1.2","Maintenance of Books of Account","11.6")])],
    scope="single", confidence="confident", notes=""),
90: dict(chapters=[("M1-C1-U0", None, [("13","List of Ind AS","1.23")])],
    scope="single", confidence="confident", notes=""),
91: dict(chapters=[("M3-C11-U2", None, [("2.5","Calculation of Cash Flows from Investing Activities","11.82")])],
    scope="single", confidence="confident", notes="Case cluster f5e7dfbc; mapped to M3-C11-U2 per established AS3 convention."),
92: dict(chapters=[("M1-C4-U1","AS 1", [("1.4","Selection of Accounting Policy","4.5")])],
    scope="single", confidence="confident", notes=""),
93: dict(chapters=[("M3-C14-U0", None, [("3","Alteration of Share Capital","14.4")])],
    scope="single", confidence="confident", notes="Conversion of shares into stock (Sec 61)."),
94: dict(chapters=[("M2-C5-U2","AS 10", [("2.6","Measurement of PPE","5.27")])],
    scope="single", confidence="inferred", notes="Same depreciation-commencement gap as row 41."),
95: dict(chapters=[("M1-C3-U0", None, [("2","Applicability of Accounting Standards","3.6")])],
    scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 25/34 (MSME para-87 encouraged-disclosure relaxation)."),
96: dict(chapters=[("M1-C2-U0", None, [("11","Capital Maintenance","2.25")])],
    scope="single", confidence="confident", notes="Financial Capital Maintenance at Current Purchasing Power."),
97: dict(chapters=[("M2-C6-U2","AS 29", [("2.15","Reimbursements","6.4")])],
    scope="single", confidence="confident", notes=""),
98: dict(chapters=[("M1-C2-U0", None, [("10","Measurement of Elements of Financial Statements","2.21")])],
    scope="single", confidence="confident", notes="Present Value convention."),
99: dict(chapters=[("M3-C11-U2", None, [("2.3","Classification of Cash Flow Activities","11.76")])],
    scope="single", confidence="confident", notes="Non-cash bonus-share transaction exclusion; mapped to M3-C11-U2 per established AS3 convention."),
100: dict(chapters=[("M2-C5-U3","AS 13", [("3.6","Carrying Amount of Investments","5.82")])],
    scope="single", confidence="confident", notes="Current vs long-term investment decline treatment."),
}
