"""
telegram/branding/brand_kit.py -- the ONE place 1LAVYA branding is defined
(2026-08-10, Phase 1 of the branding-kit -> report-pipeline -> leaderboard ->
admin-portal roadmap)
--------------------------------------------------------------------------------
Every 1LAVYA-authored, student/admin-facing HTML page or PDF report should
import from here rather than hand-rolling its own header/footer/colors --
one visual fix or copy change happens here once, not separately in the
dashboard, every future report, etc. Same "single source of truth" principle
CLAUDE.md section 7 already states for print/pagination CSS.

**NEVER used for faculty-branded content.** Per Pranav's explicit rule
(2026-08-10): faculty-facing bot output carries no 1LAVYA branding at all
(see telegram/bots/study_hub_bot.py's/exam_hub_bot.py's own "Powered by
1LAVYA" footer scope notes) -- this module is for 1LAVYA's OWN surfaces
only: the admin dashboard, and reports 1LAVYA itself generates and sends.

Markup is deliberately table/inline-block based, NOT flexbox/grid -- it has
to render correctly in TWO different engines with very different CSS
support: a real browser (the dashboard) and xhtml2pdf/reportlab (future
PDF reports, see exam_hub_bot.py's html_to_pdf_bytes() for the existing,
proven-compatible style this matches). One markup that works in the more
constrained engine works in both; the reverse isn't true.

Assets are pre-generated by build_brand_kit.py (re-run that script if
telegram/1LAVYA_LOGO.jpeg ever changes) -- this module only reads what's
already on disk, it never processes the source image itself.
"""

import json
import base64
from pathlib import Path

HERE = Path(__file__).resolve().parent
ASSETS_DIR = HERE / "assets"
COLORS_JSON = HERE / "brand_colors.json"

TAGLINE = "Learn. Practice. Achieve."
BRAND_NAME = "1LAVYA"

_LOGO_FILES = {
    "header": ASSETS_DIR / "1lavya_logo_header_128.png",
    "footer": ASSETS_DIR / "1lavya_logo_footer_48.png",
    "full": ASSETS_DIR / "1lavya_logo_transparent.png",   # one-per-document use only (~800KB) -- see its own file comment
}

_colors_cache = None
_data_uri_cache = {}


def _load_colors() -> dict:
    global _colors_cache
    if _colors_cache is None:
        if not COLORS_JSON.exists():
            raise FileNotFoundError(
                f"{COLORS_JSON} not found -- run `python telegram/branding/build_brand_kit.py` first."
            )
        _colors_cache = json.loads(COLORS_JSON.read_text(encoding="utf-8"))
    return _colors_cache


def colors() -> dict:
    """{'navy': '#...', 'gold': '#...', 'navy_tint': '#...', 'gold_tint': '#...', 'ink': '#...'}
    -- see brand_colors.json's own $comment for how navy/gold were derived."""
    c = _load_colors()
    return {k: v for k, v in c.items() if not k.startswith("_") and k != "$comment"}


def logo_data_uri(variant: str = "header") -> str:
    """variant: "header" (128px, ~13KB -- default, use in page headers),
    "footer" (48px, ~3KB -- small inline marks), or "full" (1254px, ~800KB
    -- cover pages / one-per-document only, never in a repeating header/
    footer). Cached per-process -- the underlying files are static build
    output, never expected to change without a re-run of
    build_brand_kit.py (which a running process wouldn't see anyway)."""
    if variant not in _LOGO_FILES:
        raise ValueError(f"Unknown logo variant {variant!r} -- valid: {list(_LOGO_FILES)}")
    if variant not in _data_uri_cache:
        path = _LOGO_FILES[variant]
        if not path.exists():
            raise FileNotFoundError(f"{path} not found -- run `python telegram/branding/build_brand_kit.py` first.")
        b64 = base64.b64encode(path.read_bytes()).decode("ascii")
        _data_uri_cache[variant] = f"data:image/png;base64,{b64}"
    return _data_uri_cache[variant]


def render_header_html(title: str, subtitle: str | None = None) -> str:
    """A branded page header -- logo + wordmark on the left, page
    title/subtitle on the right, a two-tone navy/gold rule beneath. Table-
    based layout, see module docstring for why. `title` and `subtitle` are
    inserted as-is -- callers are responsible for HTML-escaping any
    untrusted text before passing it in (matches how the rest of this
    codebase's HTML-generation functions already work, e.g.
    exam_hub_bot.py's html_to_pdf_bytes())."""
    c = colors()
    subtitle_html = (
        f'<div style="font-size:11px; color:{c["ink"]}; opacity:0.7; margin-top:2px;">{subtitle}</div>'
        if subtitle else ""
    )
    return f"""
<table style="width:100%; border-collapse:collapse; margin-bottom:0;">
  <tr>
    <td style="width:52px; vertical-align:middle; padding:0;">
      <img src="{logo_data_uri('header')}" width="44" height="44" style="display:block;">
    </td>
    <td style="vertical-align:middle; padding:0 0 0 12px;">
      <div style="font-size:19px; font-weight:bold; color:{c['navy']}; font-family:Georgia,'Times New Roman',serif;">{BRAND_NAME}</div>
      <div style="font-size:9px; color:{c['gold']}; text-transform:uppercase;">{TAGLINE}</div>
    </td>
    <td style="vertical-align:middle; padding:0; text-align:right;">
      <div style="font-size:15px; color:{c['ink']}; font-weight:bold;">{title}</div>
      {subtitle_html}
    </td>
  </tr>
</table>
<table style="width:100%; border-collapse:collapse; margin:8px 0 20px;"><tr>
  <td style="width:70%; height:3px; background-color:{c['navy']}; font-size:0; line-height:0;">&nbsp;</td>
  <td style="width:30%; height:3px; background-color:{c['gold']}; font-size:0; line-height:0;">&nbsp;</td>
</tr></table>
""".strip()


def render_footer_html() -> str:
    """A branded page footer -- small logo mark + "Powered by 1LAVYA" +
    tagline. Same table-based layout constraint as render_header_html()."""
    c = colors()
    return f"""
<table style="width:100%; border-collapse:collapse; border-top:1px solid {c['navy_tint']}; margin-top:24px; padding-top:8px;">
  <tr>
    <td style="vertical-align:middle; width:20px; padding:6px 0;">
      <img src="{logo_data_uri('footer')}" width="16" height="16" style="display:block;">
    </td>
    <td style="vertical-align:middle; font-size:10px; color:#888888; padding:6px 0 6px 6px;">
      Powered by {BRAND_NAME}
    </td>
    <td style="vertical-align:middle; text-align:right; font-size:10px; color:#888888; padding:6px 0;">
      {TAGLINE}
    </td>
  </tr>
</table>
""".strip()


SUPPORT_EMAIL = "support@1lavya.com"
ADMIN_EMAIL = "admin@1lavya.com"


def render_email_footer_html(sender_bot_label: str = None) -> str:
    """The footer every 1LAVYA-sent EMAIL carries (2026-08-11, the student
    report pipeline's Cloudflare Email Service integration --
    telegram/database/cf_email.py / report_delivery.py). Deliberately
    TEXT-based, not the logo <img> render_header_html()/render_footer_html()
    use -- email clients (Outlook especially) have much less reliable
    data-URI image support than a real browser or xhtml2pdf, so this stays
    text/CSS-only to guarantee it always renders, image-blocking or not.

    Every sending address is unmonitored by design (Pranav, 2026-08-11) --
    this footer is what actually tells a student where a REAL reply goes:
    support@1lavya.com for issues, admin@1lavya.com for "get your own Exam
    or Custom Bot" -- Pranav's exact wording, both confirmed live/monitored
    mailboxes. `sender_bot_label`, if given, is shown so a student who
    replies-none-the-wiser at least sees which bot this came from."""
    c = colors()
    from_line = (
        f'<div style="font-size:11px; color:#888888; margin-bottom:10px;">Sent by {sender_bot_label}</div>'
        if sender_bot_label else ""
    )
    return f"""
<table style="width:100%; border-collapse:collapse; margin-top:24px;"><tr>
  <td style="width:70%; height:3px; background-color:{c['navy']}; font-size:0; line-height:0;">&nbsp;</td>
  <td style="width:30%; height:3px; background-color:{c['gold']}; font-size:0; line-height:0;">&nbsp;</td>
</tr></table>
<div style="padding-top:12px; font-family:Arial,Helvetica,sans-serif;">
  {from_line}
  <div style="font-size:16px; font-weight:bold; color:{c['navy']}; font-family:Georgia,'Times New Roman',serif;">{BRAND_NAME}</div>
  <div style="font-size:10px; color:{c['gold']}; text-transform:uppercase; margin-bottom:10px;">{TAGLINE}</div>
  <div style="font-size:11px; color:#666666; line-height:1.6;">
    This mailbox is unmonitored -- replies here won't be seen.<br>
    For any issues, please email <a href="mailto:{SUPPORT_EMAIL}" style="color:{c['navy']};">{SUPPORT_EMAIL}</a>.<br>
    For getting your own Exam or Custom Bot created, please email <a href="mailto:{ADMIN_EMAIL}" style="color:{c['navy']};">{ADMIN_EMAIL}</a>.
  </div>
</div>
""".strip()


def brand_css_vars() -> str:
    """A <style> block defining CSS custom properties for every brand
    color -- for pages (like the dashboard, a real browser) that want to
    use var(--1lavya-navy) etc. in their own stylesheet rather than the
    inline-style approach render_header_html()/render_footer_html() use
    (those stay inline specifically for xhtml2pdf compatibility -- CSS
    custom properties are NOT reliably supported there, same class of
    limitation as the gradient/flexbox notes above)."""
    c = colors()
    return f"""<style>
  :root {{
    --1lavya-navy: {c['navy']};
    --1lavya-gold: {c['gold']};
    --1lavya-navy-tint: {c['navy_tint']};
    --1lavya-gold-tint: {c['gold_tint']};
    --1lavya-ink: {c['ink']};
  }}
</style>"""
