/*
  Nightly backup, run by the Worker's Cron Trigger (see wrangler.toml [triggers]).

  Writes to the R2 bucket bound as BACKUP ("capranav-backups"):
    d1/critical/YYYY/MM/DD.sql.gz   the tables that hold people's data and cannot be rebuilt from git
    vault/<key>                     an incremental mirror of every object in the VAULT bucket
    status.json                     result of the latest run (read it to check health)

  The full database is also exported every 6 hours by tools/backup_d1_snapshot.py on the owner's PC, which
  uploads the newest export to d1/full/. The anatomy (aa_*) tables are rebuildable from git
  (tools/build_anatomy_seed.py) so they are not in the nightly dump.

  Nothing here ever deletes from the vault mirror. Dumps older than DUMP_KEEP_DAYS are pruned.
*/

// Everything a student, buyer or admin created. Order matters only for readability of the dump.
export const CRITICAL_TABLES = [
  "student_profiles",
  "orders",
  "entitlements",
  "contact_messages",
  "webhook_events",
  "admin_users",
  "deletion_log",
];
const DUMP_KEEP_DAYS = 90;
const PAGE = 500;

function sqlValue(v) {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return Number.isFinite(v) ? String(v) : "NULL";
  if (typeof v === "boolean") return v ? "1" : "0";
  return "'" + String(v).replace(/'/g, "''") + "'";
}

export async function dumpCriticalTables(db) {
  const lines = ["-- capranav-platform critical tables, generated by the nightly backup", "PRAGMA foreign_keys = OFF;"];
  const counts = {};
  for (const table of CRITICAL_TABLES) {
    const info = await db.prepare(`PRAGMA table_info(${table})`).all();
    const cols = (info.results || []).map((c) => c.name);
    if (!cols.length) { counts[table] = "missing"; continue; }
    let offset = 0, total = 0;
    for (;;) {
      const page = await db.prepare(`SELECT * FROM ${table} LIMIT ${PAGE} OFFSET ${offset}`).all();
      const rows = page.results || [];
      for (const r of rows) {
        lines.push(`INSERT INTO "${table}" (${cols.map((c) => `"${c}"`).join(", ")}) VALUES (${cols.map((c) => sqlValue(r[c])).join(", ")});`);
      }
      total += rows.length;
      if (rows.length < PAGE) break;
      offset += PAGE;
    }
    counts[table] = total;
  }
  return { sql: lines.join("\n") + "\n", counts };
}

async function gzip(text) {
  const stream = new Blob([text]).stream().pipeThrough(new CompressionStream("gzip"));
  return new Response(stream).arrayBuffer();
}

export async function mirrorVault(vault, backup) {
  let copied = 0, skipped = 0, bytes = 0, cursor;
  const failures = [];
  do {
    const listing = await vault.list({ cursor, limit: 500 });
    for (const obj of listing.objects) {
      const target = "vault/" + obj.key;
      try {
        const existing = await backup.head(target);
        if (existing && existing.size === obj.size) { skipped++; continue; }
        const src = await vault.get(obj.key);
        if (!src) { failures.push(obj.key + " (vanished)"); continue; }
        await backup.put(target, src.body, { httpMetadata: src.httpMetadata, customMetadata: { sourceEtag: obj.etag } });
        copied++; bytes += obj.size;
      } catch (e) {
        failures.push(`${obj.key}: ${e && e.message}`);
      }
    }
    cursor = listing.truncated ? listing.cursor : undefined;
  } while (cursor);
  return { copied, skipped, bytes, failures };
}

async function pruneDumps(backup, now) {
  const cutoff = now.getTime() - DUMP_KEEP_DAYS * 86400000;
  let cursor, removed = 0;
  do {
    const listing = await backup.list({ prefix: "d1/critical/", cursor });
    for (const o of listing.objects) {
      if (o.uploaded.getTime() < cutoff) { await backup.delete(o.key); removed++; }
    }
    cursor = listing.truncated ? listing.cursor : undefined;
  } while (cursor);
  return removed;
}

export async function runBackup(env) {
  const now = new Date();
  const status = { at: now.toISOString(), ok: false, d1: null, vault: null, pruned: 0, error: null };
  try {
    const { sql, counts } = await dumpCriticalTables(env.DB);
    const key = `d1/critical/${now.getUTCFullYear()}/${String(now.getUTCMonth() + 1).padStart(2, "0")}/${String(now.getUTCDate()).padStart(2, "0")}.sql.gz`;
    await env.BACKUP.put(key, await gzip(sql), { httpMetadata: { contentType: "application/gzip" } });
    status.d1 = { key, bytes: sql.length, rows: counts };
    status.vault = await mirrorVault(env.VAULT, env.BACKUP);
    status.pruned = await pruneDumps(env.BACKUP, now);
    status.ok = status.vault.failures.length === 0;
    if (!status.ok) status.error = "vault mirror had failures: " + status.vault.failures.slice(0, 5).join("; ");
  } catch (e) {
    status.error = String(e && e.message ? e.message : e);
  }
  await env.BACKUP.put("status.json", JSON.stringify(status, null, 2), { httpMetadata: { contentType: "application/json" } });
  return status;
}
