"""
telegram/admin_portal/app.py -- 1LAVYA Admin Portal (2026-08-11, Phase 4 of
the branding-kit -> report-pipeline -> leaderboard -> admin-portal roadmap)
--------------------------------------------------------------------------------
FOUNDATION TIER ONLY (Pranav's confirmed build order, 2026-08-11: "Flask
migration + sidebar shell + login + Bot Status/Restart + Bot-wise Logs
first... then Analytics tabs... then Masters... then Leaderboard/Catalog
edits last"). This is that first tier. Everything else on his module list
(Analytics, Masters display/editing, Faculty/Bot addition, Question
Catalog edits, Leaderboard edits, student-profile<->leaderboard mappings,
Email analytics, module-wise RBAC) is a FOLLOW-UP phase, each built,
smoke-tested, and handed off for his confirmation before the next one --
see telegram/admin_portal/README.md for the live status of what's built
vs. still coming, and CLAUDE.md section 11 for the full decision trail.

RUNS ALONSIDE the existing telegram/tools/dashboard_server.py (port 8787),
not replacing it yet -- that dashboard's Analytics content (Student
Master, Faculty Report, Content Health, Bot-wise Usage, Message Volume)
stays the working, live source for Analytics until the Analytics tab in
THIS app is actually built and can absorb it. This app runs on port 8788
by default. Once Analytics (and everything else) has moved over, the old
dashboard retires -- not before, so nothing Pranav currently relies on
breaks mid-transition.

AUTH: single-admin login (see auth.py's own docstring for why every route
is wrapped in role_required(), not a bare login_required(), even though
only one role exists today) -- credentials in telegram/.env, generated by
set_password.py. SECRET_KEY signs the session cookie; there is no
"remember me" -- closing the browser or restarting this process
invalidates the session (Flask's default in-memory-signed-cookie
behavior), which is the right default for an internal ops tool with no
persistent-session requirement stated.

BOT RESTART calls telegram/tools/manage_bots.py's OWN restart_bot()
function directly (imported, not subprocessed) -- the exact same code
path `python manage_bots.py restart <id>` already uses from a terminal,
so this button can never drift from that script's own behavior. Blocking
(can take up to ~15-25s: manage_bots.py's GRACE_PERIOD_SECONDS=12s stop
wait, then a fresh start) -- the confirm dialog + a "Restarting..." button
state is enough UX for an internal tool used by one person at a time; no
async job queue built for this yet.
"""

import os
import sys
import time
import threading
from datetime import datetime, timedelta, timezone
from pathlib import Path
from urllib.parse import urlencode

from flask import Flask, render_template, request, redirect, url_for, session, flash, Response
from dotenv import load_dotenv

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "telegram" / "database"))
sys.path.insert(0, str(REPO_ROOT / "telegram" / "tools"))
sys.path.insert(0, str(REPO_ROOT / "telegram" / "branding"))
sys.path.insert(0, str(Path(__file__).resolve().parent))

load_dotenv(REPO_ROOT / "telegram" / ".env")

import db as platform_db  # noqa: E402
import analytics  # noqa: E402
import manage_bots  # noqa: E402
import brand_kit  # noqa: E402
import auth  # noqa: E402
import audit  # noqa: E402
import exporters  # noqa: E402
import report_delivery  # noqa: E402 -- telegram/database/report_delivery.py
import student_analytics  # noqa: E402 -- telegram/database/student_analytics.py
import generate_student_report  # noqa: E402 -- telegram/tools/generate_student_report.py
import document_catalog  # noqa: E402 -- telegram/admin_portal/document_catalog.py
import charts  # noqa: E402 -- telegram/admin_portal/charts.py, inline SVG (2026-08-13)
import charts_pdf  # noqa: E402 -- telegram/admin_portal/charts_pdf.py, reportlab-native PDF charts (2026-08-13)
import faculty_report  # noqa: E402 -- telegram/admin_portal/faculty_report.py, Comprehensive Faculty Report (2026-08-14)
import faculty_master  # noqa: E402 -- telegram/admin_portal/faculty_master.py, Faculty Master DB table (2026-08-14)
import backup_status  # noqa: E402 -- telegram/admin_portal/backup_status.py, Backup Snapshot Summary (2026-08-16)
import sql_query_tool  # noqa: E402 -- telegram/admin_portal/sql_query_tool.py, read-only ad hoc SQL query tab (2026-08-17)

app = Flask(__name__)
app.secret_key = os.environ.get("ADMIN_PORTAL_SECRET_KEY") or os.urandom(32)
if not os.environ.get("ADMIN_PORTAL_SECRET_KEY"):
    app.logger.warning(
        "ADMIN_PORTAL_SECRET_KEY not set in telegram/.env -- using a random key for this "
        "process only (every session invalidates on restart). Run set_password.py to fix."
    )

BOT_ID = "1lavya-admin-portal"   # this process's own bot_id, for its heartbeat -- see bots.json

# Sidebar structure -- built ONCE here (not hand-duplicated per template)
# so adding/graying a module is a one-line change picked up everywhere the
# sidebar renders. `enabled: False` items render as a "Soon" badge, not a
# link -- communicates the full intended shape of the portal even before
# every module is built (Pranav's "very scalable... each and everything
# should be able to be visible" ask), without pretending they work yet.
NAV_SECTIONS = [
    {"label": "Overview", "links": [
        {"label": "Dashboard", "endpoint": "overview", "icon": "\U0001F3E0", "enabled": True},
    ]},
    {"label": "Operations", "links": [
        {"label": "Bot Status & Restart", "endpoint": "bots_status", "icon": "\U0001F916", "enabled": True},
    ]},
    {"label": "Analytics", "links": [
        {"label": "Student Master", "endpoint": "analytics_students", "icon": "\U0001F393", "enabled": True},
        {"label": "Bot-wise Usage", "endpoint": "analytics_bots", "icon": "\U0001F4C8", "enabled": True},
        {"label": "Faculty Report", "endpoint": "analytics_faculty_report", "icon": "\U0001F4CB", "enabled": True},
        {"label": "Faculty Comprehensive Report", "endpoint": "faculty_report_view", "icon": "\U0001F4D1", "enabled": True},
        {"label": "Content Health", "endpoint": "analytics_content_health", "icon": "\U0001FA7A", "enabled": True},
        {"label": "Email Analytics", "endpoint": "analytics_email", "icon": "\U0001F4E7", "enabled": True},
        {"label": "MCQ Issue Reports", "endpoint": "analytics_issue_reports", "icon": "\U0001F6A9", "enabled": True},
    ]},
    {"label": "Data Export", "links": [
        {"label": "Export Any Table", "endpoint": "data_export_index", "icon": "\U00002B07\U0000FE0F", "enabled": True},
    ]},
    {"label": "Logs", "links": [
        {"label": "Activity Log", "endpoint": "activity_log", "icon": "\U0001F4CB", "enabled": True},
    ]},
    {"label": "Masters", "links": [
        {"label": "Faculty Details", "endpoint": "masters_faculty_list", "icon": "\U0001F9D1\U0000200D\U0001F3EB", "enabled": True},
        {"label": "Tenants & Bots", "endpoint": None, "icon": "\U0001F5C2️", "enabled": False},
        {"label": "Faculty / New Bot", "endpoint": None, "icon": "➕", "enabled": False},
    ]},
    {"label": "Content", "links": [
        {"label": "Course Catalog", "endpoint": "course_catalog", "icon": "\U0001F4DA", "enabled": True},
        {"label": "Question Catalog Edits", "endpoint": None, "icon": "\U0000270F\U0000FE0F", "enabled": False},
    ]},
    {"label": "Leaderboards", "links": [
        {"label": "Boards & Mappings", "endpoint": None, "icon": "\U0001F3C6", "enabled": False},
    ]},
    {"label": "Users & Access", "links": [
        {"label": "Roles & Permissions", "endpoint": None, "icon": "\U0001F510", "enabled": False},
    ]},
]


def get_conn():
    conn = platform_db.get_connection()
    platform_db.init_schema(conn)
    return conn


@app.template_global()
def page_url(page: int) -> str:
    """Used by templates/_pagination.html on every paginated view --
    preserves every OTHER current query arg (filter text, bot_id, etc.),
    only replacing `page`. One implementation, reused everywhere, so a
    paginated page's Next/Prev links never drop a filter a user just
    applied."""
    args = request.args.to_dict(flat=True)
    args["page"] = page
    return f"{request.path}?{urlencode(args)}"


@app.template_global()
def range_url(preset: str) -> str:
    """Used by activity_log.html's own simple range-preset picker --
    preserves every other current query arg (bot_id, action, status, q),
    sets `preset`, and drops any explicit from/to (a preset and an
    explicit range are mutually exclusive -- picking a preset should
    always win over a stale explicit range still sitting in the URL)."""
    args = request.args.to_dict(flat=True)
    args["preset"] = preset
    args.pop("from", None)
    args.pop("to", None)
    args.pop("page", None)
    return f"{request.path}?{urlencode(args)}"


# 2026-08-17 (Pranav's ask, after testing the Activity Log page): every
# timestamp stored on this platform is UTC (db.py's now(), by design --
# see that module's own docstring), but this machine's own OS clock is
# already India Standard Time (confirmed directly: time.tzname ==
# ('India Standard Time', 'India Daylight Time')) -- which means the RAW
# .log files (Python logging's default %(asctime)s uses LOCAL time, not
# UTC) are already IST. Converting ONLY the on-screen display to IST here
# -- never the stored value, which stays UTC everywhere else on this
# platform, same "store UTC, display local" split leaderboard_broadcaster.py
# already uses for its own fixed-offset scheduling -- actually makes the
# Activity Log's timestamps MATCH the raw log files' own timestamps, not
# just read more naturally.
IST = timezone(timedelta(hours=5, minutes=30))


@app.template_filter("ist")
def to_ist(value):
    """A UTC ISO timestamp string (e.g. "2026-08-17T07:14:43+00:00") ->
    "2026-08-17 12:44:43 IST". Never raises on a malformed/missing value --
    a broken timestamp on one row should show as-is, not break the whole
    table."""
    if not value:
        return value
    try:
        dt = datetime.fromisoformat(value)
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt.astimezone(IST).strftime("%Y-%m-%d %H:%M:%S") + " IST"
    except (ValueError, TypeError):
        return value


@app.template_global()
def clear_filter_url() -> str:
    """Used by templates/_export_toolbar.html's "Clear" link -- drops `q`
    and `page` but preserves everything else (e.g. Faculty Report's
    bot_id selection), so clearing the text filter doesn't also lose an
    unrelated selection."""
    args = request.args.to_dict(flat=True)
    args.pop("q", None)
    args.pop("page", None)
    return f"{request.path}?{urlencode(args)}" if args else request.path


# 2026-08-17: a bot_admin's sidebar is NOT the full NAV_SECTIONS -- every
# other route still requires role_required("admin") so a bot_admin
# couldn't actually open any of them anyway, but showing the full ops/
# analytics/masters sidebar to an account that can reach exactly one page
# is confusing, not just harmless. Deliberately a SEPARATE small constant,
# not a filtered copy of NAV_SECTIONS -- keeps the two roles' navigation
# structurally independent so a future NAV_SECTIONS edit can never
# accidentally leak a new admin-only link into the bot_admin sidebar by
# omission.
BOT_ADMIN_NAV_SECTIONS = [
    {"label": "Logs", "links": [
        {"label": "Activity Log", "endpoint": "activity_log", "icon": "\U0001F4CB", "enabled": True},
    ]},
]


@app.context_processor
def inject_globals():
    nav = BOT_ADMIN_NAV_SECTIONS if auth.current_role() == "bot_admin" else NAV_SECTIONS
    return {
        "nav_sections": nav,
        "current_user": auth.current_user(),
        "current_role": auth.current_role(),
        "brand_colors": brand_kit.colors(),
        "current_endpoint": request.endpoint,
    }


# ---------------------------------------------------------------------------
# AUTH
# ---------------------------------------------------------------------------
@app.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form.get("username", "").strip()
        password = request.form.get("password", "")
        # Super-admin checked FIRST, exactly the original single-account
        # path, completely unchanged -- Pranav's own login can never be
        # affected by anything below this line.
        if auth.verify_credentials(username, password):
            session.clear()
            session["username"] = username
            session["role"] = "admin"
            next_url = request.args.get("next") or url_for("overview")
            return redirect(next_url)
        # 2026-08-17: a bot_admin account (see auth.py's own docstring) --
        # only reachable if BOTH a real admin_accounts row AND a real
        # active admin_access.json entry exist for this username.
        if auth.verify_bot_admin_credentials(username, password):
            session.clear()
            session["username"] = username
            session["role"] = "bot_admin"
            session["allowed_bot_ids"] = auth.bot_admin_allowed_bot_ids(username)
            next_url = request.args.get("next") or url_for("activity_log")
            return redirect(next_url)
        flash("Invalid username or password.", "error")
    return render_template("login.html")


@app.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("login"))


# ---------------------------------------------------------------------------
# OVERVIEW -- rebuilt 2026-08-13 (Pranav's ask: onboarding/content/
# performance/faculty analytics, date-ranged, filterable, exportable,
# sub-tab organized). This is a SUMMARY layer -- charts + top-line tables
# per sub-tab, each linking into the already-built detailed Analytics
# pages (Student Master, Course Catalog, Faculty Report) for full
# row-level drill-down, per his confirmed choice (AskUserQuestion,
# 2026-08-13) rather than duplicating those pages' full tables here.
# ---------------------------------------------------------------------------
OVERVIEW_TABS = ("students", "content", "performance", "faculty", "sql")
OVERVIEW_TAB_LABELS = {
    "students": "Students", "content": "Content", "performance": "Performance", "faculty": "Faculty",
    "sql": "SQL Query",
}
RANGE_PRESETS = {"7d": "Last 7 days", "30d": "Last 30 days", "90d": "Last 90 days", "all": "All time"}


def _date_range_from_args():
    """(start_date, end_date, label) from ?preset=7d/30d/90d/all or an
    explicit ?from=&to=. Defaults to the last 7 days when nothing is
    given (the page's first load) -- every date-ranged tab shares this
    one implementation, so a range picked on one tab means the same thing
    on every other."""
    preset = request.args.get("preset")
    today = datetime.now(timezone.utc).date()
    if preset in ("7d", "30d", "90d"):
        days = int(preset[:-1])
        return (today - timedelta(days=days - 1)).isoformat(), today.isoformat(), RANGE_PRESETS[preset]
    if preset == "all":
        return None, None, RANGE_PRESETS["all"]
    frm, to = request.args.get("from"), request.args.get("to")
    if frm or to:
        return frm or None, to or None, f"{frm or '…'} to {to or '…'}"
    return (today - timedelta(days=6)).isoformat(), today.isoformat(), RANGE_PRESETS["7d"]


def _current_preset() -> str:
    preset = request.args.get("preset")
    if preset in RANGE_PRESETS:
        return preset
    if request.args.get("from") or request.args.get("to"):
        return "custom"
    return "7d"


# --- chart data builders -- ONE function per chart, reused for both the
# on-page render and the chart's own HTML/PDF export endpoint below, so
# neither can silently drift from the other (same discipline every table
# export in this file already follows). ---
def _students_chart_data(conn, start_date, end_date):
    return [(d["date"], d["count"]) for d in analytics.fetch_student_onboarding(conn, start_date, end_date)["daily"]]


def _content_daily_chart_data(conn, start_date, end_date):
    return [(d["date"], d["count"]) for d in analytics.fetch_content_growth(conn, start_date, end_date)["daily"]]


def _content_split_chart_data(conn, start_date, end_date):
    by_qtype = analytics.fetch_content_growth(conn, start_date, end_date)["by_qtype"]
    return [("MCQ", by_qtype.get("mcq", 0)), ("Descriptive", by_qtype.get("descriptive", 0))]


def _performance_daily_chart_data(conn, start_date, end_date):
    return [(d["date"], d["shown"]) for d in analytics.fetch_questions_attempted(conn, start_date, end_date)["daily"]]


def _faculty_chart_data(conn, start_date, end_date):
    roster = analytics.fetch_faculty_roster(conn, manage_bots.load_bots())
    return [(r["display_name"], r["total_interactions"]) for r in roster]


CHART_BUILDERS = {
    "students_daily":      {"title": "New Students",           "kind": "bar",   "color_key": "navy", "fn": _students_chart_data},
    "content_daily":       {"title": "New Questions Added",    "kind": "bar",   "color_key": "navy", "fn": _content_daily_chart_data},
    "content_split":       {"title": "MCQ vs Descriptive",     "kind": "donut", "fn": _content_split_chart_data},
    "performance_daily":   {"title": "Questions Attempted",    "kind": "bar",   "color_key": "navy", "fn": _performance_daily_chart_data},
    "faculty_interactions":{"title": "Faculty -- Total Interactions (all-time)", "kind": "bar", "color_key": "gold", "fn": _faculty_chart_data},
}
DONUT_PALETTE = ["#09284b", "#d0942c", "#5a7a9a", "#c96a4e"]


def _chart_svg_for(chart_id, conn, start_date, end_date):
    spec = CHART_BUILDERS[chart_id]
    data = spec["fn"](conn, start_date, end_date)
    if spec["kind"] == "bar":
        return charts.bar_chart_svg(data, color=brand_kit.colors().get(spec.get("color_key", "navy")))
    segs = [(l, v, DONUT_PALETTE[i % len(DONUT_PALETTE)]) for i, (l, v) in enumerate(data)]
    return charts.donut_chart_svg(segs)


def _chart_download_urls(chart_id, start_date, end_date):
    args = {}
    if start_date:
        args["from"] = start_date
    if end_date:
        args["to"] = end_date
    return {
        "html": url_for("overview_chart_export", chart_id=chart_id, fmt="html", **args),
        "pdf": url_for("overview_chart_export", chart_id=chart_id, fmt="pdf", **args),
    }


@app.route("/overview/chart/<chart_id>.<fmt>")
@auth.role_required("admin")
def overview_chart_export(chart_id, fmt):
    if chart_id not in CHART_BUILDERS or fmt not in ("html", "pdf"):
        return "Unknown chart or format.", 404
    conn = get_conn()
    spec = CHART_BUILDERS[chart_id]
    start_date, end_date, range_label = _date_range_from_args()
    data = spec["fn"](conn, start_date, end_date)
    colors = brand_kit.colors()
    title = spec["title"]
    audit.log_action(conn, auth.current_user(), "chart_export", chart_id, fmt)

    if fmt == "html":
        if spec["kind"] == "bar":
            svg = charts.bar_chart_svg(data, color=colors.get(spec.get("color_key", "navy")))
        else:
            segs = [(l, v, DONUT_PALETTE[i % len(DONUT_PALETTE)]) for i, (l, v) in enumerate(data)]
            svg = charts.donut_chart_svg(segs)
        return exporters.chart_html_response(title, range_label, svg, colors, chart_id)

    if spec["kind"] == "bar":
        pdf_bytes = charts_pdf.bar_chart_pdf_bytes(title, data, colors, subtitle=range_label)
    else:
        segs = [(l, v, DONUT_PALETTE[i % len(DONUT_PALETTE)]) for i, (l, v) in enumerate(data)]
        pdf_bytes = charts_pdf.donut_chart_pdf_bytes(title, segs, colors, subtitle=range_label)
    return exporters.chart_pdf_response(pdf_bytes, chart_id)


@app.route("/")
@auth.role_required("admin")
def overview():
    conn = get_conn()
    bots = manage_bots.load_bots()
    heartbeats = analytics.fetch_heartbeats(conn)
    online_count = sum(1 for b in bots if heartbeats.get(b["bot_id"], {}).get("online"))
    unique_mcq = analytics.fetch_unique_mcq_attempters(conn)

    tab = request.args.get("tab", "students")
    if tab not in OVERVIEW_TABS:
        tab = "students"
    start_date, end_date, range_label = _date_range_from_args()
    preset = _current_preset()

    range_urls = {p: url_for("overview", tab=tab, preset=p) for p in RANGE_PRESETS}
    tab_urls = {
        t: url_for("overview", tab=t, **({"preset": preset} if preset != "custom" else {"from": start_date, "to": end_date}))
        for t in OVERVIEW_TABS
    }

    ctx = dict(
        total_bots=len(bots), online_count=online_count, unique_mcq_attempters=unique_mcq,
        tab=tab, tabs=OVERVIEW_TABS, tab_labels=OVERVIEW_TAB_LABELS, tab_urls=tab_urls,
        range_label=range_label, range_urls=range_urls, range_presets=RANGE_PRESETS, preset=preset,
        start_date=start_date, end_date=end_date,
    )

    if tab == "students":
        onboarding = analytics.fetch_student_onboarding(conn, start_date, end_date)
        page = exporters.paginate(onboarding["daily"], request.args.get("page", 1, type=int), per_page=25)
        ctx.update(
            onboarding=onboarding, pagination=page, daily_rows=page["items"],
            chart_svg=_chart_svg_for("students_daily", conn, start_date, end_date),
            chart_download_urls=_chart_download_urls("students_daily", start_date, end_date),
            export_urls={fmt: url_for("overview_students_export", fmt=fmt, preset=preset, **({} if preset != "custom" else {"from": start_date, "to": end_date}))
                          for fmt in ("csv", "xlsx", "html", "pdf")},
        )

    elif tab == "content":
        growth = analytics.fetch_content_growth(conn, start_date, end_date)
        totals = document_catalog.platform_question_totals(conn)
        q = request.args.get("q", "").strip()
        filtered = exporters.filter_rows(growth["rows"], q, ["subject", "chapter_label", "qtype", "source_file", "content_owner"])
        page = exporters.paginate(filtered, request.args.get("page", 1, type=int), per_page=25)
        ctx.update(
            growth=growth, totals=totals, pagination=page, rows=page["items"],
            filter_query=q, total_filtered=len(filtered),
            chart_svg=_chart_svg_for("content_daily", conn, start_date, end_date),
            chart_download_urls=_chart_download_urls("content_daily", start_date, end_date),
            donut_svg=_chart_svg_for("content_split", conn, start_date, end_date),
            donut_download_urls=_chart_download_urls("content_split", start_date, end_date),
            export_urls={fmt: url_for("overview_content_export", fmt=fmt, q=q, preset=preset, **({} if preset != "custom" else {"from": start_date, "to": end_date}))
                          for fmt in ("csv", "xlsx", "html", "pdf")},
        )

    elif tab == "performance":
        qa = analytics.fetch_questions_attempted(conn, start_date, end_date)
        time_today = analytics.fetch_time_spent_today(conn)
        course_levels = _course_catalog_course_levels(conn)
        perf_course = request.args.get("perf_course") or None
        perf_level = request.args.get("perf_level") or None
        min_attempts = request.args.get("min_attempts", 5, type=int)
        top = analytics.fetch_top_performers(conn, course=perf_course, level=perf_level, min_attempts=min_attempts, limit=15)
        ctx.update(
            qa=qa, time_today=time_today, top_performers=top, min_attempts=min_attempts,
            perf_course=perf_course, perf_level=perf_level,
            perf_courses=list(course_levels.keys()),
            perf_levels=course_levels.get(perf_course, []) if perf_course else [],
            chart_svg=_chart_svg_for("performance_daily", conn, start_date, end_date),
            chart_download_urls=_chart_download_urls("performance_daily", start_date, end_date),
            export_urls={fmt: url_for("overview_performance_export", fmt=fmt, preset=preset,
                                       perf_course=perf_course or "", perf_level=perf_level or "", min_attempts=min_attempts,
                                       **({} if preset != "custom" else {"from": start_date, "to": end_date}))
                          for fmt in ("csv", "xlsx", "html", "pdf")},
        )

    elif tab == "faculty":
        roster = analytics.fetch_faculty_roster(conn, bots)
        ctx.update(
            roster=roster,
            chart_svg=_chart_svg_for("faculty_interactions", conn, start_date, end_date),
            chart_download_urls=_chart_download_urls("faculty_interactions", start_date, end_date),
            export_urls={fmt: url_for("overview_faculty_export", fmt=fmt) for fmt in ("csv", "xlsx", "html", "pdf")},
        )

    elif tab == "sql":
        sql_text = request.args.get("sql", "")
        sql_result = None
        sql_error = None
        if sql_text.strip():
            try:
                sql_result = sql_query_tool.run_query(sql_text)
                audit.log_action(conn, auth.current_user(), "sql_query_run", None, sql_text[:500])
            except (sql_query_tool.QueryRejected, sql_query_tool.QueryFailed) as e:
                sql_error = str(e)
                audit.log_action(conn, auth.current_user(), "sql_query_rejected", None, f"{sql_text[:300]!r} -- {e}")
        ctx.update(
            sql_text=sql_text, sql_result=sql_result, sql_error=sql_error,
            sql_preview_limit=sql_query_tool.PREVIEW_ROW_LIMIT,
            export_urls=({fmt: url_for("overview_sql_export", fmt=fmt, sql=sql_text) for fmt in ("csv", "xlsx", "json")}
                         if sql_text.strip() and sql_result is not None else {}),
        )

    return render_template("overview.html", **ctx)


@app.route("/overview/students.<fmt>")
@auth.role_required("admin")
def overview_students_export(fmt):
    if fmt not in ("csv", "xlsx", "html", "pdf"):
        return "Unsupported format.", 400
    conn = get_conn()
    start_date, end_date, range_label = _date_range_from_args()
    onboarding = analytics.fetch_student_onboarding(conn, start_date, end_date)
    cols = ["date", "count"]
    out_rows = [[d["date"], d["count"]] for d in onboarding["daily"]]
    audit.log_action(conn, auth.current_user(), "overview_export", "students", fmt)
    title = f"New Students -- {range_label}"
    if fmt == "csv":
        return exporters.csv_response(cols, out_rows, "new_students_daily")
    if fmt == "xlsx":
        return exporters.xlsx_response(cols, out_rows, "new_students_daily")
    if fmt == "html":
        return exporters.html_export_response(title, cols, out_rows, brand_kit.colors(), "new_students_daily")
    return exporters.pdf_export_response(title, cols, out_rows, brand_kit.colors(), "new_students_daily")


@app.route("/overview/content.<fmt>")
@auth.role_required("admin")
def overview_content_export(fmt):
    if fmt not in ("csv", "xlsx", "html", "pdf"):
        return "Unsupported format.", 400
    conn = get_conn()
    start_date, end_date, range_label = _date_range_from_args()
    growth = analytics.fetch_content_growth(conn, start_date, end_date)
    q = request.args.get("q", "").strip()
    filtered = exporters.filter_rows(growth["rows"], q, ["subject", "chapter_label", "qtype", "source_file", "content_owner"])
    cols = ["logged_at", "qtype", "course", "level", "subject", "chapter_label", "question_count", "source_file", "content_owner", "note"]
    out_rows = [[r.get(c) for c in cols] for r in filtered]
    audit.log_action(conn, auth.current_user(), "overview_export", "content_growth", fmt)
    title = f"New Questions Added -- {range_label}"
    if fmt == "csv":
        return exporters.csv_response(cols, out_rows, "content_growth")
    if fmt == "xlsx":
        return exporters.xlsx_response(cols, out_rows, "content_growth")
    if fmt == "html":
        return exporters.html_export_response(title, cols, out_rows, brand_kit.colors(), "content_growth")
    return exporters.pdf_export_response(title, cols, out_rows, brand_kit.colors(), "content_growth")


@app.route("/overview/performance.<fmt>")
@auth.role_required("admin")
def overview_performance_export(fmt):
    if fmt not in ("csv", "xlsx", "html", "pdf"):
        return "Unsupported format.", 400
    conn = get_conn()
    perf_course = request.args.get("perf_course") or None
    perf_level = request.args.get("perf_level") or None
    min_attempts = request.args.get("min_attempts", 5, type=int)
    top = analytics.fetch_top_performers(conn, course=perf_course, level=perf_level, min_attempts=min_attempts, limit=100)
    cols = ["display_name", "username", "attempted", "correct", "accuracy_pct"]
    out_rows = [[r.get(c) for c in cols] for r in top]
    audit.log_action(conn, auth.current_user(), "overview_export", "top_performers", fmt)
    title = "Top Performing Students"
    if fmt == "csv":
        return exporters.csv_response(cols, out_rows, "top_performers")
    if fmt == "xlsx":
        return exporters.xlsx_response(cols, out_rows, "top_performers")
    if fmt == "html":
        return exporters.html_export_response(title, cols, out_rows, brand_kit.colors(), "top_performers")
    return exporters.pdf_export_response(title, cols, out_rows, brand_kit.colors(), "top_performers")


@app.route("/overview/faculty.<fmt>")
@auth.role_required("admin")
def overview_faculty_export(fmt):
    if fmt not in ("csv", "xlsx", "html", "pdf"):
        return "Unsupported format.", 400
    conn = get_conn()
    roster = analytics.fetch_faculty_roster(conn, manage_bots.load_bots())
    cols = ["display_name", "tenant_id", "onboarding_fee_paid", "onboarding_fee_amount_inr", "content_scope",
            "linked_bots", "mcq_contributed", "descriptive_contributed", "total_interactions",
            "unique_users_approx", "mcq_shown", "mcq_answered", "mcq_accuracy_pct"]
    out_rows = [[r.get(c) for c in cols] for r in roster]
    audit.log_action(conn, auth.current_user(), "overview_export", "faculty_roster", fmt)
    title = "Faculty Roster"
    if fmt == "csv":
        return exporters.csv_response(cols, out_rows, "faculty_roster")
    if fmt == "xlsx":
        return exporters.xlsx_response(cols, out_rows, "faculty_roster")
    if fmt == "html":
        return exporters.html_export_response(title, cols, out_rows, brand_kit.colors(), "faculty_roster")
    return exporters.pdf_export_response(title, cols, out_rows, brand_kit.colors(), "faculty_roster")


@app.route("/overview/sql.<fmt>")
@auth.role_required("admin")
def overview_sql_export(fmt):
    """Re-runs the exact query text from ?sql= (never caches the preview's
    result) at the export ceiling (sql_query_tool.EXPORT_ROW_LIMIT, higher
    than the on-screen preview) -- same stateless re-run pattern every
    other export route on this portal already follows. Read-only guarantee
    is enforced inside sql_query_tool itself, not here -- see that
    module's own docstring."""
    if fmt not in ("csv", "xlsx", "json"):
        return "Unsupported format -- use .csv, .xlsx, or .json", 400
    sql_text = request.args.get("sql", "")
    conn = get_conn()
    try:
        result = sql_query_tool.run_query_for_export(sql_text)
    except (sql_query_tool.QueryRejected, sql_query_tool.QueryFailed) as e:
        audit.log_action(conn, auth.current_user(), "sql_query_rejected", None, f"{sql_text[:300]!r} -- {e}")
        return f"Query error: {e}", 400
    audit.log_action(conn, auth.current_user(), "sql_query_export", None, f"{fmt} -- {sql_text[:500]}")
    columns, rows = result["columns"], result["rows"]
    if fmt == "csv":
        return exporters.csv_response(columns, rows, "sql_query_result")
    if fmt == "xlsx":
        return exporters.xlsx_response(columns, rows, "sql_query_result")
    return exporters.json_response(columns, rows, "sql_query_result")


# ---------------------------------------------------------------------------
# BOTS -- status, restart, logs
# ---------------------------------------------------------------------------
@app.route("/bots")
@auth.role_required("admin")
def bots_status():
    conn = get_conn()
    bots = manage_bots.load_bots()
    heartbeats = analytics.fetch_heartbeats(conn)
    rows = []
    for b in bots:
        bot_id = b["bot_id"]
        proc = manage_bots.is_running(bot_id, manage_bots.resolve_script_path(b))
        hb = heartbeats.get(bot_id)
        rows.append({
            "bot_id": bot_id,
            "kind": b["kind"],
            "display_name": b["display_name"],
            "config_status": b.get("status", "unknown"),
            "running": bool(proc),
            "pid": proc.pid if proc else None,
            "heartbeat_age": int(hb["age_seconds"]) if hb else None,
            "online": bool(hb and hb["online"]),
            "has_log": (manage_bots.LOG_DIR / f"{bot_id}.log").exists(),
        })
    backup_summary = backup_status.fetch_backup_summary(conn)
    return render_template("bots.html", rows=rows, backup=backup_summary)


@app.route("/bots/<bot_id>/restart", methods=["POST"])
@auth.role_required("admin")
def bots_restart(bot_id):
    bots_by_id = {b["bot_id"]: b for b in manage_bots.load_bots()}
    bot = bots_by_id.get(bot_id)
    conn = get_conn()
    if not bot:
        flash(f"Unknown bot_id '{bot_id}'.", "error")
        audit.log_action(conn, auth.current_user(), "bot_restart", bot_id, "failed: unknown bot_id")
        return redirect(url_for("bots_status"))

    try:
        manage_bots.restart_bot(bot)
        flash(f"Restarted {bot['display_name']} ({bot_id}).", "success")
        audit.log_action(conn, auth.current_user(), "bot_restart", bot_id, "ok")
    except Exception as e:
        flash(f"Restart failed for {bot_id}: {e}", "error")
        audit.log_action(conn, auth.current_user(), "bot_restart", bot_id, f"failed: {e}")
    return redirect(url_for("bots_status"))


@app.route("/bots/<bot_id>/logs")
@auth.role_required("admin")
def bots_logs(bot_id):
    bots_by_id = {b["bot_id"]: b for b in manage_bots.load_bots()}
    bot = bots_by_id.get(bot_id)
    if not bot:
        return "Unknown bot_id.", 404

    log_path = manage_bots.LOG_DIR / f"{bot_id}.log"
    tail_n = request.args.get("lines", default=300, type=int)
    if log_path.exists():
        with open(log_path, encoding="utf-8", errors="replace") as f:
            all_lines = f.readlines()
        log_text = "".join(all_lines[-tail_n:])
        total_lines = len(all_lines)
    else:
        log_text = "(no log file yet -- this bot may never have been started)"
        total_lines = 0

    return render_template(
        "bot_logs.html", bot=bot, log_text=log_text, log_path=str(log_path),
        tail_n=tail_n, total_lines=total_lines,
    )


# ---------------------------------------------------------------------------
# DATA EXPORT -- any DB table, straight to json/csv/xlsx (Pranav, 2026-08-11:
# "download any tables in a json or csv or xlsx file directly from any
# Database tables"). Blanket access, no table scoping (his confirmed
# choice, 2026-08-11 -- single-admin login is the only gate today; RBAC
# later can scope this per-role without a redesign).
# ---------------------------------------------------------------------------
def get_all_table_names(conn) -> list:
    rows = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
    ).fetchall()
    return [r[0] for r in rows]


@app.route("/export")
@auth.role_required("admin")
def data_export_index():
    conn = get_conn()
    tables = []
    for name in get_all_table_names(conn):
        # name comes only from sqlite_master's own enumeration above, never
        # from request input -- safe to interpolate into SQL as a quoted
        # identifier (Python's DB-API has no separate placeholder syntax
        # for identifiers, only values).
        count = conn.execute(f'SELECT COUNT(*) FROM "{name}"').fetchone()[0]
        tables.append({"name": name, "row_count": count})
    return render_template("data_export.html", tables=tables)


@app.route("/export/<table_name>.<fmt>")
@auth.role_required("admin")
def export_table(table_name, fmt):
    conn = get_conn()
    if table_name not in set(get_all_table_names(conn)):
        return "Unknown table.", 404
    if fmt not in ("json", "csv", "xlsx"):
        return "Unsupported format -- use .json, .csv, or .xlsx", 400

    cursor = conn.execute(f'SELECT * FROM "{table_name}"')
    columns, rows = exporters.rows_from_cursor(cursor)
    audit.log_action(conn, auth.current_user(), "table_export", table_name, fmt)

    if fmt == "json":
        return exporters.json_response(columns, rows, table_name)
    if fmt == "csv":
        return exporters.csv_response(columns, rows, table_name)
    return exporters.xlsx_response(columns, rows, table_name)


# ---------------------------------------------------------------------------
# ANALYTICS > Student Master -- paginated/filterable, exportable, and the
# bulk "send performance report" action (Pranav, 2026-08-11: student
# master data visible "as per his wish," plus sending the existing
# per-student report to one or many students at once).
# ---------------------------------------------------------------------------
STUDENT_MASTER_FILTER_FIELDS = ["telegram_user_id", "display_name", "username", "email", "mobile_number", "faculty", "courses"]


def _get_student_master_rows(conn) -> list:
    return analytics.fetch_student_master(conn, manage_bots.load_bots())


@app.route("/analytics/students")
@auth.role_required("admin")
def analytics_students():
    conn = get_conn()
    all_rows = _get_student_master_rows(conn)
    q = request.args.get("q", "").strip()
    filtered = exporters.filter_rows(all_rows, q, STUDENT_MASTER_FILTER_FIELDS)
    page = request.args.get("page", 1, type=int)
    pg = exporters.paginate(filtered, page, per_page=25)
    export_urls = {fmt: url_for("analytics_students_export", fmt=fmt, q=q) for fmt in ("csv", "xlsx", "html", "pdf")}
    return render_template(
        "analytics_students.html", rows=pg["items"], pagination=pg, filter_query=q,
        total_filtered=len(filtered), total_all=len(all_rows), export_urls=export_urls,
    )


def _student_master_export_columns():
    return ["telegram_user_id", "display_name", "username", "email", "mobile_number",
            "faculty", "courses", "first_seen_at", "last_seen_at"]


def _student_master_export_rows(rows):
    cols = _student_master_export_columns()
    out = [
        [r["telegram_user_id"], r["display_name"], r.get("username"), r.get("email"), r.get("mobile_number"),
         "; ".join(r.get("faculty") or []), "; ".join(r.get("courses") or []),
         r.get("first_seen_at"), r.get("last_seen_at")]
        for r in rows
    ]
    return cols, out


@app.route("/analytics/students.<fmt>")
@auth.role_required("admin")
def analytics_students_export(fmt):
    if fmt not in ("csv", "xlsx", "html", "pdf"):
        return "Unsupported format.", 400
    conn = get_conn()
    all_rows = _get_student_master_rows(conn)
    q = request.args.get("q", "").strip()
    filtered = exporters.filter_rows(all_rows, q, STUDENT_MASTER_FILTER_FIELDS)
    cols, out_rows = _student_master_export_rows(filtered)
    audit.log_action(conn, auth.current_user(), "analytics_export", "student_master", fmt)
    if fmt == "csv":
        return exporters.csv_response(cols, out_rows, "student_master")
    if fmt == "xlsx":
        return exporters.xlsx_response(cols, out_rows, "student_master")
    if fmt == "html":
        return exporters.html_export_response("Student Master", cols, out_rows, brand_kit.colors(), "student_master")
    return exporters.pdf_export_response("Student Master", cols, out_rows, brand_kit.colors(), "student_master")


@app.route("/analytics/students/send-report", methods=["POST"])
@auth.role_required("admin")
def analytics_students_send_report():
    """Sends each selected student their OWN existing performance report
    (the same PDF generate_student_report.py already produces), ONLY to a
    student's already echo-confirmed email on file (Pranav's confirmed
    choice, 2026-08-11 -- never guessed/typed in for them here). A student
    with no confirmed email is reported as skipped, never silently
    dropped. Sent from the admin portal's own dedicated address
    ('reports@1lavya.com', bots.json's 1lavya-admin-portal entry) -- an
    honest label, not impersonating whichever bot the student happens to
    use, since this send is admin-triggered, not bot-triggered."""
    conn = get_conn()
    selected = request.form.getlist("telegram_user_id")
    results = []
    for uid_str in selected:
        try:
            uid = int(uid_str)
        except ValueError:
            continue
        row = conn.execute("SELECT email FROM students WHERE telegram_user_id=?", (uid,)).fetchone()
        if not row or not row[0]:
            results.append((uid, "skipped"))
            continue
        email = row[0]
        try:
            data_for_name = student_analytics.fetch_student_report_data(conn, uid)
            display_name = generate_student_report.display_name_for_student(data_for_name)
            pdf_bytes = generate_student_report.build_report_pdf(conn, uid)
            report_delivery.send_report_email(BOT_ID, email, pdf_bytes, display_name, "All-time")
            report_delivery.log_report_delivery(conn, uid, "All-time (admin-sent)", "email", email_status="sent")
            results.append((uid, "sent"))
        except Exception as e:
            report_delivery.log_report_delivery(conn, uid, "All-time (admin-sent)", "email",
                                                  email_status="failed", error_detail=str(e))
            results.append((uid, "failed"))

    sent = sum(1 for _, s in results if s == "sent")
    failed = sum(1 for _, s in results if s == "failed")
    skipped = sum(1 for _, s in results if s == "skipped")
    flash(f"Reports: {sent} sent, {failed} failed, {skipped} skipped (no confirmed email on file).",
          "success" if failed == 0 else "error")
    audit.log_action(conn, auth.current_user(), "bulk_report_send", f"{len(selected)} students",
                      f"sent={sent} failed={failed} skipped={skipped}")
    return redirect(url_for("analytics_students"))


# ---------------------------------------------------------------------------
# ANALYTICS > Bot-wise Usage Summary
# ---------------------------------------------------------------------------
BOT_SUMMARY_FILTER_FIELDS = ["bot_id", "display_name"]


def _get_bot_summary_rows(conn) -> list:
    summary = analytics.fetch_bot_summary(conn)
    bot_meta = {b["bot_id"]: b for b in manage_bots.load_bots()}
    rows = []
    for bot_id, s in summary.items():
        meta = bot_meta.get(bot_id, {})
        sh, eh = s.get("study_hub") or {}, s.get("exam_hub") or {}
        rows.append({
            "bot_id": bot_id, "display_name": meta.get("display_name", bot_id),
            "total_interactions": s["total_interactions"], "unique_users": s["unique_users"],
            "downloads": sh.get("file_download", 0), "searches": sh.get("search_query", 0) + sh.get("search_no_match", 0),
            "sessions": eh.get("sessions", 0), "mcq_shown": eh.get("mcq_shown", 0), "mcq_answered": eh.get("mcq_answered", 0),
            "mcq_accuracy_pct": eh.get("mcq_accuracy_pct"), "descriptive_shown": eh.get("descriptive_shown", 0),
            "last_seen_at": s.get("last_seen_at"),
        })
    rows.sort(key=lambda r: r["total_interactions"], reverse=True)
    return rows


@app.route("/analytics/bots")
@auth.role_required("admin")
def analytics_bots():
    conn = get_conn()
    all_rows = _get_bot_summary_rows(conn)
    q = request.args.get("q", "").strip()
    filtered = exporters.filter_rows(all_rows, q, BOT_SUMMARY_FILTER_FIELDS)
    page = request.args.get("page", 1, type=int)
    pg = exporters.paginate(filtered, page, per_page=25)
    export_urls = {fmt: url_for("analytics_bots_export", fmt=fmt, q=q) for fmt in ("csv", "xlsx", "html", "pdf")}
    return render_template("analytics_bots.html", rows=pg["items"], pagination=pg, filter_query=q,
                            total_filtered=len(filtered), export_urls=export_urls)


def _bot_summary_export_columns():
    return ["bot_id", "display_name", "total_interactions", "unique_users", "downloads", "searches",
            "sessions", "mcq_shown", "mcq_answered", "mcq_accuracy_pct", "descriptive_shown", "last_seen_at"]


@app.route("/analytics/bots.<fmt>")
@auth.role_required("admin")
def analytics_bots_export(fmt):
    if fmt not in ("csv", "xlsx", "html", "pdf"):
        return "Unsupported format.", 400
    conn = get_conn()
    all_rows = _get_bot_summary_rows(conn)
    q = request.args.get("q", "").strip()
    filtered = exporters.filter_rows(all_rows, q, BOT_SUMMARY_FILTER_FIELDS)
    cols = _bot_summary_export_columns()
    out_rows = [[r.get(c) for c in cols] for r in filtered]
    audit.log_action(conn, auth.current_user(), "analytics_export", "bot_summary", fmt)
    if fmt == "csv":
        return exporters.csv_response(cols, out_rows, "bot_usage_summary")
    if fmt == "xlsx":
        return exporters.xlsx_response(cols, out_rows, "bot_usage_summary")
    if fmt == "html":
        return exporters.html_export_response("Bot-wise Usage Summary", cols, out_rows, brand_kit.colors(), "bot_usage_summary")
    return exporters.pdf_export_response("Bot-wise Usage Summary", cols, out_rows, brand_kit.colors(), "bot_usage_summary")


# ---------------------------------------------------------------------------
# ANALYTICS > Faculty Report -- student-wise, with a per-student chapter
# drill-down (a separate small page, not an inline JS-expand row, so it
# reuses the same paginate/filter/export primitives as everything else).
# ---------------------------------------------------------------------------
FACULTY_REPORT_FILTER_FIELDS = ["telegram_user_id", "display_name"]


def _faculty_report_bot_ids() -> list:
    return [b["bot_id"] for b in manage_bots.load_bots() if b["kind"] in ("exam", "unified")]


def _get_faculty_report_rows(conn, bot_id: str) -> list:
    if not bot_id:
        return []
    return analytics.fetch_faculty_report(conn, [bot_id]).get(bot_id, [])


@app.route("/analytics/faculty-report")
@auth.role_required("admin")
def analytics_faculty_report():
    conn = get_conn()
    bot_ids = _faculty_report_bot_ids()
    bot_meta = {b["bot_id"]: b for b in manage_bots.load_bots()}
    selected_bot = request.args.get("bot_id") or (bot_ids[0] if bot_ids else None)
    all_rows = _get_faculty_report_rows(conn, selected_bot)
    q = request.args.get("q", "").strip()
    filtered = exporters.filter_rows(all_rows, q, FACULTY_REPORT_FILTER_FIELDS)
    page = request.args.get("page", 1, type=int)
    pg = exporters.paginate(filtered, page, per_page=25)
    export_urls = {
        fmt: url_for("analytics_faculty_report_export", fmt=fmt, q=q, bot_id=selected_bot)
        for fmt in ("csv", "xlsx", "html", "pdf")
    } if selected_bot else {}
    return render_template(
        "analytics_faculty_report.html", rows=pg["items"], pagination=pg, filter_query=q,
        bot_ids=bot_ids, bot_meta=bot_meta, selected_bot=selected_bot, total_filtered=len(filtered),
        export_urls=export_urls, filter_extra_fields=[("bot_id", selected_bot)] if selected_bot else [],
    )


@app.route("/analytics/faculty-report.<fmt>")
@auth.role_required("admin")
def analytics_faculty_report_export(fmt):
    if fmt not in ("csv", "xlsx", "html", "pdf"):
        return "Unsupported format.", 400
    conn = get_conn()
    selected_bot = request.args.get("bot_id")
    if not selected_bot:
        return "bot_id query param required.", 400
    all_rows = _get_faculty_report_rows(conn, selected_bot)
    q = request.args.get("q", "").strip()
    filtered = exporters.filter_rows(all_rows, q, FACULTY_REPORT_FILTER_FIELDS)
    cols = ["telegram_user_id", "display_name", "total_attempted", "total_correct", "accuracy_pct"]
    out_rows = [[r.get(c) for c in cols] for r in filtered]
    audit.log_action(conn, auth.current_user(), "analytics_export", f"faculty_report:{selected_bot}", fmt)
    filename = f"faculty_report_{selected_bot}"
    title = f"Faculty Report -- {selected_bot}"
    if fmt == "csv":
        return exporters.csv_response(cols, out_rows, filename)
    if fmt == "xlsx":
        return exporters.xlsx_response(cols, out_rows, filename)
    if fmt == "html":
        return exporters.html_export_response(title, cols, out_rows, brand_kit.colors(), filename)
    return exporters.pdf_export_response(title, cols, out_rows, brand_kit.colors(), filename)


@app.route("/analytics/faculty-report/<bot_id>/<int:telegram_user_id>/chapters")
@auth.role_required("admin")
def analytics_faculty_report_chapters(bot_id, telegram_user_id):
    conn = get_conn()
    rows = _get_faculty_report_rows(conn, bot_id)
    student = next((r for r in rows if r["telegram_user_id"] == telegram_user_id), None)
    if not student:
        return "Student not found for this bot.", 404
    page = request.args.get("page", 1, type=int)
    pg = exporters.paginate(student["chapters"], page, per_page=25)
    return render_template("analytics_faculty_chapters.html", student=student, rows=pg["items"], pagination=pg, bot_id=bot_id)


# ---------------------------------------------------------------------------
# FACULTY COMPREHENSIVE REPORT -- added 2026-08-14 (Pranav: a full per-
# faculty, any-date-range report -- content availability across every
# subject/level live for them, chapter-wise practice, student-wise
# performance, the last 7 days student-wise, a student x chapter
# breakdown, and question-wise difficulty analysis, downloadable as
# PDF/XLSX/HTML and emailable straight to the faculty). Distinct from the
# existing "Analytics > Faculty Report" above (analytics_faculty_report,
# one-bot-at-a-time student list + chapter drill-down) -- this is the
# bigger, multi-section, whole-tenant version. See
# telegram/admin_portal/faculty_report.py for the full query/render layer;
# this section is routing only, same thin-route discipline as every other
# view in this file.
# ---------------------------------------------------------------------------
@app.route("/reports/faculty")
@auth.role_required("admin")
def faculty_report_view():
    conn = get_conn()
    bots = manage_bots.load_bots()
    tenants = faculty_report.list_reportable_tenants(conn, bots)
    tenant_ids = [t["tenant_id"] for t in tenants]
    requested_tenant = request.args.get("tenant_id")
    selected_tenant = requested_tenant if requested_tenant in tenant_ids else (tenant_ids[0] if tenant_ids else None)

    start_date, end_date, range_label = _date_range_from_args()
    preset = _current_preset()

    data = faculty_report.build_report(conn, selected_tenant, bots, start_date, end_date) if selected_tenant else None

    range_urls = {p: url_for("faculty_report_view", tenant_id=selected_tenant, preset=p) for p in RANGE_PRESETS}
    export_args = {} if preset != "custom" else {"from": start_date, "to": end_date}
    export_urls = {
        fmt: url_for("faculty_report_export", tenant_id=selected_tenant, fmt=fmt, preset=preset, **export_args)
        for fmt in ("pdf", "xlsx", "html")
    } if selected_tenant else {}

    return render_template(
        "faculty_full_report.html", tenants=tenants, selected_tenant=selected_tenant, data=data,
        range_label=range_label, range_urls=range_urls, range_presets=RANGE_PRESETS, preset=preset,
        start_date=start_date, end_date=end_date, export_urls=export_urls,
    )


@app.route("/reports/faculty/<tenant_id>.<fmt>")
@auth.role_required("admin")
def faculty_report_export(tenant_id, fmt):
    if fmt not in ("pdf", "xlsx", "html"):
        return "Unsupported format -- use .pdf, .xlsx, or .html", 400
    conn = get_conn()
    bots = manage_bots.load_bots()
    start_date, end_date, _ = _date_range_from_args()
    try:
        data = faculty_report.build_report(conn, tenant_id, bots, start_date, end_date)
    except ValueError:
        return "Unknown tenant_id.", 404

    audit.log_action(conn, auth.current_user(), "faculty_report_export", tenant_id, fmt)
    filename = f"faculty_report_{tenant_id}_{start_date or 'all'}_{end_date or 'all'}"

    if fmt == "html":
        faculty_report.log_report_delivery(conn, tenant_id, data["range_label"], "download:html", "downloaded")
        return Response(
            faculty_report.render_full_report_html(data), mimetype="text/html",
            headers={"Content-Disposition": f'attachment; filename="{filename}.html"'},
        )
    if fmt == "pdf":
        faculty_report.log_report_delivery(conn, tenant_id, data["range_label"], "download:pdf", "downloaded")
        return Response(
            faculty_report.build_report_pdf(data), mimetype="application/pdf",
            headers={"Content-Disposition": f'attachment; filename="{filename}.pdf"'},
        )
    faculty_report.log_report_delivery(conn, tenant_id, data["range_label"], "download:xlsx", "downloaded")
    return Response(
        faculty_report.build_report_xlsx(data),
        mimetype="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": f'attachment; filename="{filename}.xlsx"'},
    )


@app.route("/reports/faculty/<tenant_id>/email", methods=["POST"])
@auth.role_required("admin")
def faculty_report_email(tenant_id):
    conn = get_conn()
    bots = manage_bots.load_bots()
    to_email = request.form.get("email", "").strip()
    start_date = request.form.get("start_date") or None
    end_date = request.form.get("end_date") or None
    preset = request.form.get("preset") or "custom"
    redirect_args = {"tenant_id": tenant_id, "preset": preset}
    if preset == "custom":
        redirect_args.update({"from": start_date, "to": end_date})

    if not to_email or "@" not in to_email:
        flash("Enter a valid email address to send the report to.", "error")
        return redirect(url_for("faculty_report_view", **redirect_args))

    range_label = None
    try:
        data = faculty_report.build_report(conn, tenant_id, bots, start_date, end_date)
        range_label = data["range_label"]
        pdf_bytes = faculty_report.build_report_pdf(data)
        faculty_report.send_report_email(to_email, data, pdf_bytes)
        faculty_report.log_report_delivery(conn, tenant_id, range_label, to_email, "sent")
        flash(f"Report emailed to {to_email}.", "success")
        audit.log_action(conn, auth.current_user(), "faculty_report_email", tenant_id, f"sent to {to_email}")
    except Exception as e:
        faculty_report.log_report_delivery(conn, tenant_id, range_label, to_email, "failed", str(e))
        flash(f"Failed to send report: {e}", "error")
        audit.log_action(conn, auth.current_user(), "faculty_report_email", tenant_id, f"failed: {e}")

    return redirect(url_for("faculty_report_view", **redirect_args))


# ---------------------------------------------------------------------------
# MASTERS > Faculty Details -- added 2026-08-14 (Pranav's direct ask: "a
# faculty table where we can store the details of the faculty," confirmed
# as a DB table, not JSON -- see telegram/admin_portal/faculty_master.py
# for the full reasoning). Every tenant from tenants.json listed, joined
# to its faculty_master row (if any) -- an unentered faculty shows blank
# fields, not an error. Onboarding-fee status shown read-only (still
# sourced from tenants.json, never duplicated here).
# ---------------------------------------------------------------------------
@app.route("/masters/faculty")
@auth.role_required("admin")
def masters_faculty_list():
    conn = get_conn()
    rows = faculty_master.list_faculty_master(conn)
    return render_template("masters_faculty_list.html", rows=rows)


@app.route("/masters/faculty/<tenant_id>", methods=["GET", "POST"])
@auth.role_required("admin")
def masters_faculty_edit(tenant_id):
    conn = get_conn()
    all_tenants = faculty_master.load_tenants()
    if tenant_id not in all_tenants:
        return "Unknown tenant_id.", 404
    tenant = all_tenants[tenant_id]

    if request.method == "POST":
        contact_email = request.form.get("contact_email", "").strip() or None
        contact_phone = request.form.get("contact_phone", "").strip() or None
        notes = request.form.get("notes", "").strip() or None
        faculty_master.upsert_faculty_master(conn, tenant_id, contact_email, contact_phone, notes)
        audit.log_action(conn, auth.current_user(), "faculty_master_edit", tenant_id, "saved")
        flash(f"Saved details for {tenant.get('display_name', tenant_id)}.", "success")
        return redirect(url_for("masters_faculty_list"))

    master = faculty_master.get_faculty_master(conn, tenant_id) or {
        "tenant_id": tenant_id, "contact_email": None, "contact_phone": None, "notes": None,
        "created_at": None, "updated_at": None,
    }
    fee = tenant.get("onboarding_fee") or {}
    return render_template("masters_faculty_edit.html", tenant=tenant, tenant_id=tenant_id, master=master, fee=fee)


# ---------------------------------------------------------------------------
# ANALYTICS > Content Health -- flattened one row per issue
# ---------------------------------------------------------------------------
CONTENT_HEALTH_FILTER_FIELDS = ["file", "kind", "severity", "record_id", "field", "message"]


def _get_content_health_rows() -> list:
    out = []
    for r in analytics.fetch_content_health():
        short_path = Path(r["path"]).name
        for issue in r.get("issues", []):
            out.append({
                "file": short_path, "kind": r["kind"], "severity": issue["severity"],
                "record_id": issue.get("record_id"), "field": issue.get("field"), "message": issue["message"],
            })
    return out


@app.route("/analytics/content-health")
@auth.role_required("admin")
def analytics_content_health():
    all_rows = _get_content_health_rows()
    q = request.args.get("q", "").strip()
    filtered = exporters.filter_rows(all_rows, q, CONTENT_HEALTH_FILTER_FIELDS)
    page = request.args.get("page", 1, type=int)
    pg = exporters.paginate(filtered, page, per_page=25)
    error_count = sum(1 for r in all_rows if r["severity"] == "ERROR")
    warning_count = sum(1 for r in all_rows if r["severity"] == "WARNING")
    export_urls = {fmt: url_for("analytics_content_health_export", fmt=fmt, q=q) for fmt in ("csv", "xlsx", "html", "pdf")}
    return render_template(
        "analytics_content_health.html", rows=pg["items"], pagination=pg, filter_query=q,
        total_filtered=len(filtered), error_count=error_count, warning_count=warning_count, export_urls=export_urls,
    )


@app.route("/analytics/content-health.<fmt>")
@auth.role_required("admin")
def analytics_content_health_export(fmt):
    if fmt not in ("csv", "xlsx", "html", "pdf"):
        return "Unsupported format.", 400
    conn = get_conn()
    all_rows = _get_content_health_rows()
    q = request.args.get("q", "").strip()
    filtered = exporters.filter_rows(all_rows, q, CONTENT_HEALTH_FILTER_FIELDS)
    cols = CONTENT_HEALTH_FILTER_FIELDS
    out_rows = [[r.get(c) for c in cols] for r in filtered]
    audit.log_action(conn, auth.current_user(), "analytics_export", "content_health", fmt)
    if fmt == "csv":
        return exporters.csv_response(cols, out_rows, "content_health")
    if fmt == "xlsx":
        return exporters.xlsx_response(cols, out_rows, "content_health")
    if fmt == "html":
        return exporters.html_export_response("Content Health", cols, out_rows, brand_kit.colors(), "content_health")
    return exporters.pdf_export_response("Content Health", cols, out_rows, brand_kit.colors(), "content_health")


# ---------------------------------------------------------------------------
# ANALYTICS > Email Analytics -- report_deliveries, one row per attempt
# ---------------------------------------------------------------------------
EMAIL_ANALYTICS_FILTER_FIELDS = ["telegram_user_id", "display_name", "email", "criteria",
                                  "channels_requested", "email_status", "telegram_status", "error_detail"]


def _get_email_analytics_rows(conn) -> list:
    rows = conn.execute(
        """
        SELECT rd.delivery_id, rd.telegram_user_id,
               COALESCE(s.first_name || ' ' || COALESCE(s.last_name,''), s.username, 'Student ' || rd.telegram_user_id) AS display_name,
               s.email, rd.generated_at, rd.criteria, rd.channels_requested, rd.email_status, rd.telegram_status, rd.error_detail
        FROM report_deliveries rd LEFT JOIN students s ON s.telegram_user_id = rd.telegram_user_id
        ORDER BY rd.delivery_id DESC
        """
    ).fetchall()
    return [
        {
            "delivery_id": r[0], "telegram_user_id": r[1], "display_name": r[2], "email": r[3],
            "generated_at": r[4], "criteria": r[5], "channels_requested": r[6],
            "email_status": r[7], "telegram_status": r[8], "error_detail": r[9],
        }
        for r in rows
    ]


@app.route("/analytics/email")
@auth.role_required("admin")
def analytics_email():
    conn = get_conn()
    all_rows = _get_email_analytics_rows(conn)
    q = request.args.get("q", "").strip()
    filtered = exporters.filter_rows(all_rows, q, EMAIL_ANALYTICS_FILTER_FIELDS)
    page = request.args.get("page", 1, type=int)
    pg = exporters.paginate(filtered, page, per_page=25)
    sent_count = sum(1 for r in all_rows if r["email_status"] == "sent")
    failed_count = sum(1 for r in all_rows if r["email_status"] == "failed")
    export_urls = {fmt: url_for("analytics_email_export", fmt=fmt, q=q) for fmt in ("csv", "xlsx", "html", "pdf")}
    return render_template(
        "analytics_email.html", rows=pg["items"], pagination=pg, filter_query=q,
        total_filtered=len(filtered), sent_count=sent_count, failed_count=failed_count, total_all=len(all_rows),
        export_urls=export_urls,
    )


@app.route("/analytics/email.<fmt>")
@auth.role_required("admin")
def analytics_email_export(fmt):
    if fmt not in ("csv", "xlsx", "html", "pdf"):
        return "Unsupported format.", 400
    conn = get_conn()
    all_rows = _get_email_analytics_rows(conn)
    q = request.args.get("q", "").strip()
    filtered = exporters.filter_rows(all_rows, q, EMAIL_ANALYTICS_FILTER_FIELDS)
    cols = ["delivery_id", "telegram_user_id", "display_name", "email", "generated_at", "criteria",
            "channels_requested", "email_status", "telegram_status", "error_detail"]
    out_rows = [[r.get(c) for c in cols] for r in filtered]
    audit.log_action(conn, auth.current_user(), "analytics_export", "email_analytics", fmt)
    if fmt == "csv":
        return exporters.csv_response(cols, out_rows, "email_analytics")
    if fmt == "xlsx":
        return exporters.xlsx_response(cols, out_rows, "email_analytics")
    if fmt == "html":
        return exporters.html_export_response("Email Analytics", cols, out_rows, brand_kit.colors(), "email_analytics")
    return exporters.pdf_export_response("Email Analytics", cols, out_rows, brand_kit.colors(), "email_analytics")


# ---------------------------------------------------------------------------
# MCQ ISSUE REPORTS -- added 2026-08-13 (Pranav: "make sure that the issues
# report given by the student gets a place in the admin dashboard"). Reads
# mcq_issue_reports (telegram/bots/mcq_issue_flow.py, the "Report Issue in
# MCQ" flow) -- same read-only/paginated/filterable/exportable shape as
# every other Analytics view here. No status-editing UI yet (marking a
# report resolved/dismissed) -- not asked for; the generic "Data Export"
# page and direct SQL already cover that if needed sooner.
# ---------------------------------------------------------------------------
ISSUE_REPORTS_FILTER_FIELDS = ["human_id", "mcq_id", "display_name", "course", "level", "subject",
                                "chapter_label", "category", "description", "status", "bot_id"]


def _get_issue_reports_rows(conn) -> list:
    rows = conn.execute(
        """
        SELECT ir.report_id, ir.bot_id, ir.telegram_user_id,
               COALESCE(s.first_name || ' ' || COALESCE(s.last_name,''), s.username, 'Student ' || ir.telegram_user_id) AS display_name,
               ir.mcq_id, ir.human_id, ir.course, ir.level, ir.subject, ir.chapter_label,
               ir.category, ir.description, ir.status, ir.created_at
        FROM mcq_issue_reports ir LEFT JOIN students s ON s.telegram_user_id = ir.telegram_user_id
        ORDER BY ir.report_id DESC
        """
    ).fetchall()
    return [
        {
            "report_id": r[0], "bot_id": r[1], "telegram_user_id": r[2], "display_name": r[3],
            "mcq_id": r[4], "human_id": r[5], "course": r[6], "level": r[7], "subject": r[8],
            "chapter_label": r[9], "category": r[10], "description": r[11], "status": r[12], "created_at": r[13],
        }
        for r in rows
    ]


@app.route("/analytics/issue-reports")
@auth.role_required("admin")
def analytics_issue_reports():
    conn = get_conn()
    all_rows = _get_issue_reports_rows(conn)
    q = request.args.get("q", "").strip()
    filtered = exporters.filter_rows(all_rows, q, ISSUE_REPORTS_FILTER_FIELDS)
    page = request.args.get("page", 1, type=int)
    pg = exporters.paginate(filtered, page, per_page=25)
    open_count = sum(1 for r in all_rows if r["status"] == "open")
    export_urls = {fmt: url_for("analytics_issue_reports_export", fmt=fmt, q=q) for fmt in ("csv", "xlsx", "html", "pdf")}
    return render_template(
        "analytics_issue_reports.html", rows=pg["items"], pagination=pg, filter_query=q,
        total_filtered=len(filtered), open_count=open_count, total_all=len(all_rows),
        export_urls=export_urls,
    )


@app.route("/analytics/issue-reports.<fmt>")
@auth.role_required("admin")
def analytics_issue_reports_export(fmt):
    if fmt not in ("csv", "xlsx", "html", "pdf"):
        return "Unsupported format.", 400
    conn = get_conn()
    all_rows = _get_issue_reports_rows(conn)
    q = request.args.get("q", "").strip()
    filtered = exporters.filter_rows(all_rows, q, ISSUE_REPORTS_FILTER_FIELDS)
    cols = ["report_id", "bot_id", "telegram_user_id", "display_name", "mcq_id", "human_id", "course",
            "level", "subject", "chapter_label", "category", "description", "status", "created_at"]
    out_rows = [[r.get(c) for c in cols] for r in filtered]
    audit.log_action(conn, auth.current_user(), "analytics_export", "issue_reports", fmt)
    if fmt == "csv":
        return exporters.csv_response(cols, out_rows, "mcq_issue_reports")
    if fmt == "xlsx":
        return exporters.xlsx_response(cols, out_rows, "mcq_issue_reports")
    if fmt == "html":
        return exporters.html_export_response("MCQ Issue Reports", cols, out_rows, brand_kit.colors(), "mcq_issue_reports")
    return exporters.pdf_export_response("MCQ Issue Reports", cols, out_rows, brand_kit.colors(), "mcq_issue_reports")


# ---------------------------------------------------------------------------
# ACTIVITY LOG -- added 2026-08-17, Phase 1 of the logging build (see
# telegram/LOGGING-ARCHITECTURE.md). The ONE page a bot_admin role can
# reach at all -- role_required() below deliberately allows BOTH "admin"
# (sees every bot) and "bot_admin" (sees only their own, enforced by
# _scoped_bot_ids() below, never by role_required() itself, which only
# checks role membership, not per-resource scope).
# ---------------------------------------------------------------------------
ACTIVITY_LOG_FILTER_FIELDS = ["action", "action_detail", "handler_name", "error_summary", "bot_id"]


def _scoped_bot_ids():
    """None for a super-admin (fetch_activity_log() then applies NO bot_id
    filter at all); a real list (possibly empty) for a bot_admin --
    ALWAYS re-derived from the session's own allowed_bot_ids, never
    trusted from a request argument, so a bot_admin can never widen their
    own scope by editing a query string."""
    if auth.current_role() == "bot_admin":
        return auth.current_allowed_bot_ids() or []
    return None


def _get_activity_log_rows(conn):
    start_date, end_date, range_label = _date_range_from_args()
    requested_bot_id = request.args.get("bot_id", "").strip()
    scoped = _scoped_bot_ids()
    if scoped is not None:
        bot_ids = scoped  # bot_admin -- ignore any ?bot_id= request arg entirely, never let it widen scope
    elif requested_bot_id:
        bot_ids = [requested_bot_id]
    else:
        bot_ids = None
    telegram_user_id = request.args.get("telegram_user_id", type=int)
    action = request.args.get("action", "").strip() or None
    status = request.args.get("status", "").strip() or None
    rows = analytics.fetch_activity_log(
        conn, bot_ids=bot_ids, start_date=start_date, end_date=end_date,
        telegram_user_id=telegram_user_id, action=action, status=status,
    )
    return rows, start_date, end_date, range_label


@app.route("/logs/activity")
@auth.role_required("admin", "bot_admin")
def activity_log():
    conn = get_conn()
    rows, start_date, end_date, range_label = _get_activity_log_rows(conn)
    q = request.args.get("q", "").strip()
    filtered = exporters.filter_rows(rows, q, ACTIVITY_LOG_FILTER_FIELDS)
    page = request.args.get("page", 1, type=int)
    pg = exporters.paginate(filtered, page, per_page=50)
    error_count = sum(1 for r in rows if r["status"] == "error")
    scoped = _scoped_bot_ids()
    available_bot_ids = scoped if scoped is not None else analytics.fetch_activity_log_bot_ids(conn)
    # A bot_admin's own ?bot_id= is never actually consulted (see
    # _scoped_bot_ids() above -- their real scope always wins), but
    # echoing it back into the export link's URL is still confusing/
    # misleading UI even though it changes nothing functionally -- strip
    # it from what gets reflected into links for that role specifically.
    link_args = request.args.to_dict()
    if scoped is not None:
        link_args.pop("bot_id", None)
    export_urls = {fmt: url_for("activity_log_export", fmt=fmt, q=q, **link_args) for fmt in ("csv", "xlsx", "html", "pdf")}
    extra_fields = [(k, v) for k, v in link_args.items() if k not in ("q", "page")]
    return render_template(
        "activity_log.html", rows=pg["items"], pagination=pg, filter_query=q,
        total_filtered=len(filtered), error_count=error_count, total_all=len(rows),
        range_label=range_label, current_preset=_current_preset(),
        available_bot_ids=available_bot_ids, is_bot_admin=(scoped is not None),
        selected_bot_id=request.args.get("bot_id", ""),
        selected_action=request.args.get("action", ""), selected_status=request.args.get("status", ""),
        export_urls=export_urls, filter_extra_fields=extra_fields,
    )


@app.route("/logs/activity.<fmt>")
@auth.role_required("admin", "bot_admin")
def activity_log_export(fmt):
    if fmt not in ("csv", "xlsx", "html", "pdf"):
        return "Unsupported format.", 400
    conn = get_conn()
    rows, _start, _end, _label = _get_activity_log_rows(conn)
    q = request.args.get("q", "").strip()
    filtered = exporters.filter_rows(rows, q, ACTIVITY_LOG_FILTER_FIELDS)
    cols = ["activity_id", "correlation_id", "bot_id", "telegram_user_id", "conversation_id", "handler_kind",
            "action", "action_detail", "handler_name", "duration_ms", "status", "error_summary", "created_at"]
    out_rows = [[r.get(c) for c in cols] for r in filtered]
    audit.log_action(conn, auth.current_user(), "analytics_export", "activity_log", fmt)
    if fmt == "csv":
        return exporters.csv_response(cols, out_rows, "activity_log")
    if fmt == "xlsx":
        return exporters.xlsx_response(cols, out_rows, "activity_log")
    if fmt == "html":
        return exporters.html_export_response("Activity Log", cols, out_rows, brand_kit.colors(), "activity_log")
    return exporters.pdf_export_response("Activity Log", cols, out_rows, brand_kit.colors(), "activity_log")


# ---------------------------------------------------------------------------
# CONTENT > Course Catalog -- Course/Level/Subject-wise view of
# course_catalog (Pranav, 2026-08-11: "I also want to see the Course,
# Level and Subject wise the Course Catalog"). The single source of truth
# every MCQ/descriptive question's human_id is now derived from -- see
# telegram/tools/populate_course_catalog.py / generate_mcq_human_ids.py.
#
# Extended 2026-08-12 to 5 tabs, all sharing the same Course/Level/Subject
# picker (Pranav: "make sure all of my 4 catalogues are live and accurate
# under the url .../content/course-catalog... You may take help of a
# dropdown if directly writing is a bit difficult"): the original
# chapter/unit TAXONOMY view (kept, now one tab among several, not
# replaced -- nothing that worked before stops working) plus 4 new
# document/question-level views built on top of it -- see
# telegram/admin_portal/document_catalog.py for what each one actually
# queries and why. `catalogue` query param selects the tab; defaults to
# "study" per Pranav's own framing ("this catalog becomes the study
# materials catalogue").
# ---------------------------------------------------------------------------
COURSE_CATALOG_VIEWS = ("study", "exam", "revision", "questions", "taxonomy")
COURSE_CATALOG_VIEW_LABELS = {
    "study": "Study Materials", "exam": "Exam Materials", "revision": "Revision Material",
    "questions": "Question Bank", "taxonomy": "Chapter Taxonomy",
}
COURSE_CATALOG_FILTER_FIELDS = {
    "taxonomy": ["chapter_no", "chapter_name", "chapter_name_short", "unit_no", "unit_name"],
    "study": ["chapter_no", "chapter_name", "chapter_name_short", "status"],
    "revision": ["chapter_no", "chapter_name", "chapter_name_short", "status"],
    "exam": ["file_name", "native_title", "paper_type", "session", "set_label", "doc_type"],
    "questions": ["chapter_no", "chapter_name", "chapter_name_short"],
}
COURSE_CATALOG_EXPORT_COLS = {
    "taxonomy": ["paper_no", "chapter_no", "chapter_name", "chapter_name_short", "unit_no", "unit_name", "unit_name_short", "source"],
    "study": ["chapter_no", "chapter_name", "chapter_name_short", "file_count", "file_names", "total_pages", "status"],
    "revision": ["chapter_no", "chapter_name", "chapter_name_short", "file_count", "file_names", "total_pages", "status"],
    "exam": ["file_name", "native_title", "paper_type", "session", "set_label", "doc_type", "page_count"],
    "questions": ["chapter_no", "chapter_name", "chapter_name_short", "mcq_count", "descriptive_count", "total_count"],
}


def _format_paper_no(paper_no: str) -> str:
    """'1' -> 'P01', '7A' -> 'P7A' -- same rule as generate_mcq_human_ids.py's
    own _format_paper(), duplicated (not imported, telegram/tools/ isn't
    normally on this app's import path) since both are simple/stable enough
    not to need a shared module for one formatting rule."""
    return f"P{str(paper_no).zfill(2)}"


def _course_catalog_course_levels(conn) -> dict:
    """{course: [levels...]} actually present in course_catalog, in a
    stable Foundation->Inter->Final-ish order (by level_num)."""
    rows = conn.execute(
        "SELECT DISTINCT course, level, level_num FROM course_catalog ORDER BY course, level_num"
    ).fetchall()
    out = {}
    for course, level, _ in rows:
        out.setdefault(course, []).append(level)
    return out


def _course_catalog_rows(conn, view, course, level, subject) -> list:
    """Dispatches to the right query for the selected tab. Every row dict
    also gets 'chapter_no'/'chapter_name' keys where applicable so the
    template can render a uniform header regardless of view."""
    if view == "taxonomy":
        rows = conn.execute(
            "SELECT paper_no, chapter_no, chapter_name, chapter_name_short, unit_no, unit_name, unit_name_short, source "
            "FROM course_catalog WHERE course=? AND level=? AND subject=? ORDER BY chapter_no, unit_no",
            (course, level, subject),
        ).fetchall()
        return [
            {"paper_no": r[0], "paper_display": _format_paper_no(r[0]), "chapter_no": r[1], "chapter_name": r[2],
             "chapter_name_short": r[3], "unit_no": r[4], "unit_name": r[5], "unit_name_short": r[6], "source": r[7]}
            for r in rows
        ]
    if view == "study":
        rows = document_catalog.study_materials_rows(conn, course, level, subject)
    elif view == "revision":
        rows = document_catalog.revision_material_rows(conn, course, level, subject)
    elif view == "exam":
        rows = document_catalog.exam_materials_rows(course, level, subject)
    elif view == "questions":
        rows = document_catalog.question_bank_rows(conn, course, level, subject)
    else:
        rows = []
    # file_names/units are lists in document_catalog's output -- flatten to
    # a display string here so filter_rows() (which does substring matching
    # on stringified values) and the export writers both work unmodified.
    for r in rows:
        if "file_names" in r:
            r["file_names"] = ", ".join(r["file_names"]) if r["file_names"] else "—"
        if "units" in r:
            r["units"] = ", ".join(r["units"]) if r["units"] else None
    return rows


@app.route("/content/course-catalog")
@auth.role_required("admin")
def course_catalog():
    # A URL-supplied course/level/subject that isn't actually a valid
    # option (a typo, or "Accounting" when the real CA Inter subject is
    # "Advanced Accounting") falls back to the first real option instead
    # of silently querying a value with zero matching rows and rendering
    # an empty "No chapters match" table with no explanation -- found
    # 2026-08-12 testing Pranav's own example URL, which named a subject
    # that only exists at a different level.
    conn = get_conn()
    course_levels = _course_catalog_course_levels(conn)
    courses = list(course_levels.keys())
    requested_course = request.args.get("course")
    selected_course = requested_course if requested_course in courses else (courses[0] if courses else None)

    levels = course_levels.get(selected_course, [])
    requested_level = request.args.get("level")
    selected_level = requested_level if requested_level in levels else (levels[0] if levels else None)

    subjects = []
    if selected_course and selected_level:
        subjects = [
            r[0] for r in conn.execute(
                "SELECT DISTINCT subject FROM course_catalog WHERE course=? AND level=? ORDER BY subject",
                (selected_course, selected_level),
            ).fetchall()
        ]
    requested_subject = request.args.get("subject")
    selected_subject = requested_subject if requested_subject in subjects else (subjects[0] if subjects else None)

    view = request.args.get("catalogue", "study")
    if view not in COURSE_CATALOG_VIEWS:
        view = "study"

    all_rows = []
    if selected_course and selected_level and selected_subject:
        all_rows = _course_catalog_rows(conn, view, selected_course, selected_level, selected_subject)

    q = request.args.get("q", "").strip()
    filtered = exporters.filter_rows(all_rows, q, COURSE_CATALOG_FILTER_FIELDS[view])
    page = request.args.get("page", 1, type=int)
    pg = exporters.paginate(filtered, page, per_page=50)

    filter_extra = [("course", selected_course), ("level", selected_level), ("subject", selected_subject), ("catalogue", view)]
    export_urls = {
        fmt: url_for("course_catalog_export", fmt=fmt, q=q, course=selected_course, level=selected_level,
                      subject=selected_subject, catalogue=view)
        for fmt in ("csv", "xlsx", "html", "pdf")
    } if (selected_course and selected_level and selected_subject) else {}

    tab_urls = {
        v: url_for("course_catalog", course=selected_course, level=selected_level, subject=selected_subject, catalogue=v)
        for v in COURSE_CATALOG_VIEWS
    }

    return render_template(
        "course_catalog.html", rows=pg["items"], pagination=pg, filter_query=q,
        courses=courses, levels=levels, subjects=subjects,
        selected_course=selected_course, selected_level=selected_level, selected_subject=selected_subject,
        total_filtered=len(filtered), export_urls=export_urls, filter_extra_fields=filter_extra,
        view=view, views=COURSE_CATALOG_VIEWS, view_labels=COURSE_CATALOG_VIEW_LABELS, tab_urls=tab_urls,
    )


@app.route("/content/course-catalog.<fmt>")
@auth.role_required("admin")
def course_catalog_export(fmt):
    if fmt not in ("csv", "xlsx", "html", "pdf"):
        return "Unsupported format.", 400
    course, level, subject = request.args.get("course"), request.args.get("level"), request.args.get("subject")
    if not (course and level and subject):
        return "course, level, and subject query params are all required.", 400
    view = request.args.get("catalogue", "study")
    if view not in COURSE_CATALOG_VIEWS:
        view = "study"
    conn = get_conn()
    all_rows = _course_catalog_rows(conn, view, course, level, subject)
    q = request.args.get("q", "").strip()
    filtered = exporters.filter_rows(all_rows, q, COURSE_CATALOG_FILTER_FIELDS[view])
    cols = COURSE_CATALOG_EXPORT_COLS[view]
    out_rows = [[r.get(c) for c in cols] for r in filtered]
    audit.log_action(conn, auth.current_user(), "analytics_export", f"course_catalog:{view}:{course}/{level}/{subject}", fmt)
    filename = f"course_catalog_{view}_{course}_{level}_{subject}".replace(" ", "_")
    title = f"{COURSE_CATALOG_VIEW_LABELS[view]} -- {course} {level} {subject}"
    if fmt == "csv":
        return exporters.csv_response(cols, out_rows, filename)
    if fmt == "xlsx":
        return exporters.xlsx_response(cols, out_rows, filename)
    if fmt == "html":
        return exporters.html_export_response(title, cols, out_rows, brand_kit.colors(), filename)
    return exporters.pdf_export_response(title, cols, out_rows, brand_kit.colors(), filename)


def _heartbeat_loop(interval_seconds: int = 120):
    """Same technique as dashboard_server.py's own _heartbeat_loop() -- this
    is a plain Flask/WSGI process, no python-telegram-bot Application/
    JobQueue to hang a periodic heartbeat off of, so a daemon background
    thread does the same job. Without this, manage_bots.py status/the
    watcher/the dashboard would never see this process as online."""
    conn = platform_db.get_connection()
    platform_db.init_schema(conn)
    pid = os.getpid()
    started_at = platform_db.now()
    while True:
        platform_db.send_heartbeat(conn, BOT_ID, pid, started_at)
        time.sleep(interval_seconds)


def main():
    threading.Thread(target=_heartbeat_loop, daemon=True).start()
    port = int(os.environ.get("ADMIN_PORTAL_PORT", "8788"))
    app.logger.info(f"1LAVYA Admin Portal starting on http://127.0.0.1:{port}/")
    app.run(host="127.0.0.1", port=port, debug=False, threaded=True)


if __name__ == "__main__":
    main()
