"""
telegram/admin_portal/app.py -- 1LAVYA Admin Portal (2026-08-11, Phase 4 of
the branding-kit -> report-pipeline -> leaderboard -> admin-portal roadmap)
--------------------------------------------------------------------------------
FOUNDATION TIER ONLY (Pranav's confirmed build order, 2026-08-11: "Flask
migration + sidebar shell + login + Bot Status/Restart + Bot-wise Logs
first... then Analytics tabs... then Masters... then Leaderboard/Catalog
edits last"). This is that first tier. Everything else on his module list
(Analytics, Masters display/editing, Faculty/Bot addition, Question
Catalog edits, Leaderboard edits, student-profile<->leaderboard mappings,
Email analytics, module-wise RBAC) is a FOLLOW-UP phase, each built,
smoke-tested, and handed off for his confirmation before the next one --
see telegram/admin_portal/README.md for the live status of what's built
vs. still coming, and CLAUDE.md section 11 for the full decision trail.

RUNS ALONSIDE the existing telegram/tools/dashboard_server.py (port 8787),
not replacing it yet -- that dashboard's Analytics content (Student
Master, Faculty Report, Content Health, Bot-wise Usage, Message Volume)
stays the working, live source for Analytics until the Analytics tab in
THIS app is actually built and can absorb it. This app runs on port 8788
by default. Once Analytics (and everything else) has moved over, the old
dashboard retires -- not before, so nothing Pranav currently relies on
breaks mid-transition.

AUTH: single-admin login (see auth.py's own docstring for why every route
is wrapped in role_required(), not a bare login_required(), even though
only one role exists today) -- credentials in telegram/.env, generated by
set_password.py. SECRET_KEY signs the session cookie; there is no
"remember me" -- closing the browser or restarting this process
invalidates the session (Flask's default in-memory-signed-cookie
behavior), which is the right default for an internal ops tool with no
persistent-session requirement stated.

BOT RESTART calls telegram/tools/manage_bots.py's OWN restart_bot()
function directly (imported, not subprocessed) -- the exact same code
path `python manage_bots.py restart <id>` already uses from a terminal,
so this button can never drift from that script's own behavior. Blocking
(can take up to ~15-25s: manage_bots.py's GRACE_PERIOD_SECONDS=12s stop
wait, then a fresh start) -- the confirm dialog + a "Restarting..." button
state is enough UX for an internal tool used by one person at a time; no
async job queue built for this yet.
"""

import os
import sys
import time
import threading
from pathlib import Path
from urllib.parse import urlencode

from flask import Flask, render_template, request, redirect, url_for, session, flash
from dotenv import load_dotenv

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "telegram" / "database"))
sys.path.insert(0, str(REPO_ROOT / "telegram" / "tools"))
sys.path.insert(0, str(REPO_ROOT / "telegram" / "branding"))
sys.path.insert(0, str(Path(__file__).resolve().parent))

load_dotenv(REPO_ROOT / "telegram" / ".env")

import db as platform_db  # noqa: E402
import analytics  # noqa: E402
import manage_bots  # noqa: E402
import brand_kit  # noqa: E402
import auth  # noqa: E402
import audit  # noqa: E402
import exporters  # noqa: E402
import report_delivery  # noqa: E402 -- telegram/database/report_delivery.py
import student_analytics  # noqa: E402 -- telegram/database/student_analytics.py
import generate_student_report  # noqa: E402 -- telegram/tools/generate_student_report.py

app = Flask(__name__)
app.secret_key = os.environ.get("ADMIN_PORTAL_SECRET_KEY") or os.urandom(32)
if not os.environ.get("ADMIN_PORTAL_SECRET_KEY"):
    app.logger.warning(
        "ADMIN_PORTAL_SECRET_KEY not set in telegram/.env -- using a random key for this "
        "process only (every session invalidates on restart). Run set_password.py to fix."
    )

BOT_ID = "1lavya-admin-portal"   # this process's own bot_id, for its heartbeat -- see bots.json

# Sidebar structure -- built ONCE here (not hand-duplicated per template)
# so adding/graying a module is a one-line change picked up everywhere the
# sidebar renders. `enabled: False` items render as a "Soon" badge, not a
# link -- communicates the full intended shape of the portal even before
# every module is built (Pranav's "very scalable... each and everything
# should be able to be visible" ask), without pretending they work yet.
NAV_SECTIONS = [
    {"label": "Overview", "links": [
        {"label": "Dashboard", "endpoint": "overview", "icon": "\U0001F3E0", "enabled": True},
    ]},
    {"label": "Operations", "links": [
        {"label": "Bot Status & Restart", "endpoint": "bots_status", "icon": "\U0001F916", "enabled": True},
    ]},
    {"label": "Analytics", "links": [
        {"label": "Student Master", "endpoint": "analytics_students", "icon": "\U0001F393", "enabled": True},
        {"label": "Bot-wise Usage", "endpoint": "analytics_bots", "icon": "\U0001F4C8", "enabled": True},
        {"label": "Faculty Report", "endpoint": "analytics_faculty_report", "icon": "\U0001F4CB", "enabled": True},
        {"label": "Content Health", "endpoint": "analytics_content_health", "icon": "\U0001FA7A", "enabled": True},
        {"label": "Email Analytics", "endpoint": "analytics_email", "icon": "\U0001F4E7", "enabled": True},
    ]},
    {"label": "Data Export", "links": [
        {"label": "Export Any Table", "endpoint": "data_export_index", "icon": "\U00002B07\U0000FE0F", "enabled": True},
    ]},
    {"label": "Masters", "links": [
        {"label": "Tenants & Bots", "endpoint": None, "icon": "\U0001F5C2️", "enabled": False},
        {"label": "Faculty / New Bot", "endpoint": None, "icon": "➕", "enabled": False},
    ]},
    {"label": "Content", "links": [
        {"label": "Course Catalog", "endpoint": "course_catalog", "icon": "\U0001F4DA", "enabled": True},
        {"label": "Question Catalog Edits", "endpoint": None, "icon": "\U0000270F\U0000FE0F", "enabled": False},
    ]},
    {"label": "Leaderboards", "links": [
        {"label": "Boards & Mappings", "endpoint": None, "icon": "\U0001F3C6", "enabled": False},
    ]},
    {"label": "Users & Access", "links": [
        {"label": "Roles & Permissions", "endpoint": None, "icon": "\U0001F510", "enabled": False},
    ]},
]


def get_conn():
    conn = platform_db.get_connection()
    platform_db.init_schema(conn)
    return conn


@app.template_global()
def page_url(page: int) -> str:
    """Used by templates/_pagination.html on every paginated view --
    preserves every OTHER current query arg (filter text, bot_id, etc.),
    only replacing `page`. One implementation, reused everywhere, so a
    paginated page's Next/Prev links never drop a filter a user just
    applied."""
    args = request.args.to_dict(flat=True)
    args["page"] = page
    return f"{request.path}?{urlencode(args)}"


@app.template_global()
def clear_filter_url() -> str:
    """Used by templates/_export_toolbar.html's "Clear" link -- drops `q`
    and `page` but preserves everything else (e.g. Faculty Report's
    bot_id selection), so clearing the text filter doesn't also lose an
    unrelated selection."""
    args = request.args.to_dict(flat=True)
    args.pop("q", None)
    args.pop("page", None)
    return f"{request.path}?{urlencode(args)}" if args else request.path


@app.context_processor
def inject_globals():
    return {
        "nav_sections": NAV_SECTIONS,
        "current_user": auth.current_user(),
        "brand_colors": brand_kit.colors(),
        "current_endpoint": request.endpoint,
    }


# ---------------------------------------------------------------------------
# AUTH
# ---------------------------------------------------------------------------
@app.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form.get("username", "").strip()
        password = request.form.get("password", "")
        if auth.verify_credentials(username, password):
            session.clear()
            session["username"] = username
            session["role"] = "admin"
            next_url = request.args.get("next") or url_for("overview")
            return redirect(next_url)
        flash("Invalid username or password.", "error")
    return render_template("login.html")


@app.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("login"))


# ---------------------------------------------------------------------------
# OVERVIEW
# ---------------------------------------------------------------------------
@app.route("/")
@auth.role_required("admin")
def overview():
    conn = get_conn()
    bots = manage_bots.load_bots()
    heartbeats = analytics.fetch_heartbeats(conn)
    online_count = sum(1 for b in bots if heartbeats.get(b["bot_id"], {}).get("online"))
    unique_mcq = analytics.fetch_unique_mcq_attempters(conn)
    return render_template(
        "overview.html",
        total_bots=len(bots), online_count=online_count,
        unique_mcq_attempters=unique_mcq,
    )


# ---------------------------------------------------------------------------
# BOTS -- status, restart, logs
# ---------------------------------------------------------------------------
@app.route("/bots")
@auth.role_required("admin")
def bots_status():
    conn = get_conn()
    bots = manage_bots.load_bots()
    heartbeats = analytics.fetch_heartbeats(conn)
    rows = []
    for b in bots:
        bot_id = b["bot_id"]
        proc = manage_bots.is_running(bot_id, manage_bots.resolve_script_path(b))
        hb = heartbeats.get(bot_id)
        rows.append({
            "bot_id": bot_id,
            "kind": b["kind"],
            "display_name": b["display_name"],
            "config_status": b.get("status", "unknown"),
            "running": bool(proc),
            "pid": proc.pid if proc else None,
            "heartbeat_age": int(hb["age_seconds"]) if hb else None,
            "online": bool(hb and hb["online"]),
            "has_log": (manage_bots.LOG_DIR / f"{bot_id}.log").exists(),
        })
    return render_template("bots.html", rows=rows)


@app.route("/bots/<bot_id>/restart", methods=["POST"])
@auth.role_required("admin")
def bots_restart(bot_id):
    bots_by_id = {b["bot_id"]: b for b in manage_bots.load_bots()}
    bot = bots_by_id.get(bot_id)
    conn = get_conn()
    if not bot:
        flash(f"Unknown bot_id '{bot_id}'.", "error")
        audit.log_action(conn, auth.current_user(), "bot_restart", bot_id, "failed: unknown bot_id")
        return redirect(url_for("bots_status"))

    try:
        manage_bots.restart_bot(bot)
        flash(f"Restarted {bot['display_name']} ({bot_id}).", "success")
        audit.log_action(conn, auth.current_user(), "bot_restart", bot_id, "ok")
    except Exception as e:
        flash(f"Restart failed for {bot_id}: {e}", "error")
        audit.log_action(conn, auth.current_user(), "bot_restart", bot_id, f"failed: {e}")
    return redirect(url_for("bots_status"))


@app.route("/bots/<bot_id>/logs")
@auth.role_required("admin")
def bots_logs(bot_id):
    bots_by_id = {b["bot_id"]: b for b in manage_bots.load_bots()}
    bot = bots_by_id.get(bot_id)
    if not bot:
        return "Unknown bot_id.", 404

    log_path = manage_bots.LOG_DIR / f"{bot_id}.log"
    tail_n = request.args.get("lines", default=300, type=int)
    if log_path.exists():
        with open(log_path, encoding="utf-8", errors="replace") as f:
            all_lines = f.readlines()
        log_text = "".join(all_lines[-tail_n:])
        total_lines = len(all_lines)
    else:
        log_text = "(no log file yet -- this bot may never have been started)"
        total_lines = 0

    return render_template(
        "bot_logs.html", bot=bot, log_text=log_text, log_path=str(log_path),
        tail_n=tail_n, total_lines=total_lines,
    )


# ---------------------------------------------------------------------------
# DATA EXPORT -- any DB table, straight to json/csv/xlsx (Pranav, 2026-08-11:
# "download any tables in a json or csv or xlsx file directly from any
# Database tables"). Blanket access, no table scoping (his confirmed
# choice, 2026-08-11 -- single-admin login is the only gate today; RBAC
# later can scope this per-role without a redesign).
# ---------------------------------------------------------------------------
def get_all_table_names(conn) -> list:
    rows = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
    ).fetchall()
    return [r[0] for r in rows]


@app.route("/export")
@auth.role_required("admin")
def data_export_index():
    conn = get_conn()
    tables = []
    for name in get_all_table_names(conn):
        # name comes only from sqlite_master's own enumeration above, never
        # from request input -- safe to interpolate into SQL as a quoted
        # identifier (Python's DB-API has no separate placeholder syntax
        # for identifiers, only values).
        count = conn.execute(f'SELECT COUNT(*) FROM "{name}"').fetchone()[0]
        tables.append({"name": name, "row_count": count})
    return render_template("data_export.html", tables=tables)


@app.route("/export/<table_name>.<fmt>")
@auth.role_required("admin")
def export_table(table_name, fmt):
    conn = get_conn()
    if table_name not in set(get_all_table_names(conn)):
        return "Unknown table.", 404
    if fmt not in ("json", "csv", "xlsx"):
        return "Unsupported format -- use .json, .csv, or .xlsx", 400

    cursor = conn.execute(f'SELECT * FROM "{table_name}"')
    columns, rows = exporters.rows_from_cursor(cursor)
    audit.log_action(conn, auth.current_user(), "table_export", table_name, fmt)

    if fmt == "json":
        return exporters.json_response(columns, rows, table_name)
    if fmt == "csv":
        return exporters.csv_response(columns, rows, table_name)
    return exporters.xlsx_response(columns, rows, table_name)


# ---------------------------------------------------------------------------
# ANALYTICS > Student Master -- paginated/filterable, exportable, and the
# bulk "send performance report" action (Pranav, 2026-08-11: student
# master data visible "as per his wish," plus sending the existing
# per-student report to one or many students at once).
# ---------------------------------------------------------------------------
STUDENT_MASTER_FILTER_FIELDS = ["telegram_user_id", "display_name", "username", "email", "mobile_number", "faculty", "courses"]


def _get_student_master_rows(conn) -> list:
    return analytics.fetch_student_master(conn, manage_bots.load_bots())


@app.route("/analytics/students")
@auth.role_required("admin")
def analytics_students():
    conn = get_conn()
    all_rows = _get_student_master_rows(conn)
    q = request.args.get("q", "").strip()
    filtered = exporters.filter_rows(all_rows, q, STUDENT_MASTER_FILTER_FIELDS)
    page = request.args.get("page", 1, type=int)
    pg = exporters.paginate(filtered, page, per_page=25)
    export_urls = {fmt: url_for("analytics_students_export", fmt=fmt, q=q) for fmt in ("csv", "xlsx", "html", "pdf")}
    return render_template(
        "analytics_students.html", rows=pg["items"], pagination=pg, filter_query=q,
        total_filtered=len(filtered), total_all=len(all_rows), export_urls=export_urls,
    )


def _student_master_export_columns():
    return ["telegram_user_id", "display_name", "username", "email", "mobile_number",
            "faculty", "courses", "first_seen_at", "last_seen_at"]


def _student_master_export_rows(rows):
    cols = _student_master_export_columns()
    out = [
        [r["telegram_user_id"], r["display_name"], r.get("username"), r.get("email"), r.get("mobile_number"),
         "; ".join(r.get("faculty") or []), "; ".join(r.get("courses") or []),
         r.get("first_seen_at"), r.get("last_seen_at")]
        for r in rows
    ]
    return cols, out


@app.route("/analytics/students.<fmt>")
@auth.role_required("admin")
def analytics_students_export(fmt):
    if fmt not in ("csv", "xlsx", "html", "pdf"):
        return "Unsupported format.", 400
    conn = get_conn()
    all_rows = _get_student_master_rows(conn)
    q = request.args.get("q", "").strip()
    filtered = exporters.filter_rows(all_rows, q, STUDENT_MASTER_FILTER_FIELDS)
    cols, out_rows = _student_master_export_rows(filtered)
    audit.log_action(conn, auth.current_user(), "analytics_export", "student_master", fmt)
    if fmt == "csv":
        return exporters.csv_response(cols, out_rows, "student_master")
    if fmt == "xlsx":
        return exporters.xlsx_response(cols, out_rows, "student_master")
    if fmt == "html":
        return exporters.html_export_response("Student Master", cols, out_rows, brand_kit.colors(), "student_master")
    return exporters.pdf_export_response("Student Master", cols, out_rows, brand_kit.colors(), "student_master")


@app.route("/analytics/students/send-report", methods=["POST"])
@auth.role_required("admin")
def analytics_students_send_report():
    """Sends each selected student their OWN existing performance report
    (the same PDF generate_student_report.py already produces), ONLY to a
    student's already echo-confirmed email on file (Pranav's confirmed
    choice, 2026-08-11 -- never guessed/typed in for them here). A student
    with no confirmed email is reported as skipped, never silently
    dropped. Sent from the admin portal's own dedicated address
    ('reports@1lavya.com', bots.json's 1lavya-admin-portal entry) -- an
    honest label, not impersonating whichever bot the student happens to
    use, since this send is admin-triggered, not bot-triggered."""
    conn = get_conn()
    selected = request.form.getlist("telegram_user_id")
    results = []
    for uid_str in selected:
        try:
            uid = int(uid_str)
        except ValueError:
            continue
        row = conn.execute("SELECT email FROM students WHERE telegram_user_id=?", (uid,)).fetchone()
        if not row or not row[0]:
            results.append((uid, "skipped"))
            continue
        email = row[0]
        try:
            data_for_name = student_analytics.fetch_student_report_data(conn, uid)
            display_name = generate_student_report.display_name_for_student(data_for_name)
            pdf_bytes = generate_student_report.build_report_pdf(conn, uid)
            report_delivery.send_report_email(BOT_ID, email, pdf_bytes, display_name, "All-time")
            report_delivery.log_report_delivery(conn, uid, "All-time (admin-sent)", "email", email_status="sent")
            results.append((uid, "sent"))
        except Exception as e:
            report_delivery.log_report_delivery(conn, uid, "All-time (admin-sent)", "email",
                                                  email_status="failed", error_detail=str(e))
            results.append((uid, "failed"))

    sent = sum(1 for _, s in results if s == "sent")
    failed = sum(1 for _, s in results if s == "failed")
    skipped = sum(1 for _, s in results if s == "skipped")
    flash(f"Reports: {sent} sent, {failed} failed, {skipped} skipped (no confirmed email on file).",
          "success" if failed == 0 else "error")
    audit.log_action(conn, auth.current_user(), "bulk_report_send", f"{len(selected)} students",
                      f"sent={sent} failed={failed} skipped={skipped}")
    return redirect(url_for("analytics_students"))


# ---------------------------------------------------------------------------
# ANALYTICS > Bot-wise Usage Summary
# ---------------------------------------------------------------------------
BOT_SUMMARY_FILTER_FIELDS = ["bot_id", "display_name"]


def _get_bot_summary_rows(conn) -> list:
    summary = analytics.fetch_bot_summary(conn)
    bot_meta = {b["bot_id"]: b for b in manage_bots.load_bots()}
    rows = []
    for bot_id, s in summary.items():
        meta = bot_meta.get(bot_id, {})
        sh, eh = s.get("study_hub") or {}, s.get("exam_hub") or {}
        rows.append({
            "bot_id": bot_id, "display_name": meta.get("display_name", bot_id),
            "total_interactions": s["total_interactions"], "unique_users": s["unique_users"],
            "downloads": sh.get("file_download", 0), "searches": sh.get("search_query", 0) + sh.get("search_no_match", 0),
            "sessions": eh.get("sessions", 0), "mcq_shown": eh.get("mcq_shown", 0), "mcq_answered": eh.get("mcq_answered", 0),
            "mcq_accuracy_pct": eh.get("mcq_accuracy_pct"), "descriptive_shown": eh.get("descriptive_shown", 0),
            "last_seen_at": s.get("last_seen_at"),
        })
    rows.sort(key=lambda r: r["total_interactions"], reverse=True)
    return rows


@app.route("/analytics/bots")
@auth.role_required("admin")
def analytics_bots():
    conn = get_conn()
    all_rows = _get_bot_summary_rows(conn)
    q = request.args.get("q", "").strip()
    filtered = exporters.filter_rows(all_rows, q, BOT_SUMMARY_FILTER_FIELDS)
    page = request.args.get("page", 1, type=int)
    pg = exporters.paginate(filtered, page, per_page=25)
    export_urls = {fmt: url_for("analytics_bots_export", fmt=fmt, q=q) for fmt in ("csv", "xlsx", "html", "pdf")}
    return render_template("analytics_bots.html", rows=pg["items"], pagination=pg, filter_query=q,
                            total_filtered=len(filtered), export_urls=export_urls)


def _bot_summary_export_columns():
    return ["bot_id", "display_name", "total_interactions", "unique_users", "downloads", "searches",
            "sessions", "mcq_shown", "mcq_answered", "mcq_accuracy_pct", "descriptive_shown", "last_seen_at"]


@app.route("/analytics/bots.<fmt>")
@auth.role_required("admin")
def analytics_bots_export(fmt):
    if fmt not in ("csv", "xlsx", "html", "pdf"):
        return "Unsupported format.", 400
    conn = get_conn()
    all_rows = _get_bot_summary_rows(conn)
    q = request.args.get("q", "").strip()
    filtered = exporters.filter_rows(all_rows, q, BOT_SUMMARY_FILTER_FIELDS)
    cols = _bot_summary_export_columns()
    out_rows = [[r.get(c) for c in cols] for r in filtered]
    audit.log_action(conn, auth.current_user(), "analytics_export", "bot_summary", fmt)
    if fmt == "csv":
        return exporters.csv_response(cols, out_rows, "bot_usage_summary")
    if fmt == "xlsx":
        return exporters.xlsx_response(cols, out_rows, "bot_usage_summary")
    if fmt == "html":
        return exporters.html_export_response("Bot-wise Usage Summary", cols, out_rows, brand_kit.colors(), "bot_usage_summary")
    return exporters.pdf_export_response("Bot-wise Usage Summary", cols, out_rows, brand_kit.colors(), "bot_usage_summary")


# ---------------------------------------------------------------------------
# ANALYTICS > Faculty Report -- student-wise, with a per-student chapter
# drill-down (a separate small page, not an inline JS-expand row, so it
# reuses the same paginate/filter/export primitives as everything else).
# ---------------------------------------------------------------------------
FACULTY_REPORT_FILTER_FIELDS = ["telegram_user_id", "display_name"]


def _faculty_report_bot_ids() -> list:
    return [b["bot_id"] for b in manage_bots.load_bots() if b["kind"] in ("exam", "unified")]


def _get_faculty_report_rows(conn, bot_id: str) -> list:
    if not bot_id:
        return []
    return analytics.fetch_faculty_report(conn, [bot_id]).get(bot_id, [])


@app.route("/analytics/faculty-report")
@auth.role_required("admin")
def analytics_faculty_report():
    conn = get_conn()
    bot_ids = _faculty_report_bot_ids()
    bot_meta = {b["bot_id"]: b for b in manage_bots.load_bots()}
    selected_bot = request.args.get("bot_id") or (bot_ids[0] if bot_ids else None)
    all_rows = _get_faculty_report_rows(conn, selected_bot)
    q = request.args.get("q", "").strip()
    filtered = exporters.filter_rows(all_rows, q, FACULTY_REPORT_FILTER_FIELDS)
    page = request.args.get("page", 1, type=int)
    pg = exporters.paginate(filtered, page, per_page=25)
    export_urls = {
        fmt: url_for("analytics_faculty_report_export", fmt=fmt, q=q, bot_id=selected_bot)
        for fmt in ("csv", "xlsx", "html", "pdf")
    } if selected_bot else {}
    return render_template(
        "analytics_faculty_report.html", rows=pg["items"], pagination=pg, filter_query=q,
        bot_ids=bot_ids, bot_meta=bot_meta, selected_bot=selected_bot, total_filtered=len(filtered),
        export_urls=export_urls, filter_extra_fields=[("bot_id", selected_bot)] if selected_bot else [],
    )


@app.route("/analytics/faculty-report.<fmt>")
@auth.role_required("admin")
def analytics_faculty_report_export(fmt):
    if fmt not in ("csv", "xlsx", "html", "pdf"):
        return "Unsupported format.", 400
    conn = get_conn()
    selected_bot = request.args.get("bot_id")
    if not selected_bot:
        return "bot_id query param required.", 400
    all_rows = _get_faculty_report_rows(conn, selected_bot)
    q = request.args.get("q", "").strip()
    filtered = exporters.filter_rows(all_rows, q, FACULTY_REPORT_FILTER_FIELDS)
    cols = ["telegram_user_id", "display_name", "total_attempted", "total_correct", "accuracy_pct"]
    out_rows = [[r.get(c) for c in cols] for r in filtered]
    audit.log_action(conn, auth.current_user(), "analytics_export", f"faculty_report:{selected_bot}", fmt)
    filename = f"faculty_report_{selected_bot}"
    title = f"Faculty Report -- {selected_bot}"
    if fmt == "csv":
        return exporters.csv_response(cols, out_rows, filename)
    if fmt == "xlsx":
        return exporters.xlsx_response(cols, out_rows, filename)
    if fmt == "html":
        return exporters.html_export_response(title, cols, out_rows, brand_kit.colors(), filename)
    return exporters.pdf_export_response(title, cols, out_rows, brand_kit.colors(), filename)


@app.route("/analytics/faculty-report/<bot_id>/<int:telegram_user_id>/chapters")
@auth.role_required("admin")
def analytics_faculty_report_chapters(bot_id, telegram_user_id):
    conn = get_conn()
    rows = _get_faculty_report_rows(conn, bot_id)
    student = next((r for r in rows if r["telegram_user_id"] == telegram_user_id), None)
    if not student:
        return "Student not found for this bot.", 404
    page = request.args.get("page", 1, type=int)
    pg = exporters.paginate(student["chapters"], page, per_page=25)
    return render_template("analytics_faculty_chapters.html", student=student, rows=pg["items"], pagination=pg, bot_id=bot_id)


# ---------------------------------------------------------------------------
# ANALYTICS > Content Health -- flattened one row per issue
# ---------------------------------------------------------------------------
CONTENT_HEALTH_FILTER_FIELDS = ["file", "kind", "severity", "record_id", "field", "message"]


def _get_content_health_rows() -> list:
    out = []
    for r in analytics.fetch_content_health():
        short_path = Path(r["path"]).name
        for issue in r.get("issues", []):
            out.append({
                "file": short_path, "kind": r["kind"], "severity": issue["severity"],
                "record_id": issue.get("record_id"), "field": issue.get("field"), "message": issue["message"],
            })
    return out


@app.route("/analytics/content-health")
@auth.role_required("admin")
def analytics_content_health():
    all_rows = _get_content_health_rows()
    q = request.args.get("q", "").strip()
    filtered = exporters.filter_rows(all_rows, q, CONTENT_HEALTH_FILTER_FIELDS)
    page = request.args.get("page", 1, type=int)
    pg = exporters.paginate(filtered, page, per_page=25)
    error_count = sum(1 for r in all_rows if r["severity"] == "ERROR")
    warning_count = sum(1 for r in all_rows if r["severity"] == "WARNING")
    export_urls = {fmt: url_for("analytics_content_health_export", fmt=fmt, q=q) for fmt in ("csv", "xlsx", "html", "pdf")}
    return render_template(
        "analytics_content_health.html", rows=pg["items"], pagination=pg, filter_query=q,
        total_filtered=len(filtered), error_count=error_count, warning_count=warning_count, export_urls=export_urls,
    )


@app.route("/analytics/content-health.<fmt>")
@auth.role_required("admin")
def analytics_content_health_export(fmt):
    if fmt not in ("csv", "xlsx", "html", "pdf"):
        return "Unsupported format.", 400
    conn = get_conn()
    all_rows = _get_content_health_rows()
    q = request.args.get("q", "").strip()
    filtered = exporters.filter_rows(all_rows, q, CONTENT_HEALTH_FILTER_FIELDS)
    cols = CONTENT_HEALTH_FILTER_FIELDS
    out_rows = [[r.get(c) for c in cols] for r in filtered]
    audit.log_action(conn, auth.current_user(), "analytics_export", "content_health", fmt)
    if fmt == "csv":
        return exporters.csv_response(cols, out_rows, "content_health")
    if fmt == "xlsx":
        return exporters.xlsx_response(cols, out_rows, "content_health")
    if fmt == "html":
        return exporters.html_export_response("Content Health", cols, out_rows, brand_kit.colors(), "content_health")
    return exporters.pdf_export_response("Content Health", cols, out_rows, brand_kit.colors(), "content_health")


# ---------------------------------------------------------------------------
# ANALYTICS > Email Analytics -- report_deliveries, one row per attempt
# ---------------------------------------------------------------------------
EMAIL_ANALYTICS_FILTER_FIELDS = ["telegram_user_id", "display_name", "email", "criteria",
                                  "channels_requested", "email_status", "telegram_status", "error_detail"]


def _get_email_analytics_rows(conn) -> list:
    rows = conn.execute(
        """
        SELECT rd.delivery_id, rd.telegram_user_id,
               COALESCE(s.first_name || ' ' || COALESCE(s.last_name,''), s.username, 'Student ' || rd.telegram_user_id) AS display_name,
               s.email, rd.generated_at, rd.criteria, rd.channels_requested, rd.email_status, rd.telegram_status, rd.error_detail
        FROM report_deliveries rd LEFT JOIN students s ON s.telegram_user_id = rd.telegram_user_id
        ORDER BY rd.delivery_id DESC
        """
    ).fetchall()
    return [
        {
            "delivery_id": r[0], "telegram_user_id": r[1], "display_name": r[2], "email": r[3],
            "generated_at": r[4], "criteria": r[5], "channels_requested": r[6],
            "email_status": r[7], "telegram_status": r[8], "error_detail": r[9],
        }
        for r in rows
    ]


@app.route("/analytics/email")
@auth.role_required("admin")
def analytics_email():
    conn = get_conn()
    all_rows = _get_email_analytics_rows(conn)
    q = request.args.get("q", "").strip()
    filtered = exporters.filter_rows(all_rows, q, EMAIL_ANALYTICS_FILTER_FIELDS)
    page = request.args.get("page", 1, type=int)
    pg = exporters.paginate(filtered, page, per_page=25)
    sent_count = sum(1 for r in all_rows if r["email_status"] == "sent")
    failed_count = sum(1 for r in all_rows if r["email_status"] == "failed")
    export_urls = {fmt: url_for("analytics_email_export", fmt=fmt, q=q) for fmt in ("csv", "xlsx", "html", "pdf")}
    return render_template(
        "analytics_email.html", rows=pg["items"], pagination=pg, filter_query=q,
        total_filtered=len(filtered), sent_count=sent_count, failed_count=failed_count, total_all=len(all_rows),
        export_urls=export_urls,
    )


@app.route("/analytics/email.<fmt>")
@auth.role_required("admin")
def analytics_email_export(fmt):
    if fmt not in ("csv", "xlsx", "html", "pdf"):
        return "Unsupported format.", 400
    conn = get_conn()
    all_rows = _get_email_analytics_rows(conn)
    q = request.args.get("q", "").strip()
    filtered = exporters.filter_rows(all_rows, q, EMAIL_ANALYTICS_FILTER_FIELDS)
    cols = ["delivery_id", "telegram_user_id", "display_name", "email", "generated_at", "criteria",
            "channels_requested", "email_status", "telegram_status", "error_detail"]
    out_rows = [[r.get(c) for c in cols] for r in filtered]
    audit.log_action(conn, auth.current_user(), "analytics_export", "email_analytics", fmt)
    if fmt == "csv":
        return exporters.csv_response(cols, out_rows, "email_analytics")
    if fmt == "xlsx":
        return exporters.xlsx_response(cols, out_rows, "email_analytics")
    if fmt == "html":
        return exporters.html_export_response("Email Analytics", cols, out_rows, brand_kit.colors(), "email_analytics")
    return exporters.pdf_export_response("Email Analytics", cols, out_rows, brand_kit.colors(), "email_analytics")


# ---------------------------------------------------------------------------
# CONTENT > Course Catalog -- Course/Level/Subject-wise view of
# course_catalog (Pranav, 2026-08-11: "I also want to see the Course,
# Level and Subject wise the Course Catalog"). The single source of truth
# every MCQ/descriptive question's human_id is now derived from -- see
# telegram/tools/populate_course_catalog.py / generate_mcq_human_ids.py.
# ---------------------------------------------------------------------------
COURSE_CATALOG_FILTER_FIELDS = ["chapter_no", "chapter_name", "chapter_name_short", "unit_no", "unit_name"]


def _format_paper_no(paper_no: str) -> str:
    """'1' -> 'P01', '7A' -> 'P7A' -- same rule as generate_mcq_human_ids.py's
    own _format_paper(), duplicated (not imported, telegram/tools/ isn't
    normally on this app's import path) since both are simple/stable enough
    not to need a shared module for one formatting rule."""
    return f"P{str(paper_no).zfill(2)}"


def _course_catalog_course_levels(conn) -> dict:
    """{course: [levels...]} actually present in course_catalog, in a
    stable Foundation->Inter->Final-ish order (by level_num)."""
    rows = conn.execute(
        "SELECT DISTINCT course, level, level_num FROM course_catalog ORDER BY course, level_num"
    ).fetchall()
    out = {}
    for course, level, _ in rows:
        out.setdefault(course, []).append(level)
    return out


@app.route("/content/course-catalog")
@auth.role_required("admin")
def course_catalog():
    conn = get_conn()
    course_levels = _course_catalog_course_levels(conn)
    courses = list(course_levels.keys())
    selected_course = request.args.get("course") or (courses[0] if courses else None)
    levels = course_levels.get(selected_course, [])
    selected_level = request.args.get("level") or (levels[0] if levels else None)

    subjects = []
    if selected_course and selected_level:
        subjects = [
            r[0] for r in conn.execute(
                "SELECT DISTINCT subject FROM course_catalog WHERE course=? AND level=? ORDER BY subject",
                (selected_course, selected_level),
            ).fetchall()
        ]
    selected_subject = request.args.get("subject") or (subjects[0] if subjects else None)

    all_rows = []
    if selected_course and selected_level and selected_subject:
        rows = conn.execute(
            "SELECT paper_no, chapter_no, chapter_name, chapter_name_short, unit_no, unit_name, unit_name_short, source "
            "FROM course_catalog WHERE course=? AND level=? AND subject=? ORDER BY chapter_no, unit_no",
            (selected_course, selected_level, selected_subject),
        ).fetchall()
        all_rows = [
            {"paper_no": r[0], "paper_display": _format_paper_no(r[0]), "chapter_no": r[1], "chapter_name": r[2],
             "chapter_name_short": r[3], "unit_no": r[4], "unit_name": r[5], "unit_name_short": r[6], "source": r[7]}
            for r in rows
        ]

    q = request.args.get("q", "").strip()
    filtered = exporters.filter_rows(all_rows, q, COURSE_CATALOG_FILTER_FIELDS)
    page = request.args.get("page", 1, type=int)
    pg = exporters.paginate(filtered, page, per_page=50)

    filter_extra = [("course", selected_course), ("level", selected_level), ("subject", selected_subject)]
    export_urls = {
        fmt: url_for("course_catalog_export", fmt=fmt, q=q, course=selected_course, level=selected_level, subject=selected_subject)
        for fmt in ("csv", "xlsx", "html", "pdf")
    } if (selected_course and selected_level and selected_subject) else {}

    return render_template(
        "course_catalog.html", rows=pg["items"], pagination=pg, filter_query=q,
        courses=courses, levels=levels, subjects=subjects,
        selected_course=selected_course, selected_level=selected_level, selected_subject=selected_subject,
        total_filtered=len(filtered), export_urls=export_urls, filter_extra_fields=filter_extra,
    )


@app.route("/content/course-catalog.<fmt>")
@auth.role_required("admin")
def course_catalog_export(fmt):
    if fmt not in ("csv", "xlsx", "html", "pdf"):
        return "Unsupported format.", 400
    course, level, subject = request.args.get("course"), request.args.get("level"), request.args.get("subject")
    if not (course and level and subject):
        return "course, level, and subject query params are all required.", 400
    conn = get_conn()
    rows = conn.execute(
        "SELECT paper_no, chapter_no, chapter_name, chapter_name_short, unit_no, unit_name, unit_name_short, source "
        "FROM course_catalog WHERE course=? AND level=? AND subject=? ORDER BY chapter_no, unit_no",
        (course, level, subject),
    ).fetchall()
    all_rows = [
        {"paper_no": r[0], "chapter_no": r[1], "chapter_name": r[2], "chapter_name_short": r[3],
         "unit_no": r[4], "unit_name": r[5], "unit_name_short": r[6], "source": r[7]}
        for r in rows
    ]
    q = request.args.get("q", "").strip()
    filtered = exporters.filter_rows(all_rows, q, COURSE_CATALOG_FILTER_FIELDS)
    cols = ["paper_no", "chapter_no", "chapter_name", "chapter_name_short", "unit_no", "unit_name", "unit_name_short", "source"]
    out_rows = [[r.get(c) for c in cols] for r in filtered]
    audit.log_action(conn, auth.current_user(), "analytics_export", f"course_catalog:{course}/{level}/{subject}", fmt)
    filename = f"course_catalog_{course}_{level}_{subject}".replace(" ", "_")
    title = f"Course Catalog -- {course} {level} {subject}"
    if fmt == "csv":
        return exporters.csv_response(cols, out_rows, filename)
    if fmt == "xlsx":
        return exporters.xlsx_response(cols, out_rows, filename)
    if fmt == "html":
        return exporters.html_export_response(title, cols, out_rows, brand_kit.colors(), filename)
    return exporters.pdf_export_response(title, cols, out_rows, brand_kit.colors(), filename)


def _heartbeat_loop(interval_seconds: int = 120):
    """Same technique as dashboard_server.py's own _heartbeat_loop() -- this
    is a plain Flask/WSGI process, no python-telegram-bot Application/
    JobQueue to hang a periodic heartbeat off of, so a daemon background
    thread does the same job. Without this, manage_bots.py status/the
    watcher/the dashboard would never see this process as online."""
    conn = platform_db.get_connection()
    platform_db.init_schema(conn)
    pid = os.getpid()
    started_at = platform_db.now()
    while True:
        platform_db.send_heartbeat(conn, BOT_ID, pid, started_at)
        time.sleep(interval_seconds)


def main():
    threading.Thread(target=_heartbeat_loop, daemon=True).start()
    port = int(os.environ.get("ADMIN_PORTAL_PORT", "8788"))
    app.logger.info(f"1LAVYA Admin Portal starting on http://127.0.0.1:{port}/")
    app.run(host="127.0.0.1", port=port, debug=False, threaded=True)


if __name__ == "__main__":
    main()
