# Batch 7 (rows 301-350)
TAGS = {
301: dict(chapters=[("M2-C9-U2","AS 14", [("2.11","Treatment of Goodwill Arising on Amalgamation","9.3")])], scope="single", confidence="confident", notes="Goodwill amortisation, same theme as row 75."),
302: dict(chapters=[("M2-C5-U3","AS 13", [("3.4","Classification of Investments","5.8")])], scope="single", confidence="confident", notes="Current Investment definition."),
303: dict(chapters=[("M2-C6-U1","AS 15", [("1.7","Accounting Treatment","6.13")])], scope="single", confidence="confident", notes="Gratuity DBO equal annual charge calc."),
304: dict(chapters=[("M3-C13-U0", None, [("7","Entries in the books of Purchasing Company","13.29")])],
    scope="single", confidence="inferred",
    notes="Duplicate-chapter situation (see row 106): unrealised-profit-in-stock elimination post-amalgamation has no matching AS14 (M2-C9-U2) topic, so falls to M3-C13-U0's purchasing-company-entries topic per the fallback rule."),
305: dict(chapters=[("M1-C1-U0", None, [("1","Introduction","1.2")])], scope="single", confidence="confident", notes="Intra- vs inter-enterprise comparison."),
306: dict(chapters=[("M2-C6-U1","AS 15", [("1.4","Short-term Employee Benefits","6.6")])], scope="single", confidence="confident", notes="Profit-sharing plan expected cost."),
307: dict(chapters=[("M2-C8-U1","AS 7", [("1.5","Contract Revenue and Costs","8.7")])],
    scope="single", confidence="inferred", notes="'Outcome cannot be estimated reliably -> cost-recovery method' rule not separately topic-numbered; mapped to Contract Revenue and Costs."),
308: dict(chapters=[("M3-C14-U0", None, [("8","Entries in case of internal reconstruction","14.12")])], scope="single", confidence="confident", notes="Property revalued upward under reconstruction."),
309: dict(chapters=[("M2-C5-U1","AS 2", [("1.9","Exclusions from the cost of inventories","5.9")])], scope="single", confidence="confident", notes="Raw material cost is NOT excluded."),
310: dict(chapters=[("M2-C7-U3","AS 11", [("3.5","Recognition of Exchange Differences","7.32")])], scope="single", confidence="confident", notes="Case cluster 0ebfb1c7 (with row 225) - both AS11, consistent."),
311: dict(chapters=[("M2-C8-U2","AS 9", [("2.7","Income from other sources - Interest, Royalties and Dividends","8.42")])], scope="single", confidence="confident", notes=""),
312: dict(chapters=[("M2-C5-U2","AS 10", [("2.7","Initial Recognition","5.28")])], scope="single", confidence="confident", notes="Case cluster 15ccb29c (with row 41) - both AS10, consistent."),
313: dict(chapters=[("M3-C11-U2", None, [("2.4","Calculation of Cash Flows from Operating Activities","11.8")])], scope="single", confidence="confident", notes="Non-cash exchange-gain adjustment; AS3 convention."),
314: dict(chapters=[("M3-C11-U1", None, [("1.6","Distributable Profit","11.18")])], scope="single", confidence="confident", notes="Companies (Dividend) Rules 2014, 1/10th reserves cap."),
315: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1. Case cluster f5667ebd (with row 35) - consistent."),
316: dict(chapters=[("M2-C7-U3","AS 11", [("3.5","Recognition of Exchange Differences","7.32")])],
    scope="single", confidence="flagged",
    notes="This row is a near-exact duplicate of row 310 (identical question text, options, and answer, same case cluster 0ebfb1c7) - likely a data-entry duplicate within the source bank rather than a genuine OP/PP recurring-question pattern (those normally recur across different sittings, not within one case cluster). Flagging for Pranav's review; tagged identically to row 310 either way."),
317: dict(chapters=[("M3-C11-U1", None, [("1.5","Final Accounts","11.1")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 14 (bonus-share source disclosure not required)."),
318: dict(chapters=[("M2-C7-U2","AS 5", [("2.2","Net Profit or Loss for the Period","7.15")])], scope="single", confidence="confident", notes="Extraordinary item example (earthquake)."),
319: dict(chapters=[("M2-C5-U2","AS 10", [("2.6","Measurement of PPE","5.27")])], scope="single", confidence="inferred", notes="PPE retired-from-use valuation not separately topic-numbered; same gap pattern as rows 41/94/163."),
320: dict(chapters=[("M2-C6-U1","AS 15", [("1.10","Actuarial Gains and Losses","6.16")])], scope="single", confidence="confident", notes="Actuarial surplus recognised immediately."),
321: dict(chapters=[("M2-C9-U2","AS 14", [("2.9","Adjustments to reserves - Amalgamation in the Nature of Merger","9.28")])], scope="single", confidence="confident", notes="Duplicate-chapter rule (row 106) - AS14 topic matches directly."),
322: dict(chapters=[("M2-C5-U2","AS 10", [("2.7","Initial Recognition","5.28")])], scope="single", confidence="confident", notes="Trial-run/soft-opening costs not capitalised."),
323: dict(chapters=[("M2-C5-U2","AS 10", [("2.5","Recognition Criteria for PPE","5.26")])],
    scope="single", confidence="confident",
    notes="Case cluster 4778790b (with rows 10, 27, 153) - reclassification to PPE due to change in intended use; the AS2/AS10 cross-chapter pattern already flagged on row 10."),
324: dict(chapters=[("M1-C2-U0", None, [("11","Capital Maintenance","2.25")])], scope="single", confidence="confident", notes="Financial Capital Maintenance at Current Purchasing Power."),
325: dict(chapters=[("M3-C15-U0", None, [("6","Accounting for Independent Branches","15.41")])], scope="single", confidence="confident", notes="HO-maintained asset account for independent branch."),
326: dict(chapters=[("M1-C3-U0", None, [("2","Applicability of Accounting Standards","3.6")])], scope="single", confidence="confident", notes="Scheme not relevant for entities under other sectoral Ind AS/AS mandates."),
327: dict(chapters=[("M1-C4-U1","AS 1", [("1.2","Fundamental Accounting Assumptions","4.3")])], scope="single", confidence="confident", notes="Consistency principle."),
328: dict(chapters=[("M2-C7-U4","AS 22", [("4.4","Recognition","7.56")])], scope="single", confidence="confident", notes="DTL creation, tax depreciation > book depreciation."),
329: dict(chapters=[("M2-C5-U2","AS 10", [("2.6","Measurement of PPE","5.27")])], scope="single", confidence="inferred", notes="Land/building depreciation distinction not separately topic-numbered; same gap pattern as rows 41/94/163/319."),
330: dict(chapters=[("M3-C11-U2", None, [("2.4","Calculation of Cash Flows from Operating Activities","11.8"), ("2.5","Calculation of Cash Flows from Investing Activities","11.82")])],
    scope="single", confidence="confident", notes="Full sale proceeds to investing, gain adjustment in operating; AS3 convention."),
331: dict(chapters=[("M2-C10-U1","AS 21", [("1.14","Consolidation Adjustments","10.27")])],
    scope="single", confidence="inferred", notes="Subsidiary bonus-share issue (no entry in holding co books) not separately topic-numbered; mapped to Consolidation Adjustments."),
332: dict(chapters=[("M1-C2-U0", None, [("9","Elements of Financial Statements","2.13")])], scope="single", confidence="confident", notes="Obligation arises on delivery/irrevocable agreement, not future commitment."),
333: dict(chapters=[("M1-C3-U0", None, [("2","Applicability of Accounting Standards","3.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 25 (AS25/SEBI quarterly-results requirement)."),
334: dict(chapters=[("M1-C4-U3","AS 17", [("3.10","Segment Accounting Policies","4.53")])], scope="single", confidence="confident", notes="Inter-segment transfer pricing policy."),
335: dict(chapters=[("M1-C4-U3","AS 17", [("3.9","Identifying Reportable Segments (Quantitative Thresholds)","4.51")])],
    scope="single", confidence="confident",
    notes="Case cluster 5c708acd now spans FOUR chapters: AS12 (row 48), AS26 (row 112), AS22 (row 232), and AS17 (this row) - flagging as the largest cross-chapter cluster found, per the open case-scenario-cluster issue."),
336: dict(chapters=[("M2-C6-U1","AS 15", [("1.3","Meaning of the term \"Employee Benefits\"","6.5")])], scope="single", confidence="confident", notes="Post-Employment Benefit classification."),
337: dict(chapters=[("M2-C7-U2","AS 5", [("2.3","Prior Period Items","7.17")])], scope="single", confidence="confident", notes="Retrospective wage revision - not a prior period item."),
338: dict(chapters=[("M1-C1-U0", None, [("7","International Financial Reporting Standards as Global Standards","1.16")])], scope="single", confidence="confident", notes="IFRS comprehensive framework definition."),
339: dict(chapters=[("M1-C2-U0", None, [("9","Elements of Financial Statements","2.13")])], scope="single", confidence="confident", notes="Profit = CE-OE-C+D calc."),
340: dict(chapters=[("M1-C1-U0", None, [("8","Becoming IFRS Compliant","1.17")])], scope="single", confidence="confident", notes="Convergence vs Adoption."),
341: dict(chapters=[("M3-C14-U0", None, [("5","Reduction of Share Capital","14.9"), ("8","Entries in case of internal reconstruction","14.12")])],
    scope="single", confidence="confident", notes="Preference + equity capital reduction credit calc."),
342: dict(chapters=[("M2-C5-U2","AS 10", [("2.6","Measurement of PPE","5.27")])], scope="single", confidence="inferred", notes="Same Revaluation Model gap as rows 117/163/246."),
343: dict(chapters=[("M1-C4-U4","AS 18", [("4.4","Who are NOT deemed to be Related Parties under AS-18?","4.74")])], scope="single", confidence="confident", notes=""),
344: dict(chapters=[("M2-C5-U2","AS 10", [("2.9","PPE acquired in Exchange for a Non-monetary Asset or Assets or A combination of Monetary and Non-monetary Assets","5.34")])], scope="single", confidence="confident", notes="Exchange lacking commercial substance."),
345: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1. Case cluster 2b23f733 (with row 192) - consistent."),
346: dict(chapters=[("M2-C7-U1","AS 4", [("1.4","Adjusting Events","7.4")])], scope="single", confidence="confident", notes="Court judgment before approval - adjusting event."),
347: dict(chapters=[("M2-C9-U2","AS 14", [("2.7","Consideration","9.27")])], scope="single", confidence="confident", notes="Duplicate-chapter rule (row 106) - AS14 topic matches directly."),
348: dict(chapters=[("M1-C3-U0", None, [("1","Status of Accounting Standards","3.2")])], scope="single", confidence="confident", notes="Sec 129(5) deviation-from-AS disclosure requirement."),
349: dict(chapters=[("M3-C11-U2", None, [("2.3","Classification of Cash Flow Activities","11.76")])],
    scope="single", confidence="confident", notes="Case cluster f5e7dfbc (with rows 91, 200, 280) - all AS3, consistent."),
350: dict(chapters=[("M2-C9-U2","AS 14", [("2.5","Amalgamation in the Nature of Purchase","9.26"), ("2.11","Treatment of Goodwill Arising on Amalgamation","9.3")])],
    scope="single", confidence="confident", notes="Net assets > PC -> Capital Reserve. Duplicate-chapter rule (row 106), consistent with row 15's Net Assets Method tag."),
}
