# Batch 6 (rows 251-300)
TAGS = {
251: dict(chapters=[("M1-C1-U0", None, [("9","What are Carve Outs/Ins in Ind AS?","1.18")])], scope="single", confidence="confident", notes=""),
252: dict(chapters=[("M3-C11-U2", None, [("2.4","Calculation of Cash Flows from Operating Activities","11.8")])], scope="single", confidence="confident", notes="Indirect method adjustments; AS3 convention."),
253: dict(chapters=[("M2-C8-U1","AS 7", [("1.5","Contract Revenue and Costs","8.7")])], scope="single", confidence="confident", notes="Loss on contract calc."),
254: dict(chapters=[("M1-C1-U0", None, [("2","Standards Setting Process","1.6")])], scope="single", confidence="confident", notes=""),
255: dict(chapters=[("M2-C5-U3","AS 13", [("3.5","Cost of Investments","5.8")])], scope="single", confidence="confident", notes=""),
256: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1. Case cluster 3b7a7ad5 (with rows 9, 202, 211) - consistent."),
257: dict(chapters=[("M2-C8-U1","AS 7", [("1.5","Contract Revenue and Costs","8.7")])], scope="single", confidence="confident", notes="Contract revenue components (incentive, cost recoveries)."),
258: dict(chapters=[("M1-C1-U0", None, [("2","Standards Setting Process","1.6")])], scope="single", confidence="confident", notes="ASB constituted 1977."),
259: dict(chapters=[("M2-C9-U2","AS 14", [("2.4","Amalgamation in the Nature of Merger","9.25")])], scope="single", confidence="confident", notes="Duplicate-chapter rule (row 106) - AS14 topic matches directly."),
260: dict(chapters=[("M1-C3-U0", None, [("2","Applicability of Accounting Standards","3.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 25 (5 MSME conditions, turnover-limit trick)."),
261: dict(chapters=[("M1-C2-U0", None, [("9","Elements of Financial Statements","2.13")])], scope="single", confidence="confident", notes="Five elements."),
262: dict(chapters=[("M2-C5-U2","AS 10", [("2.7","Initial Recognition","5.28")])], scope="single", confidence="confident", notes="Directly attributable costs capitalisation calc."),
263: dict(chapters=[("M1-C1-U0", None, [("2","Standards Setting Process","1.6")])], scope="single", confidence="confident", notes="Purpose of standard-setting bodies."),
264: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1 (Section 70 prohibited circumstances)."),
265: dict(chapters=[("M1-C1-U0", None, [("2","Standards Setting Process","1.6")])], scope="single", confidence="confident", notes="Exposure draft procedure."),
266: dict(chapters=[("M1-C2-U0", None, [("10","Measurement of Elements of Financial Statements","2.21")])], scope="single", confidence="confident", notes="Current Cost convention calc."),
267: dict(chapters=[("M3-C14-U0", None, [("8","Entries in case of internal reconstruction","14.12")])], scope="single", confidence="confident", notes="Capital Reduction A/c credit balance -> Capital Reserve."),
268: dict(chapters=[("M3-C11-U2", None, [("2.3","Classification of Cash Flow Activities","11.76")])], scope="single", confidence="confident", notes="Insurance claim classification; AS3 convention."),
269: dict(chapters=[("M2-C5-U2","AS 10", [("2.7","Initial Recognition","5.28")])],
    scope="single", confidence="confident", notes="Case cluster 6fce0c47 (with rows 2, 132) - this row is AS10, consistent with row 132's tag; row 2 remains the AS16 cross-chapter member (see row 132's note)."),
270: dict(chapters=[("M2-C5-U3","AS 13", [("3.4","Classification of Investments","5.8")])], scope="single", confidence="confident", notes="Stock-in-trade securities not investments."),
271: dict(chapters=[("M1-C1-U0", None, [("3","How Many Accounting Standards?","1.9")])], scope="single", confidence="confident", notes="Chapter-wise AS grouping table."),
272: dict(chapters=[("M1-C2-U0", None, [("6","Fundamental Accounting Assumptions","2.6")])], scope="single", confidence="confident", notes=""),
273: dict(chapters=[("M2-C5-U3","AS 13", [("3.7","Investment Properties","5.86")])], scope="single", confidence="confident", notes=""),
274: dict(chapters=[("M1-C2-U0", None, [("1","Introduction","2.2")])], scope="single", confidence="confident", notes="Framework issued July 2000."),
275: dict(chapters=[("M2-C9-U1","AS 12", [("1.9","Refund of Government Grants","9.11")])], scope="single", confidence="confident", notes=""),
276: dict(chapters=[("M2-C5-U7","AS 28", [("7.4","Measurement of Recoverable Amount","5.219")]),
                    ("M1-C2-U0", None, [("10","Measurement of Elements of Financial Statements","2.21")])],
    scope="multiple", confidence="inferred",
    notes="CSV chapter_id is 'Framework' and the calculation mechanics are Present-Value-convention arithmetic (a Framework topic), but 'Value in Use'/'Recoverable Amount' compared against carrying amount is specifically AS28 impairment vocabulary and logic, not Framework terminology - tagged as connected content across both, AS28 primary since that's the substantive concept being tested."),
277: dict(chapters=[("M3-C11-U1", None, [("1.5","Final Accounts","11.1")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 14 (negative Reserves and Surplus presentation)."),
278: dict(chapters=[("M1-C4-U5","AS 20", [("5.4","Per share- Basic","4.99")])], scope="single", confidence="confident", notes="Weighted average shares calc."),
279: dict(chapters=[("M3-C15-U0", None, [("5","Accounting for Dependent Branches","15.6")])], scope="single", confidence="confident", notes="Selling-price invoicing, Stock Reserve via Branch Adjustment."),
280: dict(chapters=[("M3-C11-U2", None, [("2.3","Classification of Cash Flow Activities","11.76")])],
    scope="single", confidence="confident", notes="Case cluster f5e7dfbc (with rows 91, 200) - all AS3, consistent. Income tax paid, default Operating classification."),
281: dict(chapters=[("M1-C2-U0", None, [("6","Fundamental Accounting Assumptions","2.6")])], scope="single", confidence="confident", notes="Going concern vs non-going concern basis."),
282: dict(chapters=[("M3-C11-U1", None, [("1.4","Annual Return","11.1")])], scope="single", confidence="confident", notes="Sec 92, 60-day filing window."),
283: dict(chapters=[("M2-C8-U2","AS 9", [("2.3","Agency Relationship","8.37")])], scope="single", confidence="confident", notes="Zigato food-delivery agent/principal revenue."),
284: dict(chapters=[("M1-C3-U0", None, [("2","Applicability of Accounting Standards","3.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 234 (MSME exemption disclosure requirement)."),
285: dict(chapters=[("M1-C1-U0", None, [("3","How Many Accounting Standards?","1.9")])], scope="single", confidence="confident", notes="2021 Rules - which ASs were/weren't revised to align with Ind AS."),
286: dict(chapters=[("M3-C14-U0", None, [("8","Entries in case of internal reconstruction","14.12")])],
    scope="single", confidence="confident",
    notes="Case cluster 7c0cf99a now spans AS3/Cash-Flow (rows 79, 194, 240) AND Internal Reconstruction (this row) - an unusual but genuine cross-chapter cluster (a combined case testing both a cash-flow reconciliation and an internal-reconstruction share-capital calc under one shared scenario), flagging per the open case-scenario-cluster issue."),
287: dict(chapters=[("M2-C9-U1","AS 12", [("1.9","Refund of Government Grants","9.11")])], scope="single", confidence="confident", notes="Prospective (not retrospective) depreciation after grant refund."),
288: dict(chapters=[("M1-C4-U3","AS 17", [("3.9","Identifying Reportable Segments (Quantitative Thresholds)","4.51")])], scope="single", confidence="confident", notes="Six-segment reportability across all three tests."),
289: dict(chapters=[("M2-C7-U1","AS 4", [("1.5","Non-Adjusting Events","7.4")])],
    scope="single", confidence="confident", notes="CSV chapter_id 'Financial Statements of Companies' mislabels this AS4 dividend-after-balance-sheet-date content - tagged per actual content."),
290: dict(chapters=[("M2-C9-U2","AS 14", [("2.9","Adjustments to reserves - Amalgamation in the Nature of Merger","9.28")])],
    scope="single", confidence="confident", notes="Duplicate-chapter rule (row 106) - AS14 topic matches directly."),
291: dict(chapters=[("M2-C7-U1","AS 4", [("1","Introduction","7.1")])],
    scope="single", confidence="flagged",
    notes="This row appears to be placeholder/test data, not a real question - question text is literally 'Question', all four options are 'Question', and the explanation is literally the word 'Question'. Same issue as row 224. Recommend Pranav review whether this row should be removed from the bank entirely."),
292: dict(chapters=[("M2-C7-U4","AS 22", [("4.4","Recognition","7.56")])], scope="single", confidence="confident", notes="DTA for carry-forward loss, reversal over subsequent years."),
293: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])],
    scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1. Case cluster 623873e2 (with row 122) - consistent."),
294: dict(chapters=[("M2-C7-U4","AS 22", [("4.8","Virtual certainty supported by convincing evidence","7.58")])], scope="single", confidence="confident", notes="DTA for carry-forward loss - virtual certainty standard."),
295: dict(chapters=[("M1-C4-U3","AS 17", [("3.12","Secondary Segment Information","4.54")])], scope="single", confidence="confident", notes=""),
296: dict(chapters=[("M3-C11-U1", None, [("1.5","Final Accounts","11.1")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 14 (fixed asset held for sale -> current asset)."),
297: dict(chapters=[("M1-C4-U3","AS 17", [("3.8","Business and Geographical Segments","4.5")])], scope="single", confidence="confident", notes="Business segment identification."),
298: dict(chapters=[("M2-C10-U1","AS 21", [("1.7","Exclusion from Preparation of Consolidated Financial Statements","10.12")])], scope="single", confidence="confident", notes=""),
299: dict(chapters=[("M2-C9-U2","AS 14", [("2.7","Consideration","9.27")])], scope="single", confidence="confident", notes="Liquidation-expense reimbursement cap, excess borne by vendor. Duplicate-chapter rule (row 106)."),
300: dict(chapters=[("M3-C15-U0", None, [("5","Accounting for Dependent Branches","15.6")])], scope="single", confidence="confident", notes="Memorandum Branch Debtors Account."),
}
