# Batch 4 (rows 151-200)
TAGS = {
151: dict(chapters=[("M2-C5-U3","AS 13", [("3.6","Carrying Amount of Investments","5.82")])], scope="single", confidence="confident", notes="Current investment write-down reversal up to cost."),
152: dict(chapters=[("M2-C6-U2","AS 29", [("2.4","Recognition of provision","6.32"), ("2.9","Contingent Liabilities","6.35")])], scope="single", confidence="confident", notes="Sales tax demand paid under protest, split appealed/non-appealed."),
153: dict(chapters=[("M2-C5-U1","AS 2", [("1.2","Inventories","5.2")])],
    scope="single", confidence="confident", notes="Case cluster 4778790b (with rows 10, 27) - AS2 classification question, same Year-1 slice as row 27."),
154: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1 (CRR calc for pref redemption + equity buy-back)."),
155: dict(chapters=[("M1-C1-U0", None, [("13","List of Ind AS","1.23")])], scope="single", confidence="confident", notes="Ind AS 33 -> old AS 20 mapping."),
156: dict(chapters=[("M2-C5-U2","AS 10", [("2.5","Recognition Criteria for PPE","5.26")])], scope="single", confidence="confident", notes="Environmental/safety assets."),
157: dict(chapters=[("M2-C5-U5","AS 19", [("5.3","Definitions","5.139")])],
    scope="single", confidence="inferred", notes="Lessor-side finance-lease accounting (Gross Investment, Unearned Finance Income) has no dedicated topic among the 10 listed for this unit (only 5.8 'Accounting for Finance Leases (Books of lessee)' exists) - mapped to Definitions, where these terms are defined. Flagging as a chapter-content gap for AS19's lessor side."),
158: dict(chapters=[("M1-C3-U0", None, [("1","Status of Accounting Standards","3.2")])], scope="single", confidence="confident", notes="3-question applicability sequence."),
159: dict(chapters=[("M1-C1-U0", None, [("3","How Many Accounting Standards?","1.9")])], scope="single", confidence="confident", notes="AS8 withdrawn."),
160: dict(chapters=[("M2-C6-U1","AS 15", [("1.12","Termination Benefits","6.21")])], scope="single", confidence="confident", notes=""),
161: dict(chapters=[("M2-C5-U2","AS 10", [("2.2","Scope of the Standard","5.22")])], scope="single", confidence="confident", notes="Bearer plants included, biological/wasting assets excluded."),
162: dict(chapters=[("M2-C9-U1","AS 12", [("1.6","Presentation of Grants Related to Specific Fixed Assets","9.4")])], scope="single", confidence="confident", notes="Case cluster 30b85fe4."),
163: dict(chapters=[("M2-C5-U2","AS 10", [("2.6","Measurement of PPE","5.27")])], scope="single", confidence="inferred", notes="Same Revaluation Model gap as row 117."),
164: dict(chapters=[("M3-C14-U0", None, [("7","Surrender of Shares","14.12")])], scope="single", confidence="confident", notes=""),
165: dict(chapters=[("M2-C10-U1","AS 21", [("1.11","Calculation of Goodwill/Capital Reserve (Cost of Control)","10.2")])], scope="single", confidence="confident", notes=""),
166: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1 (Debt-Equity Ratio Test theory)."),
167: dict(chapters=[("M1-C3-U0", None, [("1","Status of Accounting Standards","3.2")])], scope="single", confidence="confident", notes="AS mandatory for attest function even without statutory requirement."),
168: dict(chapters=[("M1-C4-U3","AS 17", [("3.9","Identifying Reportable Segments (Quantitative Thresholds)","4.51")])], scope="single", confidence="confident", notes="75% Overall Test."),
169: dict(chapters=[("M2-C6-U2","AS 29", [("2.19","Application of the Recognition and Measurement Rules","6.42")])],
    scope="single", confidence="inferred", notes="Restructuring provision scope not separately topic-numbered; mapped to the general recognition/measurement-rules-application topic."),
170: dict(chapters=[("M2-C5-U3","AS 13", [("3.5","Cost of Investments","5.8"), ("3.6","Carrying Amount of Investments","5.82")])],
    scope="single", confidence="confident",
    notes="Case cluster 3b2dee7b spans AS10 (row 57), AS28 (row 119), and now AS13 (this row) - a 3-chapter cluster under one shared narrative. Flagging per the open cross-chapter case-scenario-cluster issue; CSV chapter_id 'Other Accounting Standards' also mislabels this AS13 content (should be Assets Based Accounting Standards bucket) - tagged per actual content regardless."),
171: dict(chapters=[("M1-C2-U0", None, [("5","Objectives and Users of Financial Statements","2.5")])], scope="single", confidence="confident", notes="7 broad user groups."),
172: dict(chapters=[("M2-C5-U3","AS 13", [("3.6","Carrying Amount of Investments","5.82")])], scope="single", confidence="confident", notes="Case cluster fe39296d; investment-in-associate separate-FS carrying amount, pre-acquisition dividend."),
173: dict(chapters=[("M2-C7-U3","AS 11", [("3.11","Forward Exchange Contract","7.41")])], scope="single", confidence="confident", notes=""),
174: dict(chapters=[("M1-C2-U0", None, [("7","Qualitative Characteristics of Financial Statements","2.11")])], scope="single", confidence="confident", notes="Materiality definition."),
175: dict(chapters=[("M1-C1-U0", None, [("2","Standards Setting Process","1.6")])], scope="single", confidence="confident", notes="Section 133 Companies Act, NFRA consultation."),
176: dict(chapters=[("M3-C11-U2", None, [("2.5","Calculation of Cash Flows from Investing Activities","11.82")])],
    scope="single", confidence="confident",
    notes="Case cluster bc3fd25b spans AS10 (row 52, deferred-payment machinery) and AS3/Cash-Flow (this row and row 182) - flagging per the open cross-chapter case-scenario-cluster issue. Mapped to M3-C11-U2 per established AS3 convention."),
177: dict(chapters=[("M2-C6-U1","AS 15", [("1.7","Accounting Treatment","6.13")])], scope="single", confidence="confident", notes="7 components of defined benefit cost."),
178: dict(chapters=[("M2-C5-U1","AS 2", [("1.9","Exclusions from the cost of inventories","5.9")])], scope="single", confidence="confident", notes=""),
179: dict(chapters=[("M3-C11-U2", None, [("2.1","Introduction","11.73")])], scope="single", confidence="confident", notes="Mandatory applicability exemptions (OPC/Small/Dormant/start-up); AS3 convention."),
180: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1. Case cluster 9baffa7e."),
181: dict(chapters=[("M2-C6-U2","AS 29", [("2.9","Contingent Liabilities","6.35")])], scope="single", confidence="confident", notes=""),
182: dict(chapters=[("M3-C11-U2", None, [("2.5","Calculation of Cash Flows from Investing Activities","11.82"), ("2.6","Calculation of Cash Flows from Financing Activities","11.82")])],
    scope="single", confidence="confident", notes="Case cluster bc3fd25b (with rows 52, 176) - see row 176's note. Mapped to M3-C11-U2 per AS3 convention."),
183: dict(chapters=[("M2-C9-U2","AS 14", [("2.8","Treatment of Reserves of the Transferor Company on Amalgamation","9.28")])],
    scope="single", confidence="confident", notes="Duplicate-chapter rule (see row 106) - matches AS14 topic directly."),
184: dict(chapters=[("M3-C14-U0", None, [("1","Meaning of reconstruction","14.2")])], scope="single", confidence="confident", notes="Internal vs External Reconstruction."),
185: dict(chapters=[("M1-C3-U0", None, [("1","Status of Accounting Standards","3.2")])],
    scope="single", confidence="confident",
    notes="CORRECTED after cross-checking topic-index.json: 'materiality of financial items' is explicitly part of the Applicability chapter's topic 1 description (Preface to Statements of Accounting Standards), not the Framework - CSV's own 'Applicability' bucket was actually correct here. (Initially mis-tagged to Framework M1-C2-U0 by analogy with row 174's qualitative-characteristics materiality; corrected once row 233 surfaced the same pattern and the topic-index.json description was checked.)"),
186: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1 (12-month completion window)."),
187: dict(chapters=[("M3-C14-U0", None, [("5","Reduction of Share Capital","14.9")])], scope="single", confidence="confident", notes="'and Reduced' + 5-year disclosure requirement."),
188: dict(chapters=[("M1-C3-U0", None, [("2","Applicability of Accounting Standards","3.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 25 (SMC vs MSME AS17/3/20/24 exemption comparison)."),
189: dict(chapters=[("M3-C15-U0", None, [("5","Accounting for Dependent Branches","15.6")])], scope="single", confidence="confident", notes="Debtors Method."),
190: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1 (Sec 68(7) 6-month restriction)."),
191: dict(chapters=[("M1-C1-U0", None, [("3","How Many Accounting Standards?","1.9")])], scope="single", confidence="confident", notes="AS10(Revised) applicability date table."),
192: dict(chapters=[("M3-C12-U0", None, [("2","Provisions of Section 70 of the Companies Act, 2013","12.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 1. Case cluster 2b23f733."),
193: dict(chapters=[("M1-C3-U0", None, [("2","Applicability of Accounting Standards","3.6")])], scope="single", confidence="confident", notes="SMC/Non-SMC classification scheme - core topic-2 content, not just an MSME sub-detail."),
194: dict(chapters=[("M3-C11-U2", None, [("2.4","Calculation of Cash Flows from Operating Activities","11.8")])],
    scope="single", confidence="confident", notes="Case cluster 7c0cf99a (with row 79) - both AS3, consistent."),
195: dict(chapters=[("M2-C9-U1","AS 12", [("1.8","Presentation of Grants of the Nature of Promoters' Contribution","9.9")])], scope="single", confidence="confident", notes="Central Investment Subsidy."),
196: dict(chapters=[("M1-C1-U0", None, [("3","How Many Accounting Standards?","1.9")])], scope="single", confidence="confident", notes="27 effective standards."),
197: dict(chapters=[("M2-C6-U2","AS 29", [("2.4","Recognition of provision","6.32"), ("2.7","Probable Outflow of Resources Embodying Economic Benefits","6.34")])],
    scope="single", confidence="confident",
    notes="Case cluster dd4cd032 spans AS9 (row 107, bill-and-hold revenue recognition) and AS29 (this row, legal cost/claim provision) - flagging per the open cross-chapter case-scenario-cluster issue."),
198: dict(chapters=[("M3-C14-U0", None, [("5","Reduction of Share Capital","14.9")])], scope="single", confidence="confident", notes="Section 66 three ways of capital reduction."),
199: dict(chapters=[("M1-C3-U0", None, [("2","Applicability of Accounting Standards","3.6")])], scope="single", confidence="inferred", notes="Same coarse-topic-list caveat as row 188 (SMC AS20 diluted-EPS exemption)."),
200: dict(chapters=[("M3-C11-U2", None, [("2.3","Classification of Cash Flow Activities","11.76")])],
    scope="single", confidence="confident", notes="Case cluster f5e7dfbc (with row 91) - both AS3, consistent. Financial-enterprise interest classification rule."),
}
