#!/usr/bin/env python3
"""
fetch_local_fonts.py — vendor the strategy book's Google Fonts locally.

WHY THIS EXISTS
----------------
The strategy-book HTML (generated by strategy_book_parser.py) used to load
its fonts via `@import url('https://fonts.googleapis.com/...')`. That is a
network dependency, and on the whole-book merged file specifically, it was
one of the suspects chased down while debugging a pagination-instability
bug (see Claude_V2.md section 15 / project_log.md 2026-07-22) -- vendoring
the fonts locally removes that network dependency entirely, the same
principle already applied to paged.js itself (design/templates/vendor/
paged.polyfill.js).

WHY THE OUTPUT OF THIS SCRIPT IS NOT COMMITTED TO GIT
--------------------------------------------------------
The font files (.woff2) are binary, and this repo's explicit rule is no
binary files in git (see .gitignore's header comment and its Fonts section).
`gfonts-local.css` (the stylesheet that references those files) is plain
text and COULD be committed on its own, but it's excluded too, deliberately
-- committing it separately from the binaries it references risks the two
drifting out of sync (e.g. if a future run of this script downloads
differently-numbered files, a stale committed gfonts-local.css would
reference files that no longer exist). Instead, both are always regenerated
together, by running this script, exactly like `design/templates/build/`
itself is never committed and is instead regenerated from MASTER.md via
strategy_book_parser.py.

RUN THIS:
    - Right after cloning this repo onto a new machine, before generating
      any strategy-book HTML, OR
    - Any time books/strategy-book/design/templates/vendor/fonts/ or
      gfonts-local.css is missing (strategy_book_parser.py's generated
      HTML references them via a <link> tag; if they're absent the browser
      just silently falls back to system fonts -- not a hard error, but a
      visual regression worth avoiding).

Usage:
    python tools/fetch_local_fonts.py
"""

import re
import sys
import urllib.request
from pathlib import Path

# Must match the family/weight query strategy_book_parser.py's get_css()
# is written for (Archivo headings, Source Sans 3 body, Kalam handwritten
# accent) -- if that changes, update this query string to match.
GOOGLE_FONTS_CSS_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=Archivo:wght@400;500;600;700;800;900"
    "&family=Source+Sans+3:ital,wght@0,400;0,600;1,400"
    "&family=Kalam:wght@300;400;700"
    "&display=swap"
)

# Google serves different font formats (woff2/woff/ttf) depending on the
# requesting User-Agent. This must look like a modern Chrome so we get
# woff2 (small, universally supported by anything that can render this
# book anyway, since paged.js itself requires a modern Chromium).
USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
)

VENDOR_DIR = (
    Path(__file__).resolve().parent.parent
    / "books" / "strategy-book" / "design" / "templates" / "vendor"
)
FONTS_DIR = VENDOR_DIR / "fonts"
OUTPUT_CSS = VENDOR_DIR / "gfonts-local.css"


def main():
    print(f"Fetching font CSS from Google Fonts...")
    req = urllib.request.Request(GOOGLE_FONTS_CSS_URL, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=15) as resp:
        css = resp.read().decode("utf-8")

    urls = re.findall(r"url\((https://fonts\.gstatic\.com/[^)]+)\)", css)
    if not urls:
        print("ERROR: no font file URLs found in the fetched CSS -- Google's "
              "response format may have changed, or the query URL above is "
              "stale.", file=sys.stderr)
        sys.exit(1)
    print(f"  {len(urls)} @font-face declarations found")

    FONTS_DIR.mkdir(parents=True, exist_ok=True)
    url_to_local = {}
    for i, url in enumerate(urls):
        if url in url_to_local:
            continue
        ext = ".woff2" if ".woff2" in url else (".ttf" if ".ttf" in url else ".woff")
        fname = f"font-{i:03d}{ext}"
        urllib.request.urlretrieve(url, FONTS_DIR / fname)
        url_to_local[url] = fname

    def repl(m):
        return f"url(fonts/{url_to_local[m.group(1)]})"

    local_css = re.sub(r"url\((https://fonts\.gstatic\.com/[^)]+)\)", repl, css)
    OUTPUT_CSS.write_text(local_css, encoding="utf-8")

    print(f"  Downloaded {len(url_to_local)} unique font files -> {FONTS_DIR}")
    print(f"  Wrote {OUTPUT_CSS}")
    print("Done. strategy_book_parser.py's generated HTML already references "
          "this via <link rel=\"stylesheet\" href=\"../vendor/gfonts-local.css\"> "
          "-- no other setup needed.")


if __name__ == "__main__":
    main()
