#!/usr/bin/env python3
"""file_index.py — auto-generate a tracked-file listing for the repo.

Writes a tree of all source/text files (skips gitignored binaries, .git,
.venv, __pycache__) to _claude/artifacts/file-index.md.

Usage:  python tools/file_index.py
"""
from __future__ import annotations
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "_claude" / "artifacts" / "file-index.md"

SKIP_DIRS = {".git", ".venv", "__pycache__", ".idea", ".vscode"}
# Binary extensions we never index (mirrors .gitignore intent)
SKIP_EXT = {
    ".pdf", ".docx", ".doc", ".pptx", ".ppt", ".xlsx", ".xls",
    ".jpg", ".jpeg", ".png", ".gif", ".bmp", ".tiff", ".tif", ".webp", ".psd", ".ico",
    ".mp3", ".wav", ".m4a", ".aac", ".flac", ".ogg",
    ".mp4", ".mov", ".mkv", ".avi", ".webm", ".wmv",
    ".zip", ".rar", ".7z", ".tar", ".gz", ".exe", ".dll", ".msi", ".bin", ".iso",
    ".pyc",
}


def walk(d: Path, prefix: str, lines: list[str]) -> None:
    entries = sorted(
        [e for e in d.iterdir() if e.name not in SKIP_DIRS and not e.name.startswith(".git")],
        key=lambda e: (e.is_file(), e.name.lower()),
    )
    for e in entries:
        if e.is_dir():
            lines.append(f"{prefix}- **{e.name}/**")
            walk(e, prefix + "  ", lines)
        elif e.suffix.lower() not in SKIP_EXT:
            lines.append(f"{prefix}- {e.name}")


def main() -> None:
    lines: list[str] = [
        "# File Index — cap-online",
        "",
        f"_Auto-generated by `tools/file_index.py` on {date.today().isoformat()}._",
        "_Lists tracked source/text files only; binaries are gitignored and omitted._",
        "",
    ]
    walk(ROOT, "", lines)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    count = sum(1 for ln in lines if ln.strip().startswith("- ") and "**" not in ln)
    print(f"Wrote {OUT.relative_to(ROOT)} ({count} files indexed).")


if __name__ == "__main__":
    main()
