#!/usr/bin/env python3
"""file_index.py - generate a complete, searchable index of every file in the repo.

Writes _claude/artifacts/file-index.md with:
  1. A flat A-Z lookup table (filename -> folder) — Ctrl-F a name to find where it lives.
  2. A full folder tree.
Includes binaries (PDF/xlsx/video/images) tagged (local) since they're gitignored
and live on disk only. Skips .git / .venv / __pycache__ / node_modules.

Usage:  python tools/file_index.py
"""
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "_claude" / "artifacts" / "file-index.md"

SKIP_DIRS = {".git", ".venv", "__pycache__", ".idea", ".vscode", "node_modules"}
# extensions that are gitignored (live locally only) -> tagged "(local)"
LOCAL_EXT = {
    ".pdf", ".docx", ".doc", ".pptx", ".ppt", ".xlsx", ".xls",
    ".jpg", ".jpeg", ".png", ".gif", ".bmp", ".tiff", ".tif", ".webp", ".psd", ".ico",
    ".mp3", ".wav", ".m4a", ".aac", ".flac", ".ogg",
    ".mp4", ".mov", ".mkv", ".avi", ".webm", ".wmv",
    ".zip", ".rar", ".7z", ".tar", ".gz", ".exe", ".dll", ".msi", ".bin", ".iso",
}


def all_files():
    files = []
    for p in ROOT.rglob("*"):
        if not p.is_file():
            continue
        if any(part in SKIP_DIRS for part in p.parts):
            continue
        if p.name == ".gitkeep":
            continue
        files.append(p)
    return files


def is_local(p: Path) -> bool:
    return p.suffix.lower() in LOCAL_EXT


def flat_table(files):
    lines = ["## Find a file (A–Z)", "",
             "_Ctrl-F a filename. `(local)` = gitignored binary, on disk only._", "",
             "| File | Location | |", "|------|----------|---|"]
    for p in sorted(files, key=lambda x: (x.name.lower(), str(x).lower())):
        folder = str(p.parent.relative_to(ROOT)).replace("\\", "/")
        if folder == ".":
            folder = "(root)"
        tag = "(local)" if is_local(p) else ""
        lines.append("| `%s` | `%s/` | %s |" % (p.name, folder, tag))
    return lines


def tree(files):
    # build nested dict
    root = {}
    for p in files:
        node = root
        parts = p.relative_to(ROOT).parts
        for d in parts[:-1]:
            node = node.setdefault(d, {})
        node.setdefault("__files__", []).append(p)

    out = ["## Full tree", ""]

    def walk(node, prefix):
        for name in sorted(k for k in node if k != "__files__"):
            out.append("%s- **%s/**" % (prefix, name))
            walk(node[name], prefix + "  ")
        for p in sorted(node.get("__files__", []), key=lambda x: x.name.lower()):
            tag = " (local)" if is_local(p) else ""
            out.append("%s- %s%s" % (prefix, p.name, tag))

    walk(root, "")
    return out


def main():
    files = all_files()
    local = sum(1 for p in files if is_local(p))
    header = [
        "# File Index — cap-online",
        "",
        "_Auto-generated by `tools/file_index.py` on %s._" % date.today().isoformat(),
        "_%d files total (%d tracked text, %d local-only binaries). "
        "Run the script after any structural change to refresh._" % (
            len(files), len(files) - local, local),
        "",
    ]
    body = header + flat_table(files) + ["", "---", ""] + tree(files)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(body) + "\n", encoding="utf-8")
    print("Wrote %s (%d files: %d text, %d local)." % (
        OUT.relative_to(ROOT), len(files), len(files) - local, local))


if __name__ == "__main__":
    main()
