#!/usr/bin/env python3
"""generate_style_css.py - the ONLY thing allowed to write book-style.css.

Reads book-style.json (the single source of truth for every font size, spacing
value, colour, and page-geometry number in the Question Bank Book pipeline) and
writes book-style.css next to it. Every generated HTML file (sitting-level,
chapter-wise, and the final merged book) links to book-style.css and must never
hardcode a font-size/margin/colour value itself.

Usage: python generate_style_css.py
(re-run any time book-style.json changes; nothing else needs to change)
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
JSON_PATH = HERE / "book-style.json"
CSS_PATH = HERE / "book-style.css"


def build_css(style: dict) -> str:
    t = style["typography"]
    c = style["colors"]
    s = style["spacing"]

    return f"""/* AUTO-GENERATED by generate_style_css.py from book-style.json - DO NOT EDIT DIRECTLY.
   To change any font size, spacing, or colour anywhere in the Question Bank Book,
   edit book-style.json and re-run generate_style_css.py. Every HTML file that
   links to this stylesheet picks up the change immediately - no HTML file needs
   to be regenerated or hand-edited for a pure style change. */

*, *::before, *::after {{
  box-sizing: border-box;
  print-color-adjust: exact;
  -webkit-print-color-adjust: exact;
}}

:root {{
  --body-font: {t['body_font']};
  --heading-font: {t['heading_font']};
  --mono-font: {t['mono_font']};
  --body-font-size: {t['body_font_size']};
  --body-line-height: {t['body_line_height']};
  --paragraph-spacing: {t['paragraph_spacing']};
  --h1-font-size: {t['h1_font_size']};
  --h2-font-size: {t['h2_font_size']};
  --h3-font-size: {t['h3_font_size']};
  --small-font-size: {t['small_font_size']};
  --table-font-size: {t['table_font_size']};

  --ink: {c['ink']};
  --muted-ink: {c['muted_ink']};
  --page-bg: {c['page_bg']};
  --accent: {c['accent']};
  --table-border: {c['table_border']};
  --table-header-bg: {c['table_header_bg']};
  --table-header-ink: {c['table_header_ink']};
  --table-zebra-bg: {c['table_zebra_bg']};
  --question-block-border: {c['question_block_border']};
  --question-block-bg: {c['question_block_bg']};
  --answer-block-bg: {c['answer_block_bg']};
  --examiner-comment-bg: {c['examiner_comment_bg']};
  --examiner-comment-border: {c['examiner_comment_border']};
  --synthesized-comment-bg: {c['synthesized_comment_bg']};
  --synthesized-comment-border: {c['synthesized_comment_border']};
  --author-comment-border: {c['author_comment_border']};
  --flagged-border: {c['flagged_border']};
  --flagged-bg: {c['flagged_bg']};

  --page-margin: {s['page_margin']};
  --qblock-margin: {s['qblock_margin']};
  --qblock-padding: {s['qblock_padding']};
  --qblock-border-radius: {s['qblock_border_radius']};
  --section-gap: {s['section_gap']};
}}

body {{
  font-family: var(--body-font);
  font-size: var(--body-font-size);
  line-height: var(--body-line-height);
  color: var(--ink);
  background: var(--page-bg);
  max-width: 980px;
  margin: 0 auto;
  padding: var(--page-margin);
}}

h1 {{ font-family: var(--heading-font); font-size: var(--h1-font-size); margin-bottom: 4px; }}
h2 {{ font-family: var(--heading-font); font-size: var(--h2-font-size); margin-top: var(--section-gap); border-bottom: 2px solid var(--accent); padding-bottom: 6px; }}
h3 {{ font-family: var(--heading-font); font-size: var(--h3-font-size); }}

p {{ margin: 0 0 var(--paragraph-spacing) 0; }}

table {{
  border-collapse: collapse;
  width: 100%;
  margin: 10px 0;
  font-size: var(--table-font-size);
}}
th, td {{
  border: 1px solid var(--table-border);
  padding: 5px 7px;
  text-align: left;
  vertical-align: top;
}}
th {{ background: var(--table-header-bg); color: var(--table-header-ink); }}
tr:nth-child(even) {{ background: var(--table-zebra-bg); }}
td.num, th.num {{ text-align: right; white-space: nowrap; }}

/* ── Per-question block (see HTML-SCHEMA.md for the full structure) ── */
.qblock {{
  border: 1px solid var(--question-block-border);
  border-radius: var(--qblock-border-radius);
  padding: var(--qblock-padding);
  margin: var(--qblock-margin);
  background: var(--question-block-bg);
  break-inside: avoid;
}}
.qblock.flagged {{ border-color: var(--flagged-border); background: var(--flagged-bg); }}

.qmeta {{
  font-size: var(--small-font-size);
  color: var(--muted-ink);
  margin-bottom: 10px;
  padding-bottom: 8px;
  border-bottom: 1px dashed var(--question-block-border);
}}
.qmeta .src {{ font-weight: bold; color: var(--accent); }}

.question {{ margin: 10px 0; }}

.answer-block {{
  margin: 10px 0;
  background: var(--answer-block-bg);
  padding: 8px 12px;
  border-radius: 6px;
}}

.topics {{ margin: 10px 0; }}
.topic-tag {{
  display: inline-block;
  font-size: var(--small-font-size);
  background: #eef1f4;
  border: 1px solid var(--question-block-border);
  border-radius: 10px;
  padding: 2px 10px;
  margin: 2px 4px 2px 0;
}}

.examiner-comment {{
  margin: 10px 0;
  background: var(--examiner-comment-bg);
  border: 1px solid var(--examiner-comment-border);
  border-radius: 6px;
  padding: 8px 12px;
  font-size: var(--small-font-size);
}}
.examiner-comment.synthesized {{
  background: var(--synthesized-comment-bg);
  border-color: var(--synthesized-comment-border);
}}

.author-comment {{
  display: none; /* hidden/idle placeholder - Pranav toggles visibility manually when he has notes to add */
  margin: 10px 0;
  border-left: 3px solid var(--author-comment-border);
  padding: 6px 12px;
  font-size: var(--small-font-size);
}}

.extraction-note {{
  margin-top: 8px;
  font-size: var(--small-font-size);
  color: var(--muted-ink);
  font-style: italic;
}}
.extraction-note.flagged-note {{ color: #a33; font-weight: bold; font-style: normal; }}

.na {{ color: #999; font-style: italic; }}
"""


def main():
    style = json.loads(JSON_PATH.read_text(encoding="utf-8"))
    css = build_css(style)
    CSS_PATH.write_text(css, encoding="utf-8", newline="\n")
    print(f"Wrote {CSS_PATH} ({len(css)} chars) from {JSON_PATH.name}")


if __name__ == "__main__":
    main()
